-- +goose Up

-- ---------------------------------------------------------------------------
-- Identity and tenancy
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id                text PRIMARY KEY,
    email             text NOT NULL,
    name              text NOT NULL DEFAULT '',
    password_hash     text NOT NULL,
    email_verified_at timestamptz,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX users_email_key ON users (lower(email));

CREATE TABLE sessions (
    id           text PRIMARY KEY,
    user_id      text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash   bytea NOT NULL UNIQUE,
    ip           inet,
    user_agent   text NOT NULL DEFAULT '',
    created_at   timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL
);
CREATE INDEX sessions_user_id_idx ON sessions (user_id);
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

CREATE TABLE organizations (
    id         text PRIMARY KEY,
    name       text NOT NULL,
    slug       text NOT NULL UNIQUE,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TYPE member_role AS ENUM ('owner', 'admin', 'member');

CREATE TABLE organization_members (
    id              text PRIMARY KEY,
    organization_id text NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    user_id         text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role            member_role NOT NULL DEFAULT 'member',
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organization_id, user_id)
);
CREATE INDEX organization_members_user_id_idx ON organization_members (user_id);

CREATE TABLE projects (
    id              text PRIMARY KEY,
    organization_id text NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    name            text NOT NULL,
    slug            text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (organization_id, slug)
);

-- ---------------------------------------------------------------------------
-- Credentials
-- ---------------------------------------------------------------------------

CREATE TYPE api_environment AS ENUM ('live', 'test');

CREATE TABLE api_keys (
    id           text PRIMARY KEY,
    project_id   text NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    name         text NOT NULL,
    environment  api_environment NOT NULL,
    key_prefix   text NOT NULL,
    key_hash     bytea NOT NULL UNIQUE,
    created_by   text REFERENCES users (id) ON DELETE SET NULL,
    last_used_at timestamptz,
    expires_at   timestamptz,
    revoked_at   timestamptz,
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX api_keys_project_id_idx ON api_keys (project_id);

-- ---------------------------------------------------------------------------
-- Devices (Android gateways)
-- ---------------------------------------------------------------------------

CREATE TYPE device_status AS ENUM ('online', 'offline', 'disabled');

CREATE TABLE devices (
    id                text PRIMARY KEY,
    project_id        text NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    name              text NOT NULL,
    -- Random per-install identifier generated by the app. Never a hardware ID.
    installation_id   text NOT NULL,
    credential_hash   bytea NOT NULL UNIQUE,
    status            device_status NOT NULL DEFAULT 'offline',
    last_heartbeat_at timestamptz,
    last_seen_at      timestamptz,
    battery_level     smallint CHECK (battery_level BETWEEN 0 AND 100),
    is_charging       boolean,
    network_type      text,
    carrier_name      text,
    sim_count         smallint,
    device_model      text,
    android_version   text,
    app_version       text,
    push_token        text,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    revoked_at        timestamptz,
    UNIQUE (project_id, installation_id)
);
CREATE INDEX devices_project_id_idx ON devices (project_id);

CREATE TABLE device_pairing_tokens (
    id         text PRIMARY KEY,
    project_id text NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    token_hash bytea NOT NULL UNIQUE,
    created_by text REFERENCES users (id) ON DELETE SET NULL,
    device_id  text REFERENCES devices (id) ON DELETE SET NULL,
    expires_at timestamptz NOT NULL,
    used_at    timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX device_pairing_tokens_expires_at_idx ON device_pairing_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- Messages
-- ---------------------------------------------------------------------------

CREATE TYPE message_direction AS ENUM ('outbound', 'inbound');
CREATE TYPE message_status AS ENUM ('created', 'queued', 'sending', 'sent', 'delivered', 'failed', 'received');

CREATE TABLE messages (
    id                  text PRIMARY KEY,
    project_id          text NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    environment         api_environment NOT NULL,
    direction           message_direction NOT NULL,
    status              message_status NOT NULL,
    provider            text NOT NULL,
    device_id           text REFERENCES devices (id) ON DELETE SET NULL,
    api_key_id          text REFERENCES api_keys (id) ON DELETE SET NULL,
    recipient           text NOT NULL,
    sender              text,
    body                text NOT NULL,
    segments            smallint,
    attempts            integer NOT NULL DEFAULT 0,
    provider_message_id text,
    error_code          text,
    error_message       text,
    metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
    idempotency_key     text,
    created_at          timestamptz NOT NULL DEFAULT now(),
    queued_at           timestamptz,
    sending_at          timestamptz,
    sent_at             timestamptz,
    delivered_at        timestamptz,
    failed_at           timestamptz,
    updated_at          timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, idempotency_key)
);
CREATE INDEX messages_project_created_idx ON messages (project_id, created_at DESC, id DESC);
CREATE INDEX messages_device_pending_idx ON messages (device_id, created_at) WHERE status IN ('queued', 'sending');

CREATE TABLE message_events (
    id          text PRIMARY KEY,
    message_id  text NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    project_id  text NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    type        text NOT NULL,
    from_status message_status,
    to_status   message_status,
    detail      jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX message_events_message_idx ON message_events (message_id, created_at);

-- ---------------------------------------------------------------------------
-- Operations
-- ---------------------------------------------------------------------------

CREATE TABLE audit_logs (
    id              text PRIMARY KEY,
    organization_id text NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    project_id      text,
    actor_type      text NOT NULL,
    actor_id        text,
    action          text NOT NULL,
    target_type     text,
    target_id       text,
    metadata        jsonb NOT NULL DEFAULT '{}'::jsonb,
    ip              inet,
    created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX audit_logs_org_created_idx ON audit_logs (organization_id, created_at DESC);

-- Fixed-window rate-limit counters. UNLOGGED: losing counters on crash is acceptable.
CREATE UNLOGGED TABLE rate_limit_counters (
    key          text PRIMARY KEY,
    window_start timestamptz NOT NULL,
    count        integer NOT NULL
);

-- +goose Down
DROP TABLE rate_limit_counters;
DROP TABLE audit_logs;
DROP TABLE message_events;
DROP TABLE messages;
DROP TYPE message_status;
DROP TYPE message_direction;
DROP TABLE device_pairing_tokens;
DROP TABLE devices;
DROP TYPE device_status;
DROP TABLE api_keys;
DROP TYPE api_environment;
DROP TABLE projects;
DROP TABLE organization_members;
DROP TYPE member_role;
DROP TABLE organizations;
DROP TABLE sessions;
DROP TABLE users;
