// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package dbq

import (
	"context"
	"time"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, project_id, name, environment, key_prefix, key_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, name, environment, key_prefix, key_hash, created_by, last_used_at, expires_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	ID          string
	ProjectID   string
	Name        string
	Environment APIEnvironment
	KeyPrefix   string
	KeyHash     []byte
	CreatedBy   *string
	ExpiresAt   *time.Time
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (APIKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Environment,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Environment,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, project_id, name, environment, key_prefix, key_hash, created_by, last_used_at, expires_at, revoked_at, created_at FROM api_keys WHERE id = $1 AND project_id = $2
`

type GetAPIKeyParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (APIKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.ID, arg.ProjectID)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Environment,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyForAuth = `-- name: GetAPIKeyForAuth :one
SELECT k.id, k.project_id, k.name, k.environment, k.expires_at, k.revoked_at, k.last_used_at,
       p.organization_id, p.name AS project_name
FROM api_keys k
JOIN projects p ON p.id = k.project_id
WHERE k.key_hash = $1
`

type GetAPIKeyForAuthRow struct {
	ID             string
	ProjectID      string
	Name           string
	Environment    APIEnvironment
	ExpiresAt      *time.Time
	RevokedAt      *time.Time
	LastUsedAt     *time.Time
	OrganizationID string
	ProjectName    string
}

func (q *Queries) GetAPIKeyForAuth(ctx context.Context, keyHash []byte) (GetAPIKeyForAuthRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyForAuth, keyHash)
	var i GetAPIKeyForAuthRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Environment,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastUsedAt,
		&i.OrganizationID,
		&i.ProjectName,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, project_id, name, environment, key_prefix, key_hash, created_by, last_used_at, expires_at, revoked_at, created_at FROM api_keys
WHERE project_id = $1
ORDER BY (revoked_at IS NOT NULL), created_at DESC, id DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, projectID string) ([]APIKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []APIKey{}
	for rows.Next() {
		var i APIKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Environment,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.CreatedBy,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys SET revoked_at = now()
WHERE id = $1 AND project_id = $2 AND revoked_at IS NULL
RETURNING id, project_id, name, environment, key_prefix, key_hash, created_by, last_used_at, expires_at, revoked_at, created_at
`

type RevokeAPIKeyParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (APIKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.ProjectID)
	var i APIKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Environment,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedBy,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
