// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbq

import (
	"context"
	"encoding/json"
	"net/netip"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (id, organization_id, project_id, actor_type, actor_id, action, target_type, target_id, metadata, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAuditLogParams struct {
	ID             string
	OrganizationID string
	ProjectID      *string
	ActorType      string
	ActorID        *string
	Action         string
	TargetType     *string
	TargetID       *string
	Metadata       json.RawMessage
	IP             *netip.Addr
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ID,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Metadata,
		arg.IP,
	)
	return err
}

const listAuditLogsForProject = `-- name: ListAuditLogsForProject :many
SELECT id, organization_id, project_id, actor_type, actor_id, action, target_type, target_id, metadata, ip, created_at FROM audit_logs
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAuditLogsForProjectParams struct {
	ProjectID *string
	Limit     int32
}

func (q *Queries) ListAuditLogsForProject(ctx context.Context, arg ListAuditLogsForProjectParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsForProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.IP,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
