// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automation.sql

package dbq

import (
	"context"
	"time"
)

const claimAutomationDefaults = `-- name: ClaimAutomationDefaults :execrows

INSERT INTO automation_settings (project_id) VALUES ($1) ON CONFLICT (project_id) DO NOTHING
`

// ---- Auto-replies -----------------------------------------------------------
// Returns 1 the first time for a project, when its default rules should be created.
func (q *Queries) ClaimAutomationDefaults(ctx context.Context, projectID string) (int64, error) {
	result, err := q.db.Exec(ctx, claimAutomationDefaults, projectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAutoReplyRule = `-- name: DeleteAutoReplyRule :execrows
DELETE FROM auto_reply_rules WHERE id = $1 AND project_id = $2
`

type DeleteAutoReplyRuleParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) DeleteAutoReplyRule(ctx context.Context, arg DeleteAutoReplyRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAutoReplyRule, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteForwardingDestination = `-- name: DeleteForwardingDestination :exec
DELETE FROM forwarding_destinations WHERE id = $1 AND rule_id = $2
`

type DeleteForwardingDestinationParams struct {
	ID     string
	RuleID string
}

func (q *Queries) DeleteForwardingDestination(ctx context.Context, arg DeleteForwardingDestinationParams) error {
	_, err := q.db.Exec(ctx, deleteForwardingDestination, arg.ID, arg.RuleID)
	return err
}

const deleteForwardingRule = `-- name: DeleteForwardingRule :execrows
DELETE FROM forwarding_rules WHERE id = $1 AND project_id = $2
`

type DeleteForwardingRuleParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) DeleteForwardingRule(ctx context.Context, arg DeleteForwardingRuleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteForwardingRule, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldForwardingDeliveries = `-- name: DeleteOldForwardingDeliveries :execrows
DELETE FROM forwarding_deliveries WHERE created_at < $1
`

func (q *Queries) DeleteOldForwardingDeliveries(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldForwardingDeliveries, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOptOut = `-- name: DeleteOptOut :one
DELETE FROM opt_outs WHERE project_id = $1 AND number = $2
RETURNING id, project_id, number, source, keyword, created_at
`

type DeleteOptOutParams struct {
	ProjectID string
	Number    string
}

func (q *Queries) DeleteOptOut(ctx context.Context, arg DeleteOptOutParams) (OptOut, error) {
	row := q.db.QueryRow(ctx, deleteOptOut, arg.ProjectID, arg.Number)
	var i OptOut
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Source,
		&i.Keyword,
		&i.CreatedAt,
	)
	return i, err
}

const getAutoReplyRule = `-- name: GetAutoReplyRule :one
SELECT id, project_id, name, match_type, keywords, reply, action, enabled, priority, created_at, updated_at FROM auto_reply_rules WHERE id = $1 AND project_id = $2
`

type GetAutoReplyRuleParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetAutoReplyRule(ctx context.Context, arg GetAutoReplyRuleParams) (AutoReplyRule, error) {
	row := q.db.QueryRow(ctx, getAutoReplyRule, arg.ID, arg.ProjectID)
	var i AutoReplyRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.MatchType,
		&i.Keywords,
		&i.Reply,
		&i.Action,
		&i.Enabled,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getForwardingDelivery = `-- name: GetForwardingDelivery :one
SELECT id, rule_id, destination_id, project_id, message_id, status, attempts, response_status, error, forwarded_message_id, created_at, updated_at FROM forwarding_deliveries WHERE id = $1
`

func (q *Queries) GetForwardingDelivery(ctx context.Context, id string) (ForwardingDelivery, error) {
	row := q.db.QueryRow(ctx, getForwardingDelivery, id)
	var i ForwardingDelivery
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.DestinationID,
		&i.ProjectID,
		&i.MessageID,
		&i.Status,
		&i.Attempts,
		&i.ResponseStatus,
		&i.Error,
		&i.ForwardedMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getForwardingDestination = `-- name: GetForwardingDestination :one
SELECT id, rule_id, project_id, type, target, format, secret, position, created_at FROM forwarding_destinations WHERE id = $1
`

func (q *Queries) GetForwardingDestination(ctx context.Context, id string) (ForwardingDestination, error) {
	row := q.db.QueryRow(ctx, getForwardingDestination, id)
	var i ForwardingDestination
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ProjectID,
		&i.Type,
		&i.Target,
		&i.Format,
		&i.Secret,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getForwardingRule = `-- name: GetForwardingRule :one
SELECT id, project_id, name, enabled, senders, contains, signing_secret, created_at, updated_at FROM forwarding_rules WHERE id = $1 AND project_id = $2
`

type GetForwardingRuleParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetForwardingRule(ctx context.Context, arg GetForwardingRuleParams) (ForwardingRule, error) {
	row := q.db.QueryRow(ctx, getForwardingRule, arg.ID, arg.ProjectID)
	var i ForwardingRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.Senders,
		&i.Contains,
		&i.SigningSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getForwardingRuleByID = `-- name: GetForwardingRuleByID :one
SELECT id, project_id, name, enabled, senders, contains, signing_secret, created_at, updated_at FROM forwarding_rules WHERE id = $1
`

func (q *Queries) GetForwardingRuleByID(ctx context.Context, id string) (ForwardingRule, error) {
	row := q.db.QueryRow(ctx, getForwardingRuleByID, id)
	var i ForwardingRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.Senders,
		&i.Contains,
		&i.SigningSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOptOut = `-- name: GetOptOut :one
SELECT id, project_id, number, source, keyword, created_at FROM opt_outs WHERE project_id = $1 AND number = $2
`

type GetOptOutParams struct {
	ProjectID string
	Number    string
}

func (q *Queries) GetOptOut(ctx context.Context, arg GetOptOutParams) (OptOut, error) {
	row := q.db.QueryRow(ctx, getOptOut, arg.ProjectID, arg.Number)
	var i OptOut
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Source,
		&i.Keyword,
		&i.CreatedAt,
	)
	return i, err
}

const getOptOutByID = `-- name: GetOptOutByID :one
SELECT id, project_id, number, source, keyword, created_at FROM opt_outs WHERE id = $1 AND project_id = $2
`

type GetOptOutByIDParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetOptOutByID(ctx context.Context, arg GetOptOutByIDParams) (OptOut, error) {
	row := q.db.QueryRow(ctx, getOptOutByID, arg.ID, arg.ProjectID)
	var i OptOut
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Source,
		&i.Keyword,
		&i.CreatedAt,
	)
	return i, err
}

const hasMessageEvent = `-- name: HasMessageEvent :one
SELECT EXISTS (SELECT 1 FROM message_events WHERE message_id = $1 AND type = $2)
`

type HasMessageEventParams struct {
	MessageID string
	Type      string
}

func (q *Queries) HasMessageEvent(ctx context.Context, arg HasMessageEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasMessageEvent, arg.MessageID, arg.Type)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAutoReplyRule = `-- name: InsertAutoReplyRule :one
INSERT INTO auto_reply_rules (id, project_id, name, match_type, keywords, reply, action, enabled, priority)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, name, match_type, keywords, reply, action, enabled, priority, created_at, updated_at
`

type InsertAutoReplyRuleParams struct {
	ID        string
	ProjectID string
	Name      string
	MatchType string
	Keywords  []string
	Reply     *string
	Action    string
	Enabled   bool
	Priority  int32
}

func (q *Queries) InsertAutoReplyRule(ctx context.Context, arg InsertAutoReplyRuleParams) (AutoReplyRule, error) {
	row := q.db.QueryRow(ctx, insertAutoReplyRule,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.MatchType,
		arg.Keywords,
		arg.Reply,
		arg.Action,
		arg.Enabled,
		arg.Priority,
	)
	var i AutoReplyRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.MatchType,
		&i.Keywords,
		&i.Reply,
		&i.Action,
		&i.Enabled,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertForwardingDelivery = `-- name: InsertForwardingDelivery :one
INSERT INTO forwarding_deliveries (id, rule_id, destination_id, project_id, message_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (destination_id, message_id) DO NOTHING
RETURNING id
`

type InsertForwardingDeliveryParams struct {
	ID            string
	RuleID        string
	DestinationID string
	ProjectID     string
	MessageID     string
}

func (q *Queries) InsertForwardingDelivery(ctx context.Context, arg InsertForwardingDeliveryParams) (string, error) {
	row := q.db.QueryRow(ctx, insertForwardingDelivery,
		arg.ID,
		arg.RuleID,
		arg.DestinationID,
		arg.ProjectID,
		arg.MessageID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertForwardingDestination = `-- name: InsertForwardingDestination :one
INSERT INTO forwarding_destinations (id, rule_id, project_id, type, target, format, secret, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, rule_id, project_id, type, target, format, secret, position, created_at
`

type InsertForwardingDestinationParams struct {
	ID        string
	RuleID    string
	ProjectID string
	Type      string
	Target    string
	Format    *string
	Secret    []byte
	Position  int32
}

func (q *Queries) InsertForwardingDestination(ctx context.Context, arg InsertForwardingDestinationParams) (ForwardingDestination, error) {
	row := q.db.QueryRow(ctx, insertForwardingDestination,
		arg.ID,
		arg.RuleID,
		arg.ProjectID,
		arg.Type,
		arg.Target,
		arg.Format,
		arg.Secret,
		arg.Position,
	)
	var i ForwardingDestination
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ProjectID,
		&i.Type,
		&i.Target,
		&i.Format,
		&i.Secret,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const insertForwardingRule = `-- name: InsertForwardingRule :one

INSERT INTO forwarding_rules (id, project_id, name, enabled, senders, contains, signing_secret)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, enabled, senders, contains, signing_secret, created_at, updated_at
`

type InsertForwardingRuleParams struct {
	ID            string
	ProjectID     string
	Name          string
	Enabled       bool
	Senders       []string
	Contains      *string
	SigningSecret string
}

// ---- Forwarding -------------------------------------------------------------
func (q *Queries) InsertForwardingRule(ctx context.Context, arg InsertForwardingRuleParams) (ForwardingRule, error) {
	row := q.db.QueryRow(ctx, insertForwardingRule,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Enabled,
		arg.Senders,
		arg.Contains,
		arg.SigningSecret,
	)
	var i ForwardingRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.Senders,
		&i.Contains,
		&i.SigningSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOptOut = `-- name: InsertOptOut :one
INSERT INTO opt_outs (id, project_id, number, source, keyword)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, number) DO NOTHING
RETURNING id, project_id, number, source, keyword, created_at
`

type InsertOptOutParams struct {
	ID        string
	ProjectID string
	Number    string
	Source    string
	Keyword   *string
}

func (q *Queries) InsertOptOut(ctx context.Context, arg InsertOptOutParams) (OptOut, error) {
	row := q.db.QueryRow(ctx, insertOptOut,
		arg.ID,
		arg.ProjectID,
		arg.Number,
		arg.Source,
		arg.Keyword,
	)
	var i OptOut
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Source,
		&i.Keyword,
		&i.CreatedAt,
	)
	return i, err
}

const isOptedOut = `-- name: IsOptedOut :one

SELECT EXISTS (SELECT 1 FROM opt_outs WHERE project_id = $1 AND number = $2)
`

type IsOptedOutParams struct {
	ProjectID string
	Number    string
}

// ---- Opt-outs ---------------------------------------------------------------
func (q *Queries) IsOptedOut(ctx context.Context, arg IsOptedOutParams) (bool, error) {
	row := q.db.QueryRow(ctx, isOptedOut, arg.ProjectID, arg.Number)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAutoReplyRules = `-- name: ListAutoReplyRules :many
SELECT id, project_id, name, match_type, keywords, reply, action, enabled, priority, created_at, updated_at FROM auto_reply_rules WHERE project_id = $1 ORDER BY priority, created_at, id
`

func (q *Queries) ListAutoReplyRules(ctx context.Context, projectID string) ([]AutoReplyRule, error) {
	rows, err := q.db.Query(ctx, listAutoReplyRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutoReplyRule{}
	for rows.Next() {
		var i AutoReplyRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.MatchType,
			&i.Keywords,
			&i.Reply,
			&i.Action,
			&i.Enabled,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForwardingDeliveries = `-- name: ListForwardingDeliveries :many
SELECT d.id, d.rule_id, d.destination_id, d.project_id, d.message_id, d.status, d.attempts, d.response_status, d.error, d.forwarded_message_id, d.created_at, d.updated_at, fd.type AS destination_type FROM forwarding_deliveries d
JOIN forwarding_destinations fd ON fd.id = d.destination_id
WHERE d.rule_id = $1
ORDER BY d.created_at DESC, d.id DESC
LIMIT $2
`

type ListForwardingDeliveriesParams struct {
	RuleID   string
	RowLimit int32
}

type ListForwardingDeliveriesRow struct {
	ID                 string
	RuleID             string
	DestinationID      string
	ProjectID          string
	MessageID          string
	Status             string
	Attempts           int32
	ResponseStatus     *int32
	Error              *string
	ForwardedMessageID *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DestinationType    string
}

func (q *Queries) ListForwardingDeliveries(ctx context.Context, arg ListForwardingDeliveriesParams) ([]ListForwardingDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listForwardingDeliveries, arg.RuleID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForwardingDeliveriesRow{}
	for rows.Next() {
		var i ListForwardingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.DestinationID,
			&i.ProjectID,
			&i.MessageID,
			&i.Status,
			&i.Attempts,
			&i.ResponseStatus,
			&i.Error,
			&i.ForwardedMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DestinationType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForwardingDestinations = `-- name: ListForwardingDestinations :many
SELECT id, rule_id, project_id, type, target, format, secret, position, created_at FROM forwarding_destinations WHERE rule_id = ANY($1::text[]) ORDER BY rule_id, position, id
`

func (q *Queries) ListForwardingDestinations(ctx context.Context, ruleIds []string) ([]ForwardingDestination, error) {
	rows, err := q.db.Query(ctx, listForwardingDestinations, ruleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForwardingDestination{}
	for rows.Next() {
		var i ForwardingDestination
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.ProjectID,
			&i.Type,
			&i.Target,
			&i.Format,
			&i.Secret,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForwardingRules = `-- name: ListForwardingRules :many
SELECT id, project_id, name, enabled, senders, contains, signing_secret, created_at, updated_at FROM forwarding_rules WHERE project_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListForwardingRules(ctx context.Context, projectID string) ([]ForwardingRule, error) {
	rows, err := q.db.Query(ctx, listForwardingRules, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ForwardingRule{}
	for rows.Next() {
		var i ForwardingRule
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Enabled,
			&i.Senders,
			&i.Contains,
			&i.SigningSecret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptOuts = `-- name: ListOptOuts :many
SELECT id, project_id, number, source, keyword, created_at FROM opt_outs
WHERE project_id = $1
  AND ($2::text IS NULL OR source = $2)
  AND ($3::timestamptz IS NULL
       OR (created_at, id) < ($3::timestamptz, $4::text))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListOptOutsParams struct {
	ProjectID     string
	Source        *string
	BeforeCreated *time.Time
	BeforeID      *string
	RowLimit      int32
}

func (q *Queries) ListOptOuts(ctx context.Context, arg ListOptOutsParams) ([]OptOut, error) {
	rows, err := q.db.Query(ctx, listOptOuts,
		arg.ProjectID,
		arg.Source,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptOut{}
	for rows.Next() {
		var i OptOut
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Source,
			&i.Keyword,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const optedOutAmong = `-- name: OptedOutAmong :many
SELECT number FROM opt_outs WHERE project_id = $1 AND number = ANY($2::text[])
`

type OptedOutAmongParams struct {
	ProjectID string
	Numbers   []string
}

func (q *Queries) OptedOutAmong(ctx context.Context, arg OptedOutAmongParams) ([]string, error) {
	rows, err := q.db.Query(ctx, optedOutAmong, arg.ProjectID, arg.Numbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var number string
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentAutoReply = `-- name: RecentAutoReply :one
SELECT EXISTS (
    SELECT 1 FROM messages
    WHERE project_id = $1 AND recipient = $2 AND direction = 'outbound'
      AND created_at > $3 AND metadata ->> 'auto_reply_rule_id' = $4::text
)
`

type RecentAutoReplyParams struct {
	ProjectID string
	Recipient string
	Since     time.Time
	RuleID    string
}

// Whether a rule already replied to a number since a time (loop protection).
func (q *Queries) RecentAutoReply(ctx context.Context, arg RecentAutoReplyParams) (bool, error) {
	row := q.db.QueryRow(ctx, recentAutoReply,
		arg.ProjectID,
		arg.Recipient,
		arg.Since,
		arg.RuleID,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recentForwardWithBody = `-- name: RecentForwardWithBody :one
SELECT EXISTS (
    SELECT 1 FROM messages
    WHERE project_id = $1 AND direction = 'outbound' AND body_sha256 = $2
      AND created_at > $3 AND metadata ? 'forwarded_from'
)
`

type RecentForwardWithBodyParams struct {
	ProjectID  string
	BodySha256 []byte
	Since      time.Time
}

// Whether Bridge forwarded a message with this exact text recently: an incoming
// SMS that matches is one of its own forwards arriving back.
func (q *Queries) RecentForwardWithBody(ctx context.Context, arg RecentForwardWithBodyParams) (bool, error) {
	row := q.db.QueryRow(ctx, recentForwardWithBody, arg.ProjectID, arg.BodySha256, arg.Since)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const recordForwardingAttempt = `-- name: RecordForwardingAttempt :exec
UPDATE forwarding_deliveries SET
    status = $1, attempts = $2, response_status = $3, error = $4,
    forwarded_message_id = COALESCE($5::text, forwarded_message_id), updated_at = now()
WHERE id = $6
`

type RecordForwardingAttemptParams struct {
	Status             string
	Attempts           int32
	ResponseStatus     *int32
	Error              *string
	ForwardedMessageID *string
	ID                 string
}

func (q *Queries) RecordForwardingAttempt(ctx context.Context, arg RecordForwardingAttemptParams) error {
	_, err := q.db.Exec(ctx, recordForwardingAttempt,
		arg.Status,
		arg.Attempts,
		arg.ResponseStatus,
		arg.Error,
		arg.ForwardedMessageID,
		arg.ID,
	)
	return err
}

const updateAutoReplyRule = `-- name: UpdateAutoReplyRule :one
UPDATE auto_reply_rules SET
    name = $1, match_type = $2, keywords = $3, reply = $4,
    action = $5, enabled = $6, priority = $7, updated_at = now()
WHERE id = $8 AND project_id = $9
RETURNING id, project_id, name, match_type, keywords, reply, action, enabled, priority, created_at, updated_at
`

type UpdateAutoReplyRuleParams struct {
	Name      string
	MatchType string
	Keywords  []string
	Reply     *string
	Action    string
	Enabled   bool
	Priority  int32
	ID        string
	ProjectID string
}

func (q *Queries) UpdateAutoReplyRule(ctx context.Context, arg UpdateAutoReplyRuleParams) (AutoReplyRule, error) {
	row := q.db.QueryRow(ctx, updateAutoReplyRule,
		arg.Name,
		arg.MatchType,
		arg.Keywords,
		arg.Reply,
		arg.Action,
		arg.Enabled,
		arg.Priority,
		arg.ID,
		arg.ProjectID,
	)
	var i AutoReplyRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.MatchType,
		&i.Keywords,
		&i.Reply,
		&i.Action,
		&i.Enabled,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateForwardingDestination = `-- name: UpdateForwardingDestination :one
UPDATE forwarding_destinations SET
    type = $1, target = $2, format = $3, secret = $4, position = $5
WHERE id = $6 AND rule_id = $7
RETURNING id, rule_id, project_id, type, target, format, secret, position, created_at
`

type UpdateForwardingDestinationParams struct {
	Type     string
	Target   string
	Format   *string
	Secret   []byte
	Position int32
	ID       string
	RuleID   string
}

func (q *Queries) UpdateForwardingDestination(ctx context.Context, arg UpdateForwardingDestinationParams) (ForwardingDestination, error) {
	row := q.db.QueryRow(ctx, updateForwardingDestination,
		arg.Type,
		arg.Target,
		arg.Format,
		arg.Secret,
		arg.Position,
		arg.ID,
		arg.RuleID,
	)
	var i ForwardingDestination
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.ProjectID,
		&i.Type,
		&i.Target,
		&i.Format,
		&i.Secret,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateForwardingRule = `-- name: UpdateForwardingRule :one
UPDATE forwarding_rules SET
    name = $1, enabled = $2, senders = $3, contains = $4, updated_at = now()
WHERE id = $5 AND project_id = $6
RETURNING id, project_id, name, enabled, senders, contains, signing_secret, created_at, updated_at
`

type UpdateForwardingRuleParams struct {
	Name      string
	Enabled   bool
	Senders   []string
	Contains  *string
	ID        string
	ProjectID string
}

func (q *Queries) UpdateForwardingRule(ctx context.Context, arg UpdateForwardingRuleParams) (ForwardingRule, error) {
	row := q.db.QueryRow(ctx, updateForwardingRule,
		arg.Name,
		arg.Enabled,
		arg.Senders,
		arg.Contains,
		arg.ID,
		arg.ProjectID,
	)
	var i ForwardingRule
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Enabled,
		&i.Senders,
		&i.Contains,
		&i.SigningSecret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
