// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package dbq

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimBillingWebhookEvent = `-- name: ClaimBillingWebhookEvent :one
INSERT INTO billing_webhook_events (id, type) VALUES ($1, $2)
ON CONFLICT (id) DO NOTHING
RETURNING id
`

type ClaimBillingWebhookEventParams struct {
	ID   string
	Type string
}

func (q *Queries) ClaimBillingWebhookEvent(ctx context.Context, arg ClaimBillingWebhookEventParams) (string, error) {
	row := q.db.QueryRow(ctx, claimBillingWebhookEvent, arg.ID, arg.Type)
	var id string
	err := row.Scan(&id)
	return id, err
}

const countOrganizationMembers = `-- name: CountOrganizationMembers :one
SELECT count(*) FROM organization_members WHERE organization_id = $1
`

func (q *Queries) CountOrganizationMembers(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationMembers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationPhones = `-- name: CountOrganizationPhones :one
SELECT count(*) FROM devices d
JOIN projects p ON p.id = d.project_id
WHERE p.organization_id = $1 AND d.revoked_at IS NULL
`

func (q *Queries) CountOrganizationPhones(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationPhones, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationProjects = `-- name: CountOrganizationProjects :one
SELECT count(*) FROM projects WHERE organization_id = $1
`

func (q *Queries) CountOrganizationProjects(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationProjects, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationSeats = `-- name: CountOrganizationSeats :one
SELECT (
    (SELECT count(*) FROM organization_members m WHERE m.organization_id = $1) +
    (SELECT count(*) FROM organization_invites i
      WHERE i.organization_id = $1 AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > now())
)::bigint AS seats
`

// Members plus invitations that are still open, so invites cannot exceed the plan.
func (q *Queries) CountOrganizationSeats(ctx context.Context, organizationID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationSeats, organizationID)
	var seats int64
	err := row.Scan(&seats)
	return seats, err
}

const getLiveUsage = `-- name: GetLiveUsage :one
SELECT COALESCE((
    SELECT live_messages FROM organization_usage WHERE organization_id = $1 AND period = $2
), 0)::integer AS live_messages
`

type GetLiveUsageParams struct {
	OrganizationID string
	Period         pgtype.Date
}

func (q *Queries) GetLiveUsage(ctx context.Context, arg GetLiveUsageParams) (int32, error) {
	row := q.db.QueryRow(ctx, getLiveUsage, arg.OrganizationID, arg.Period)
	var live_messages int32
	err := row.Scan(&live_messages)
	return live_messages, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, price_cents, currency, max_phones, max_live_messages, max_projects, max_members, sort_order, created_at, updated_at FROM plans WHERE id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.Currency,
		&i.MaxPhones,
		&i.MaxLiveMessages,
		&i.MaxProjects,
		&i.MaxMembers,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT organization_id, plan_id, status, provider_customer_id, provider_subscription_id, current_period_end, cancel_at_period_end, created_at, updated_at FROM subscriptions WHERE organization_id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, organizationID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, organizationID)
	var i Subscription
	err := row.Scan(
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByCustomer = `-- name: GetSubscriptionByCustomer :one
SELECT organization_id, plan_id, status, provider_customer_id, provider_subscription_id, current_period_end, cancel_at_period_end, created_at, updated_at FROM subscriptions WHERE provider_customer_id = $1 ORDER BY updated_at DESC LIMIT 1
`

func (q *Queries) GetSubscriptionByCustomer(ctx context.Context, providerCustomerID *string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByCustomer, providerCustomerID)
	var i Subscription
	err := row.Scan(
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByProviderID = `-- name: GetSubscriptionByProviderID :one
SELECT organization_id, plan_id, status, provider_customer_id, provider_subscription_id, current_period_end, cancel_at_period_end, created_at, updated_at FROM subscriptions WHERE provider_subscription_id = $1
`

func (q *Queries) GetSubscriptionByProviderID(ctx context.Context, providerSubscriptionID *string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByProviderID, providerSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionForUpdate = `-- name: GetSubscriptionForUpdate :one
SELECT organization_id, plan_id, status, provider_customer_id, provider_subscription_id, current_period_end, cancel_at_period_end, created_at, updated_at FROM subscriptions WHERE organization_id = $1 FOR UPDATE
`

// Locks the workspace's subscription row while a webhook decides what to store.
func (q *Queries) GetSubscriptionForUpdate(ctx context.Context, organizationID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionForUpdate, organizationID)
	var i Subscription
	err := row.Scan(
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementLiveUsage = `-- name: IncrementLiveUsage :one
INSERT INTO organization_usage AS u (organization_id, period, live_messages)
SELECT $1::text, $2::date, 1
WHERE $3::integer > 0
ON CONFLICT (organization_id, period) DO UPDATE SET live_messages = u.live_messages + 1
WHERE u.live_messages < $3::integer
RETURNING live_messages
`

type IncrementLiveUsageParams struct {
	OrganizationID string
	Period         pgtype.Date
	MaxMessages    int32
}

// Counts one live message, unless the organization already reached max_messages.
// No row returned means the limit was reached.
func (q *Queries) IncrementLiveUsage(ctx context.Context, arg IncrementLiveUsageParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementLiveUsage, arg.OrganizationID, arg.Period, arg.MaxMessages)
	var live_messages int32
	err := row.Scan(&live_messages)
	return live_messages, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, price_cents, currency, max_phones, max_live_messages, max_projects, max_members, sort_order, created_at, updated_at FROM plans ORDER BY sort_order, id
`

func (q *Queries) ListPlans(ctx context.Context) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceCents,
			&i.Currency,
			&i.MaxPhones,
			&i.MaxLiveMessages,
			&i.MaxProjects,
			&i.MaxMembers,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationExists = `-- name: OrganizationExists :one
SELECT EXISTS (SELECT 1 FROM organizations WHERE id = $1)
`

func (q *Queries) OrganizationExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, organizationExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (
    organization_id, plan_id, status, provider_customer_id, provider_subscription_id,
    current_period_end, cancel_at_period_end
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (organization_id) DO UPDATE SET
    plan_id = EXCLUDED.plan_id,
    status = EXCLUDED.status,
    provider_customer_id = COALESCE(EXCLUDED.provider_customer_id, subscriptions.provider_customer_id),
    provider_subscription_id = EXCLUDED.provider_subscription_id,
    current_period_end = EXCLUDED.current_period_end,
    cancel_at_period_end = EXCLUDED.cancel_at_period_end,
    updated_at = now()
RETURNING organization_id, plan_id, status, provider_customer_id, provider_subscription_id, current_period_end, cancel_at_period_end, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	OrganizationID         string
	PlanID                 string
	Status                 string
	ProviderCustomerID     *string
	ProviderSubscriptionID *string
	CurrentPeriodEnd       *time.Time
	CancelAtPeriodEnd      bool
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.OrganizationID,
		arg.PlanID,
		arg.Status,
		arg.ProviderCustomerID,
		arg.ProviderSubscriptionID,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.OrganizationID,
		&i.PlanID,
		&i.Status,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
