// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broadcasts.sql

package dbq

import (
	"context"
	"time"
)

const broadcastCounts = `-- name: BroadcastCounts :many
SELECT r.broadcast_id,
       count(*) FILTER (WHERE r.status = 'pending')::int                                        AS waiting,
       count(*) FILTER (WHERE m.status IN ('created', 'queued', 'sending'))::int                AS in_flight,
       count(*) FILTER (WHERE m.status = 'sent')::int                                           AS sent,
       count(*) FILTER (WHERE m.status = 'delivered')::int                                      AS delivered,
       count(*) FILTER (WHERE m.status = 'failed' AND m.error_code IS DISTINCT FROM 'canceled')::int AS failed,
       count(*) FILTER (WHERE r.status = 'canceled' OR (m.status = 'failed' AND m.error_code = 'canceled'))::int AS canceled,
       count(*) FILTER (WHERE r.status = 'skipped')::int                                        AS skipped
FROM broadcast_recipients r
LEFT JOIN messages m ON m.id = r.message_id
WHERE r.broadcast_id = ANY($1::text[])
GROUP BY r.broadcast_id
`

type BroadcastCountsRow struct {
	BroadcastID string
	Waiting     int32
	InFlight    int32
	Sent        int32
	Delivered   int32
	Failed      int32
	Canceled    int32
	Skipped     int32
}

// Progress of broadcasts, from their recipients and the messages created for them.
func (q *Queries) BroadcastCounts(ctx context.Context, ids []string) ([]BroadcastCountsRow, error) {
	rows, err := q.db.Query(ctx, broadcastCounts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BroadcastCountsRow{}
	for rows.Next() {
		var i BroadcastCountsRow
		if err := rows.Scan(
			&i.BroadcastID,
			&i.Waiting,
			&i.InFlight,
			&i.Sent,
			&i.Delivered,
			&i.Failed,
			&i.Canceled,
			&i.Skipped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const broadcastInFlight = `-- name: BroadcastInFlight :one
SELECT count(*)::int FROM broadcast_recipients r
JOIN messages m ON m.id = r.message_id
WHERE r.broadcast_id = $1 AND m.status IN ('created', 'queued', 'sending')
`

// Messages of a broadcast that no phone or provider has finished with yet.
func (q *Queries) BroadcastInFlight(ctx context.Context, broadcastID string) (int32, error) {
	row := q.db.QueryRow(ctx, broadcastInFlight, broadcastID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const cancelBroadcast = `-- name: CancelBroadcast :one
UPDATE broadcasts SET status = 'canceled', canceled_at = now(), updated_at = now()
WHERE id = $1 AND project_id = $2 AND status IN ('scheduled', 'sending')
RETURNING id, project_id, environment, name, template, device_id, status, scheduled_at, total_recipients, skipped_opted_out, duplicates, total_segments, api_key_id, created_by, started_at, completed_at, canceled_at, created_at, updated_at
`

type CancelBroadcastParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) CancelBroadcast(ctx context.Context, arg CancelBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, cancelBroadcast, arg.ID, arg.ProjectID)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Name,
		&i.Template,
		&i.DeviceID,
		&i.Status,
		&i.ScheduledAt,
		&i.TotalRecipients,
		&i.SkippedOptedOut,
		&i.Duplicates,
		&i.TotalSegments,
		&i.APIKeyID,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelPendingRecipients = `-- name: CancelPendingRecipients :execrows
UPDATE broadcast_recipients SET status = 'canceled', vars = NULL
WHERE broadcast_id = $1 AND status = 'pending'
`

func (q *Queries) CancelPendingRecipients(ctx context.Context, broadcastID string) (int64, error) {
	result, err := q.db.Exec(ctx, cancelPendingRecipients, broadcastID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeBroadcast = `-- name: CompleteBroadcast :one
UPDATE broadcasts SET status = 'completed', completed_at = now(), updated_at = now()
WHERE id = $1 AND status = 'sending'
RETURNING id, project_id, environment, name, template, device_id, status, scheduled_at, total_recipients, skipped_opted_out, duplicates, total_segments, api_key_id, created_by, started_at, completed_at, canceled_at, created_at, updated_at
`

func (q *Queries) CompleteBroadcast(ctx context.Context, id string) (Broadcast, error) {
	row := q.db.QueryRow(ctx, completeBroadcast, id)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Name,
		&i.Template,
		&i.DeviceID,
		&i.Status,
		&i.ScheduledAt,
		&i.TotalRecipients,
		&i.SkippedOptedOut,
		&i.Duplicates,
		&i.TotalSegments,
		&i.APIKeyID,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBroadcast = `-- name: GetBroadcast :one
SELECT id, project_id, environment, name, template, device_id, status, scheduled_at, total_recipients, skipped_opted_out, duplicates, total_segments, api_key_id, created_by, started_at, completed_at, canceled_at, created_at, updated_at FROM broadcasts WHERE id = $1 AND project_id = $2
`

type GetBroadcastParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetBroadcast(ctx context.Context, arg GetBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, getBroadcast, arg.ID, arg.ProjectID)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Name,
		&i.Template,
		&i.DeviceID,
		&i.Status,
		&i.ScheduledAt,
		&i.TotalRecipients,
		&i.SkippedOptedOut,
		&i.Duplicates,
		&i.TotalSegments,
		&i.APIKeyID,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBroadcastByID = `-- name: GetBroadcastByID :one
SELECT id, project_id, environment, name, template, device_id, status, scheduled_at, total_recipients, skipped_opted_out, duplicates, total_segments, api_key_id, created_by, started_at, completed_at, canceled_at, created_at, updated_at FROM broadcasts WHERE id = $1
`

func (q *Queries) GetBroadcastByID(ctx context.Context, id string) (Broadcast, error) {
	row := q.db.QueryRow(ctx, getBroadcastByID, id)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Name,
		&i.Template,
		&i.DeviceID,
		&i.Status,
		&i.ScheduledAt,
		&i.TotalRecipients,
		&i.SkippedOptedOut,
		&i.Duplicates,
		&i.TotalSegments,
		&i.APIKeyID,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBroadcast = `-- name: InsertBroadcast :one
INSERT INTO broadcasts (
    id, project_id, environment, name, template, device_id, status, scheduled_at,
    total_recipients, skipped_opted_out, duplicates, total_segments, api_key_id, created_by, started_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14,
    CASE WHEN $7::text = 'sending' THEN now() END
)
RETURNING id, project_id, environment, name, template, device_id, status, scheduled_at, total_recipients, skipped_opted_out, duplicates, total_segments, api_key_id, created_by, started_at, completed_at, canceled_at, created_at, updated_at
`

type InsertBroadcastParams struct {
	ID              string
	ProjectID       string
	Environment     APIEnvironment
	Name            string
	Template        string
	DeviceID        *string
	Status          string
	ScheduledAt     *time.Time
	TotalRecipients int32
	SkippedOptedOut int32
	Duplicates      int32
	TotalSegments   int32
	APIKeyID        *string
	CreatedBy       *string
}

func (q *Queries) InsertBroadcast(ctx context.Context, arg InsertBroadcastParams) (Broadcast, error) {
	row := q.db.QueryRow(ctx, insertBroadcast,
		arg.ID,
		arg.ProjectID,
		arg.Environment,
		arg.Name,
		arg.Template,
		arg.DeviceID,
		arg.Status,
		arg.ScheduledAt,
		arg.TotalRecipients,
		arg.SkippedOptedOut,
		arg.Duplicates,
		arg.TotalSegments,
		arg.APIKeyID,
		arg.CreatedBy,
	)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Name,
		&i.Template,
		&i.DeviceID,
		&i.Status,
		&i.ScheduledAt,
		&i.TotalRecipients,
		&i.SkippedOptedOut,
		&i.Duplicates,
		&i.TotalSegments,
		&i.APIKeyID,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type InsertBroadcastRecipientsParams struct {
	BroadcastID string
	Position    int32
	Recipient   string
	Vars        []byte
}

const listBroadcasts = `-- name: ListBroadcasts :many
SELECT id, project_id, environment, name, template, device_id, status, scheduled_at, total_recipients, skipped_opted_out, duplicates, total_segments, api_key_id, created_by, started_at, completed_at, canceled_at, created_at, updated_at FROM broadcasts
WHERE project_id = $1 AND environment = $2
  AND ($3::text IS NULL OR status = $3)
  AND ($4::timestamptz IS NULL
       OR (created_at, id) < ($4::timestamptz, $5::text))
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListBroadcastsParams struct {
	ProjectID     string
	Environment   APIEnvironment
	Status        *string
	BeforeCreated *time.Time
	BeforeID      *string
	RowLimit      int32
}

func (q *Queries) ListBroadcasts(ctx context.Context, arg ListBroadcastsParams) ([]Broadcast, error) {
	rows, err := q.db.Query(ctx, listBroadcasts,
		arg.ProjectID,
		arg.Environment,
		arg.Status,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Broadcast{}
	for rows.Next() {
		var i Broadcast
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Environment,
			&i.Name,
			&i.Template,
			&i.DeviceID,
			&i.Status,
			&i.ScheduledAt,
			&i.TotalRecipients,
			&i.SkippedOptedOut,
			&i.Duplicates,
			&i.TotalSegments,
			&i.APIKeyID,
			&i.CreatedBy,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecipientQueued = `-- name: MarkRecipientQueued :execrows
UPDATE broadcast_recipients SET status = 'queued', message_id = $1, vars = NULL
WHERE broadcast_id = $2 AND position = $3 AND status = 'pending'
`

type MarkRecipientQueuedParams struct {
	MessageID   *string
	BroadcastID string
	Position    int32
}

func (q *Queries) MarkRecipientQueued(ctx context.Context, arg MarkRecipientQueuedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRecipientQueued, arg.MessageID, arg.BroadcastID, arg.Position)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRecipientSkipped = `-- name: MarkRecipientSkipped :exec
UPDATE broadcast_recipients SET status = 'skipped', skip_reason = $1, vars = NULL
WHERE broadcast_id = $2 AND position = $3 AND status = 'pending'
`

type MarkRecipientSkippedParams struct {
	SkipReason  *string
	BroadcastID string
	Position    int32
}

func (q *Queries) MarkRecipientSkipped(ctx context.Context, arg MarkRecipientSkippedParams) error {
	_, err := q.db.Exec(ctx, markRecipientSkipped, arg.SkipReason, arg.BroadcastID, arg.Position)
	return err
}

const pendingBroadcastRecipients = `-- name: PendingBroadcastRecipients :many
SELECT broadcast_id, position, recipient, vars, status, skip_reason, message_id FROM broadcast_recipients
WHERE broadcast_id = $1 AND status = 'pending'
ORDER BY position
LIMIT $2
`

type PendingBroadcastRecipientsParams struct {
	BroadcastID string
	RowLimit    int32
}

func (q *Queries) PendingBroadcastRecipients(ctx context.Context, arg PendingBroadcastRecipientsParams) ([]BroadcastRecipient, error) {
	rows, err := q.db.Query(ctx, pendingBroadcastRecipients, arg.BroadcastID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BroadcastRecipient{}
	for rows.Next() {
		var i BroadcastRecipient
		if err := rows.Scan(
			&i.BroadcastID,
			&i.Position,
			&i.Recipient,
			&i.Vars,
			&i.Status,
			&i.SkipReason,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectSendCapacity = `-- name: ProjectSendCapacity :one
SELECT COALESCE(sum(GREATEST(0, LEAST(d.send_limit_count, d.daily_send_limit - (
    SELECT count(*) FROM messages m WHERE m.device_id = d.id AND m.assigned_at > now() - interval '24 hours'
)))), 0)::int
FROM devices d
WHERE d.project_id = $1 AND d.revoked_at IS NULL AND d.status = 'online'
  AND ($2::text IS NULL OR d.id = $2)
`

type ProjectSendCapacityParams struct {
	ProjectID string
	DeviceID  *string
}

// Messages the project's online phones may send per send-limit window, together,
// never more than what is left of each phone's daily cap. Offline phones are left
// out so queued messages do not wait long enough to time out.
func (q *Queries) ProjectSendCapacity(ctx context.Context, arg ProjectSendCapacityParams) (int32, error) {
	row := q.db.QueryRow(ctx, projectSendCapacity, arg.ProjectID, arg.DeviceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const startBroadcast = `-- name: StartBroadcast :one
UPDATE broadcasts SET status = 'sending', started_at = now(), updated_at = now()
WHERE id = $1 AND status = 'scheduled'
RETURNING id, project_id, environment, name, template, device_id, status, scheduled_at, total_recipients, skipped_opted_out, duplicates, total_segments, api_key_id, created_by, started_at, completed_at, canceled_at, created_at, updated_at
`

func (q *Queries) StartBroadcast(ctx context.Context, id string) (Broadcast, error) {
	row := q.db.QueryRow(ctx, startBroadcast, id)
	var i Broadcast
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Name,
		&i.Template,
		&i.DeviceID,
		&i.Status,
		&i.ScheduledAt,
		&i.TotalRecipients,
		&i.SkippedOptedOut,
		&i.Duplicates,
		&i.TotalSegments,
		&i.APIKeyID,
		&i.CreatedBy,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const undispatchedBroadcastMessages = `-- name: UndispatchedBroadcastMessages :many
SELECT m.id, m.project_id, m.environment, m.direction, m.status, m.provider, m.device_id, m.api_key_id, m.recipient, m.sender, m.body, m.segments, m.attempts, m.provider_message_id, m.error_code, m.error_message, m.metadata, m.idempotency_key, m.created_at, m.queued_at, m.sending_at, m.sent_at, m.delivered_at, m.failed_at, m.updated_at, m.requested_device_id, m.sim_slot, m.assigned_at, m.idempotency_hash, m.body_sha256, m.body_length, m.body_redacted_at, m.encoding, m.purpose, m.display_body, m.provider_account_id, m.body_vars FROM broadcast_recipients r
JOIN messages m ON m.id = r.message_id
WHERE r.broadcast_id = $1 AND m.status = 'queued' AND m.device_id IS NULL
  AND m.provider IN ('android', 'simulator')
`

// Messages of a broadcast still waiting in the queue, not yet with a phone or provider.
func (q *Queries) UndispatchedBroadcastMessages(ctx context.Context, broadcastID string) ([]Message, error) {
	rows, err := q.db.Query(ctx, undispatchedBroadcastMessages, broadcastID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Environment,
			&i.Direction,
			&i.Status,
			&i.Provider,
			&i.DeviceID,
			&i.APIKeyID,
			&i.Recipient,
			&i.Sender,
			&i.Body,
			&i.Segments,
			&i.Attempts,
			&i.ProviderMessageID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.QueuedAt,
			&i.SendingAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.UpdatedAt,
			&i.RequestedDeviceID,
			&i.SimSlot,
			&i.AssignedAt,
			&i.IdempotencyHash,
			&i.BodySha256,
			&i.BodyLength,
			&i.BodyRedactedAt,
			&i.Encoding,
			&i.Purpose,
			&i.DisplayBody,
			&i.ProviderAccountID,
			&i.BodyVars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
