// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package dbq

import (
	"context"
)

// iteratorForInsertBroadcastRecipients implements pgx.CopyFromSource.
type iteratorForInsertBroadcastRecipients struct {
	rows                 []InsertBroadcastRecipientsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertBroadcastRecipients) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertBroadcastRecipients) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BroadcastID,
		r.rows[0].Position,
		r.rows[0].Recipient,
		r.rows[0].Vars,
	}, nil
}

func (r iteratorForInsertBroadcastRecipients) Err() error {
	return nil
}

func (q *Queries) InsertBroadcastRecipients(ctx context.Context, arg []InsertBroadcastRecipientsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"broadcast_recipients"}, []string{"broadcast_id", "position", "recipient", "vars"}, &iteratorForInsertBroadcastRecipients{rows: arg})
}
