// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package dbq

import (
	"context"
	"time"
)

const claimPairingToken = `-- name: ClaimPairingToken :one
SELECT id, project_id, token_hash, created_by, device_id, expires_at, used_at, created_at FROM device_pairing_tokens
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
FOR UPDATE
`

// Locks a valid, unused token for the pairing transaction.
func (q *Queries) ClaimPairingToken(ctx context.Context, tokenHash []byte) (DevicePairingToken, error) {
	row := q.db.QueryRow(ctx, claimPairingToken, tokenHash)
	var i DevicePairingToken
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.DeviceID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (id, project_id, name, installation_id, credential_hash, device_model, android_version, app_version, app_flavor)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, name, installation_id, credential_hash, status, last_heartbeat_at, last_seen_at, battery_level, is_charging, network_type, carrier_name, sim_count, device_model, android_version, app_version, created_at, updated_at, revoked_at, push_provider, push_endpoint, push_p256dh, push_auth, push_updated_at, connection_id, connected_at, heartbeat_interval, app_flavor, preferred_sim_slot, send_limit_count, send_limit_window_seconds, sims, forward_inbound, notified_presence, daily_send_limit
`

type CreateDeviceParams struct {
	ID             string
	ProjectID      string
	Name           string
	InstallationID string
	CredentialHash []byte
	DeviceModel    *string
	AndroidVersion *string
	AppVersion     *string
	AppFlavor      *string
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.InstallationID,
		arg.CredentialHash,
		arg.DeviceModel,
		arg.AndroidVersion,
		arg.AppVersion,
		arg.AppFlavor,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.InstallationID,
		&i.CredentialHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSeenAt,
		&i.BatteryLevel,
		&i.IsCharging,
		&i.NetworkType,
		&i.CarrierName,
		&i.SimCount,
		&i.DeviceModel,
		&i.AndroidVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.PushProvider,
		&i.PushEndpoint,
		&i.PushP256dh,
		&i.PushAuth,
		&i.PushUpdatedAt,
		&i.ConnectionID,
		&i.ConnectedAt,
		&i.HeartbeatInterval,
		&i.AppFlavor,
		&i.PreferredSimSlot,
		&i.SendLimitCount,
		&i.SendLimitWindowSeconds,
		&i.Sims,
		&i.ForwardInbound,
		&i.NotifiedPresence,
		&i.DailySendLimit,
	)
	return i, err
}

const createPairingToken = `-- name: CreatePairingToken :one
INSERT INTO device_pairing_tokens (id, project_id, token_hash, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, token_hash, created_by, device_id, expires_at, used_at, created_at
`

type CreatePairingTokenParams struct {
	ID        string
	ProjectID string
	TokenHash []byte
	CreatedBy *string
	ExpiresAt time.Time
}

func (q *Queries) CreatePairingToken(ctx context.Context, arg CreatePairingTokenParams) (DevicePairingToken, error) {
	row := q.db.QueryRow(ctx, createPairingToken,
		arg.ID,
		arg.ProjectID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i DevicePairingToken
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.DeviceID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDevice = `-- name: GetDevice :one
SELECT id, project_id, name, installation_id, credential_hash, status, last_heartbeat_at, last_seen_at, battery_level, is_charging, network_type, carrier_name, sim_count, device_model, android_version, app_version, created_at, updated_at, revoked_at, push_provider, push_endpoint, push_p256dh, push_auth, push_updated_at, connection_id, connected_at, heartbeat_interval, app_flavor, preferred_sim_slot, send_limit_count, send_limit_window_seconds, sims, forward_inbound, notified_presence, daily_send_limit FROM devices WHERE id = $1 AND project_id = $2
`

type GetDeviceParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetDevice(ctx context.Context, arg GetDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDevice, arg.ID, arg.ProjectID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.InstallationID,
		&i.CredentialHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSeenAt,
		&i.BatteryLevel,
		&i.IsCharging,
		&i.NetworkType,
		&i.CarrierName,
		&i.SimCount,
		&i.DeviceModel,
		&i.AndroidVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.PushProvider,
		&i.PushEndpoint,
		&i.PushP256dh,
		&i.PushAuth,
		&i.PushUpdatedAt,
		&i.ConnectionID,
		&i.ConnectedAt,
		&i.HeartbeatInterval,
		&i.AppFlavor,
		&i.PreferredSimSlot,
		&i.SendLimitCount,
		&i.SendLimitWindowSeconds,
		&i.Sims,
		&i.ForwardInbound,
		&i.NotifiedPresence,
		&i.DailySendLimit,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, project_id, name, installation_id, credential_hash, status, last_heartbeat_at, last_seen_at, battery_level, is_charging, network_type, carrier_name, sim_count, device_model, android_version, app_version, created_at, updated_at, revoked_at, push_provider, push_endpoint, push_p256dh, push_auth, push_updated_at, connection_id, connected_at, heartbeat_interval, app_flavor, preferred_sim_slot, send_limit_count, send_limit_window_seconds, sims, forward_inbound, notified_presence, daily_send_limit FROM devices WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.InstallationID,
		&i.CredentialHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSeenAt,
		&i.BatteryLevel,
		&i.IsCharging,
		&i.NetworkType,
		&i.CarrierName,
		&i.SimCount,
		&i.DeviceModel,
		&i.AndroidVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.PushProvider,
		&i.PushEndpoint,
		&i.PushP256dh,
		&i.PushAuth,
		&i.PushUpdatedAt,
		&i.ConnectionID,
		&i.ConnectedAt,
		&i.HeartbeatInterval,
		&i.AppFlavor,
		&i.PreferredSimSlot,
		&i.SendLimitCount,
		&i.SendLimitWindowSeconds,
		&i.Sims,
		&i.ForwardInbound,
		&i.NotifiedPresence,
		&i.DailySendLimit,
	)
	return i, err
}

const getDeviceByInstallation = `-- name: GetDeviceByInstallation :one
SELECT id, project_id, name, installation_id, credential_hash, status, last_heartbeat_at, last_seen_at, battery_level, is_charging, network_type, carrier_name, sim_count, device_model, android_version, app_version, created_at, updated_at, revoked_at, push_provider, push_endpoint, push_p256dh, push_auth, push_updated_at, connection_id, connected_at, heartbeat_interval, app_flavor, preferred_sim_slot, send_limit_count, send_limit_window_seconds, sims, forward_inbound, notified_presence, daily_send_limit FROM devices WHERE project_id = $1 AND installation_id = $2
`

type GetDeviceByInstallationParams struct {
	ProjectID      string
	InstallationID string
}

func (q *Queries) GetDeviceByInstallation(ctx context.Context, arg GetDeviceByInstallationParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByInstallation, arg.ProjectID, arg.InstallationID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.InstallationID,
		&i.CredentialHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSeenAt,
		&i.BatteryLevel,
		&i.IsCharging,
		&i.NetworkType,
		&i.CarrierName,
		&i.SimCount,
		&i.DeviceModel,
		&i.AndroidVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.PushProvider,
		&i.PushEndpoint,
		&i.PushP256dh,
		&i.PushAuth,
		&i.PushUpdatedAt,
		&i.ConnectionID,
		&i.ConnectedAt,
		&i.HeartbeatInterval,
		&i.AppFlavor,
		&i.PreferredSimSlot,
		&i.SendLimitCount,
		&i.SendLimitWindowSeconds,
		&i.Sims,
		&i.ForwardInbound,
		&i.NotifiedPresence,
		&i.DailySendLimit,
	)
	return i, err
}

const getDeviceForAuth = `-- name: GetDeviceForAuth :one
SELECT devices.id, devices.project_id, devices.name, devices.installation_id, devices.credential_hash, devices.status, devices.last_heartbeat_at, devices.last_seen_at, devices.battery_level, devices.is_charging, devices.network_type, devices.carrier_name, devices.sim_count, devices.device_model, devices.android_version, devices.app_version, devices.created_at, devices.updated_at, devices.revoked_at, devices.push_provider, devices.push_endpoint, devices.push_p256dh, devices.push_auth, devices.push_updated_at, devices.connection_id, devices.connected_at, devices.heartbeat_interval, devices.app_flavor, devices.preferred_sim_slot, devices.send_limit_count, devices.send_limit_window_seconds, devices.sims, devices.forward_inbound, devices.notified_presence, devices.daily_send_limit, projects.organization_id, projects.name AS project_name
FROM devices
JOIN projects ON projects.id = devices.project_id
WHERE devices.credential_hash = $1
`

type GetDeviceForAuthRow struct {
	Device         Device
	OrganizationID string
	ProjectName    string
}

func (q *Queries) GetDeviceForAuth(ctx context.Context, credentialHash []byte) (GetDeviceForAuthRow, error) {
	row := q.db.QueryRow(ctx, getDeviceForAuth, credentialHash)
	var i GetDeviceForAuthRow
	err := row.Scan(
		&i.Device.ID,
		&i.Device.ProjectID,
		&i.Device.Name,
		&i.Device.InstallationID,
		&i.Device.CredentialHash,
		&i.Device.Status,
		&i.Device.LastHeartbeatAt,
		&i.Device.LastSeenAt,
		&i.Device.BatteryLevel,
		&i.Device.IsCharging,
		&i.Device.NetworkType,
		&i.Device.CarrierName,
		&i.Device.SimCount,
		&i.Device.DeviceModel,
		&i.Device.AndroidVersion,
		&i.Device.AppVersion,
		&i.Device.CreatedAt,
		&i.Device.UpdatedAt,
		&i.Device.RevokedAt,
		&i.Device.PushProvider,
		&i.Device.PushEndpoint,
		&i.Device.PushP256dh,
		&i.Device.PushAuth,
		&i.Device.PushUpdatedAt,
		&i.Device.ConnectionID,
		&i.Device.ConnectedAt,
		&i.Device.HeartbeatInterval,
		&i.Device.AppFlavor,
		&i.Device.PreferredSimSlot,
		&i.Device.SendLimitCount,
		&i.Device.SendLimitWindowSeconds,
		&i.Device.Sims,
		&i.Device.ForwardInbound,
		&i.Device.NotifiedPresence,
		&i.Device.DailySendLimit,
		&i.OrganizationID,
		&i.ProjectName,
	)
	return i, err
}

const getServerKey = `-- name: GetServerKey :one
SELECT private_key FROM server_keys WHERE name = $1
`

func (q *Queries) GetServerKey(ctx context.Context, name string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getServerKey, name)
	var private_key []byte
	err := row.Scan(&private_key)
	return private_key, err
}

const insertServerKey = `-- name: InsertServerKey :exec
INSERT INTO server_keys (name, private_key) VALUES ($1, $2) ON CONFLICT (name) DO NOTHING
`

type InsertServerKeyParams struct {
	Name       string
	PrivateKey []byte
}

func (q *Queries) InsertServerKey(ctx context.Context, arg InsertServerKeyParams) error {
	_, err := q.db.Exec(ctx, insertServerKey, arg.Name, arg.PrivateKey)
	return err
}

const listDevices = `-- name: ListDevices :many
SELECT id, project_id, name, installation_id, credential_hash, status, last_heartbeat_at, last_seen_at, battery_level, is_charging, network_type, carrier_name, sim_count, device_model, android_version, app_version, created_at, updated_at, revoked_at, push_provider, push_endpoint, push_p256dh, push_auth, push_updated_at, connection_id, connected_at, heartbeat_interval, app_flavor, preferred_sim_slot, send_limit_count, send_limit_window_seconds, sims, forward_inbound, notified_presence, daily_send_limit FROM devices
WHERE project_id = $1
ORDER BY (revoked_at IS NOT NULL), created_at DESC, id DESC
`

func (q *Queries) ListDevices(ctx context.Context, projectID string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.InstallationID,
			&i.CredentialHash,
			&i.Status,
			&i.LastHeartbeatAt,
			&i.LastSeenAt,
			&i.BatteryLevel,
			&i.IsCharging,
			&i.NetworkType,
			&i.CarrierName,
			&i.SimCount,
			&i.DeviceModel,
			&i.AndroidVersion,
			&i.AppVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.PushProvider,
			&i.PushEndpoint,
			&i.PushP256dh,
			&i.PushAuth,
			&i.PushUpdatedAt,
			&i.ConnectionID,
			&i.ConnectedAt,
			&i.HeartbeatInterval,
			&i.AppFlavor,
			&i.PreferredSimSlot,
			&i.SendLimitCount,
			&i.SendLimitWindowSeconds,
			&i.Sims,
			&i.ForwardInbound,
			&i.NotifiedPresence,
			&i.DailySendLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeviceConnected = `-- name: MarkDeviceConnected :exec
UPDATE devices SET
    status = 'online', connection_id = $1, connected_at = now(), last_seen_at = now(), updated_at = now()
WHERE id = $2 AND revoked_at IS NULL
`

type MarkDeviceConnectedParams struct {
	ConnectionID *string
	ID           string
}

func (q *Queries) MarkDeviceConnected(ctx context.Context, arg MarkDeviceConnectedParams) error {
	_, err := q.db.Exec(ctx, markDeviceConnected, arg.ConnectionID, arg.ID)
	return err
}

const markDeviceDisconnected = `-- name: MarkDeviceDisconnected :execrows
UPDATE devices SET status = 'offline', connection_id = NULL, last_seen_at = now(), updated_at = now()
WHERE id = $1 AND connection_id = $2
`

type MarkDeviceDisconnectedParams struct {
	ID           string
	ConnectionID *string
}

// Only the connection that currently owns the device may mark it offline.
func (q *Queries) MarkDeviceDisconnected(ctx context.Context, arg MarkDeviceDisconnectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDeviceDisconnected, arg.ID, arg.ConnectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPairingTokenUsed = `-- name: MarkPairingTokenUsed :exec
UPDATE device_pairing_tokens SET used_at = now(), device_id = $1 WHERE id = $2
`

type MarkPairingTokenUsedParams struct {
	DeviceID *string
	ID       string
}

func (q *Queries) MarkPairingTokenUsed(ctx context.Context, arg MarkPairingTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markPairingTokenUsed, arg.DeviceID, arg.ID)
	return err
}

const recordHeartbeat = `-- name: RecordHeartbeat :exec
UPDATE devices SET
    last_heartbeat_at = now(),
    last_seen_at = now(),
    heartbeat_interval = $1,
    battery_level = $2,
    is_charging = $3,
    network_type = $4,
    carrier_name = $5,
    sim_count = $6,
    device_model = COALESCE($7, device_model),
    android_version = COALESCE($8, android_version),
    app_version = COALESCE($9, app_version),
    sims = COALESCE($10::jsonb, sims),
    updated_at = now()
WHERE id = $11 AND revoked_at IS NULL
`

type RecordHeartbeatParams struct {
	HeartbeatInterval int32
	BatteryLevel      *int16
	IsCharging        *bool
	NetworkType       *string
	CarrierName       *string
	SimCount          *int16
	DeviceModel       *string
	AndroidVersion    *string
	AppVersion        *string
	Sims              []byte
	ID                string
}

func (q *Queries) RecordHeartbeat(ctx context.Context, arg RecordHeartbeatParams) error {
	_, err := q.db.Exec(ctx, recordHeartbeat,
		arg.HeartbeatInterval,
		arg.BatteryLevel,
		arg.IsCharging,
		arg.NetworkType,
		arg.CarrierName,
		arg.SimCount,
		arg.DeviceModel,
		arg.AndroidVersion,
		arg.AppVersion,
		arg.Sims,
		arg.ID,
	)
	return err
}

const renameDevice = `-- name: RenameDevice :one
UPDATE devices SET name = $1, updated_at = now()
WHERE id = $2 AND project_id = $3
RETURNING id, project_id, name, installation_id, credential_hash, status, last_heartbeat_at, last_seen_at, battery_level, is_charging, network_type, carrier_name, sim_count, device_model, android_version, app_version, created_at, updated_at, revoked_at, push_provider, push_endpoint, push_p256dh, push_auth, push_updated_at, connection_id, connected_at, heartbeat_interval, app_flavor, preferred_sim_slot, send_limit_count, send_limit_window_seconds, sims, forward_inbound, notified_presence, daily_send_limit
`

type RenameDeviceParams struct {
	Name      string
	ID        string
	ProjectID string
}

func (q *Queries) RenameDevice(ctx context.Context, arg RenameDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, renameDevice, arg.Name, arg.ID, arg.ProjectID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.InstallationID,
		&i.CredentialHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSeenAt,
		&i.BatteryLevel,
		&i.IsCharging,
		&i.NetworkType,
		&i.CarrierName,
		&i.SimCount,
		&i.DeviceModel,
		&i.AndroidVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.PushProvider,
		&i.PushEndpoint,
		&i.PushP256dh,
		&i.PushAuth,
		&i.PushUpdatedAt,
		&i.ConnectionID,
		&i.ConnectedAt,
		&i.HeartbeatInterval,
		&i.AppFlavor,
		&i.PreferredSimSlot,
		&i.SendLimitCount,
		&i.SendLimitWindowSeconds,
		&i.Sims,
		&i.ForwardInbound,
		&i.NotifiedPresence,
		&i.DailySendLimit,
	)
	return i, err
}

const repairDevice = `-- name: RepairDevice :one
UPDATE devices SET
    credential_hash = $1,
    name = $2,
    device_model = $3,
    android_version = $4,
    app_version = $5,
    app_flavor = $6,
    revoked_at = NULL,
    status = 'offline',
    connection_id = NULL,
    updated_at = now()
WHERE id = $7
RETURNING id, project_id, name, installation_id, credential_hash, status, last_heartbeat_at, last_seen_at, battery_level, is_charging, network_type, carrier_name, sim_count, device_model, android_version, app_version, created_at, updated_at, revoked_at, push_provider, push_endpoint, push_p256dh, push_auth, push_updated_at, connection_id, connected_at, heartbeat_interval, app_flavor, preferred_sim_slot, send_limit_count, send_limit_window_seconds, sims, forward_inbound, notified_presence, daily_send_limit
`

type RepairDeviceParams struct {
	CredentialHash []byte
	Name           string
	DeviceModel    *string
	AndroidVersion *string
	AppVersion     *string
	AppFlavor      *string
	ID             string
}

// Re-pairing the same installation rotates its credential and reactivates it.
func (q *Queries) RepairDevice(ctx context.Context, arg RepairDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, repairDevice,
		arg.CredentialHash,
		arg.Name,
		arg.DeviceModel,
		arg.AndroidVersion,
		arg.AppVersion,
		arg.AppFlavor,
		arg.ID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.InstallationID,
		&i.CredentialHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSeenAt,
		&i.BatteryLevel,
		&i.IsCharging,
		&i.NetworkType,
		&i.CarrierName,
		&i.SimCount,
		&i.DeviceModel,
		&i.AndroidVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.PushProvider,
		&i.PushEndpoint,
		&i.PushP256dh,
		&i.PushAuth,
		&i.PushUpdatedAt,
		&i.ConnectionID,
		&i.ConnectedAt,
		&i.HeartbeatInterval,
		&i.AppFlavor,
		&i.PreferredSimSlot,
		&i.SendLimitCount,
		&i.SendLimitWindowSeconds,
		&i.Sims,
		&i.ForwardInbound,
		&i.NotifiedPresence,
		&i.DailySendLimit,
	)
	return i, err
}

const revokeDevice = `-- name: RevokeDevice :one
UPDATE devices SET revoked_at = now(), status = 'disabled', connection_id = NULL, updated_at = now()
WHERE id = $1 AND project_id = $2 AND revoked_at IS NULL
RETURNING id, project_id, name, installation_id, credential_hash, status, last_heartbeat_at, last_seen_at, battery_level, is_charging, network_type, carrier_name, sim_count, device_model, android_version, app_version, created_at, updated_at, revoked_at, push_provider, push_endpoint, push_p256dh, push_auth, push_updated_at, connection_id, connected_at, heartbeat_interval, app_flavor, preferred_sim_slot, send_limit_count, send_limit_window_seconds, sims, forward_inbound, notified_presence, daily_send_limit
`

type RevokeDeviceParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, revokeDevice, arg.ID, arg.ProjectID)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.InstallationID,
		&i.CredentialHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSeenAt,
		&i.BatteryLevel,
		&i.IsCharging,
		&i.NetworkType,
		&i.CarrierName,
		&i.SimCount,
		&i.DeviceModel,
		&i.AndroidVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.PushProvider,
		&i.PushEndpoint,
		&i.PushP256dh,
		&i.PushAuth,
		&i.PushUpdatedAt,
		&i.ConnectionID,
		&i.ConnectedAt,
		&i.HeartbeatInterval,
		&i.AppFlavor,
		&i.PreferredSimSlot,
		&i.SendLimitCount,
		&i.SendLimitWindowSeconds,
		&i.Sims,
		&i.ForwardInbound,
		&i.NotifiedPresence,
		&i.DailySendLimit,
	)
	return i, err
}

const sweepStaleDevices = `-- name: SweepStaleDevices :execrows
UPDATE devices SET status = 'offline', connection_id = NULL, updated_at = now()
WHERE status = 'online'
  AND last_seen_at < now() - make_interval(secs => heartbeat_interval * 3 + 60)
`

// Marks devices offline whose connection vanished without a clean close
// (for example an API instance crash).
func (q *Queries) SweepStaleDevices(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, sweepStaleDevices)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDevicePush = `-- name: UpdateDevicePush :exec
UPDATE devices SET
    push_provider = $1,
    push_endpoint = $2,
    push_p256dh = $3,
    push_auth = $4,
    push_updated_at = now(),
    updated_at = now()
WHERE id = $5 AND revoked_at IS NULL
`

type UpdateDevicePushParams struct {
	PushProvider *string
	PushEndpoint *string
	PushP256dh   *string
	PushAuth     *string
	ID           string
}

func (q *Queries) UpdateDevicePush(ctx context.Context, arg UpdateDevicePushParams) error {
	_, err := q.db.Exec(ctx, updateDevicePush,
		arg.PushProvider,
		arg.PushEndpoint,
		arg.PushP256dh,
		arg.PushAuth,
		arg.ID,
	)
	return err
}
