// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verifications.sql

package dbq

import (
	"context"
	"time"
)

const consumeEmailVerification = `-- name: ConsumeEmailVerification :exec
UPDATE email_verifications SET consumed_at = now() WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeEmailVerification(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumeEmailVerification, id)
	return err
}

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (id, user_id, purpose, email, code_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, purpose, email, code_hash, attempts, expires_at, consumed_at, created_at
`

type CreateEmailVerificationParams struct {
	ID        string
	UserID    string
	Purpose   string
	Email     string
	CodeHash  []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.Email,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldEmailVerifications = `-- name: DeleteOldEmailVerifications :execrows
DELETE FROM email_verifications WHERE expires_at < $1
`

func (q *Queries) DeleteOldEmailVerifications(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldEmailVerifications, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireAllEmailVerifications = `-- name: ExpireAllEmailVerifications :exec
UPDATE email_verifications SET consumed_at = now() WHERE user_id = $1 AND consumed_at IS NULL
`

// A changed address makes every open code useless.
func (q *Queries) ExpireAllEmailVerifications(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, expireAllEmailVerifications, userID)
	return err
}

const expireEmailVerifications = `-- name: ExpireEmailVerifications :exec
UPDATE email_verifications SET consumed_at = now()
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
`

type ExpireEmailVerificationsParams struct {
	UserID  string
	Purpose string
}

// A new code makes the open codes of its purpose useless.
func (q *Queries) ExpireEmailVerifications(ctx context.Context, arg ExpireEmailVerificationsParams) error {
	_, err := q.db.Exec(ctx, expireEmailVerifications, arg.UserID, arg.Purpose)
	return err
}

const latestEmailVerification = `-- name: LatestEmailVerification :one
SELECT id, user_id, purpose, email, code_hash, attempts, expires_at, consumed_at, created_at FROM email_verifications
WHERE user_id = $1 AND purpose = $2
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type LatestEmailVerificationParams struct {
	UserID  string
	Purpose string
}

// The newest code of a purpose sent to the user, for the resend cooldown.
func (q *Queries) LatestEmailVerification(ctx context.Context, arg LatestEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, latestEmailVerification, arg.UserID, arg.Purpose)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const pendingEmailVerificationForUpdate = `-- name: PendingEmailVerificationForUpdate :one
SELECT id, user_id, purpose, email, code_hash, attempts, expires_at, consumed_at, created_at FROM email_verifications
WHERE user_id = $1 AND purpose = $2 AND consumed_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT 1
FOR UPDATE
`

type PendingEmailVerificationForUpdateParams struct {
	UserID  string
	Purpose string
}

func (q *Queries) PendingEmailVerificationForUpdate(ctx context.Context, arg PendingEmailVerificationForUpdateParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, pendingEmailVerificationForUpdate, arg.UserID, arg.Purpose)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const recordEmailVerificationAttempt = `-- name: RecordEmailVerificationAttempt :one
UPDATE email_verifications
SET attempts = attempts + 1,
    consumed_at = CASE WHEN attempts + 1 >= $1::integer THEN now() ELSE consumed_at END
WHERE id = $2
RETURNING id, user_id, purpose, email, code_hash, attempts, expires_at, consumed_at, created_at
`

type RecordEmailVerificationAttemptParams struct {
	MaxAttempts int32
	ID          string
}

// Counts a wrong code; the last allowed attempt also uses the code up.
func (q *Queries) RecordEmailVerificationAttempt(ctx context.Context, arg RecordEmailVerificationAttemptParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, recordEmailVerificationAttempt, arg.MaxAttempts, arg.ID)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
