// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: insights.sql

package dbq

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insightsActiveOrganizations = `-- name: InsightsActiveOrganizations :one
WITH recent AS (
    SELECT project_id, max(created_at) AS last_sent
    FROM messages
    WHERE created_at >= now() - interval '30 days' AND direction = 'outbound'
    GROUP BY project_id
)
SELECT (count(DISTINCT p.organization_id) FILTER (WHERE r.last_sent >= now() - interval '7 days'))::int AS active_7d,
       count(DISTINCT p.organization_id)::int AS active_30d
FROM recent r
JOIN projects p ON p.id = r.project_id
`

type InsightsActiveOrganizationsRow struct {
	Active7d  int32
	Active30d int32
}

// Workspaces that sent at least one message (live or test) in the last 7 and 30 days.
func (q *Queries) InsightsActiveOrganizations(ctx context.Context) (InsightsActiveOrganizationsRow, error) {
	row := q.db.QueryRow(ctx, insightsActiveOrganizations)
	var i InsightsActiveOrganizationsRow
	err := row.Scan(&i.Active7d, &i.Active30d)
	return i, err
}

const insightsMRR = `-- name: InsightsMRR :one
SELECT COALESCE(sum(pl.price_cents), 0)::bigint AS mrr_cents
FROM subscriptions s
JOIN plans pl ON pl.id = s.plan_id
WHERE s.status = 'active'
`

// Monthly recurring revenue of active subscriptions, in the plans' smallest unit.
func (q *Queries) InsightsMRR(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, insightsMRR)
	var mrr_cents int64
	err := row.Scan(&mrr_cents)
	return mrr_cents, err
}

const insightsMessagesByProvider = `-- name: InsightsMessagesByProvider :many
SELECT provider, count(*)::int AS messages
FROM messages
WHERE created_at >= $1 AND direction = 'outbound'
GROUP BY provider
ORDER BY 2 DESC, 1
LIMIT 20
`

type InsightsMessagesByProviderRow struct {
	Provider string
	Messages int32
}

// Outgoing messages per route; "simulator" is test mode, "android" a paired phone.
func (q *Queries) InsightsMessagesByProvider(ctx context.Context, since time.Time) ([]InsightsMessagesByProviderRow, error) {
	rows, err := q.db.Query(ctx, insightsMessagesByProvider, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightsMessagesByProviderRow{}
	for rows.Next() {
		var i InsightsMessagesByProviderRow
		if err := rows.Scan(&i.Provider, &i.Messages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insightsMessagesDaily = `-- name: InsightsMessagesDaily :many
WITH days AS (
    SELECT d::date AS day
    FROM generate_series($1::date, $2::date, interval '1 day') AS d
), m AS (
    SELECT (created_at AT TIME ZONE 'UTC')::date AS day,
           count(*) FILTER (WHERE direction = 'outbound' AND environment = 'live') AS live,
           count(*) FILTER (WHERE direction = 'outbound' AND environment = 'test') AS test,
           count(*) FILTER (WHERE direction = 'outbound' AND environment = 'live' AND status = 'delivered') AS delivered,
           count(*) FILTER (WHERE direction = 'outbound' AND environment = 'live' AND status = 'sent') AS sent,
           count(*) FILTER (WHERE direction = 'outbound' AND environment = 'live' AND status = 'failed') AS failed,
           count(*) FILTER (WHERE direction = 'outbound' AND environment = 'live'
                            AND status IN ('created', 'queued', 'sending')) AS pending,
           count(*) FILTER (WHERE direction = 'inbound') AS inbound
    FROM messages
    WHERE created_at >= $3
    GROUP BY 1
)
SELECT to_char(days.day, 'YYYY-MM-DD')::text AS date,
       COALESCE(m.live, 0)::int AS live,
       COALESCE(m.test, 0)::int AS test,
       COALESCE(m.delivered, 0)::int AS delivered,
       COALESCE(m.sent, 0)::int AS sent,
       COALESCE(m.failed, 0)::int AS failed,
       COALESCE(m.pending, 0)::int AS pending,
       COALESCE(m.inbound, 0)::int AS inbound
FROM days
LEFT JOIN m ON m.day = days.day
ORDER BY days.day
`

type InsightsMessagesDailyParams struct {
	FirstDay pgtype.Date
	LastDay  pgtype.Date
	Since    time.Time
}

type InsightsMessagesDailyRow struct {
	Date      string
	Live      int32
	Test      int32
	Delivered int32
	Sent      int32
	Failed    int32
	Pending   int32
	Inbound   int32
}

// One row per UTC day, like InsightsSignupsDaily. Statuses count live outgoing
// messages only; test messages are simulated.
func (q *Queries) InsightsMessagesDaily(ctx context.Context, arg InsightsMessagesDailyParams) ([]InsightsMessagesDailyRow, error) {
	rows, err := q.db.Query(ctx, insightsMessagesDaily, arg.FirstDay, arg.LastDay, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightsMessagesDailyRow{}
	for rows.Next() {
		var i InsightsMessagesDailyRow
		if err := rows.Scan(
			&i.Date,
			&i.Live,
			&i.Test,
			&i.Delivered,
			&i.Sent,
			&i.Failed,
			&i.Pending,
			&i.Inbound,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insightsPlanMix = `-- name: InsightsPlanMix :many
WITH effective AS (
    SELECT CASE WHEN s.status IN ('active', 'past_due') THEN s.plan_id ELSE $1::text END AS plan_id
    FROM organizations o
    LEFT JOIN subscriptions s ON s.organization_id = o.id
)
SELECT pl.id, pl.name, pl.price_cents, pl.currency, count(e.plan_id)::int AS organizations
FROM plans pl
LEFT JOIN effective e ON e.plan_id = pl.id
GROUP BY pl.id
ORDER BY pl.sort_order, pl.id
`

type InsightsPlanMixRow struct {
	ID            string
	Name          string
	PriceCents    int32
	Currency      string
	Organizations int32
}

// Workspaces per plan in effect: active and past_due subscriptions keep their
// plan, everything else is on @free_plan.
func (q *Queries) InsightsPlanMix(ctx context.Context, freePlan string) ([]InsightsPlanMixRow, error) {
	rows, err := q.db.Query(ctx, insightsPlanMix, freePlan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightsPlanMixRow{}
	for rows.Next() {
		var i InsightsPlanMixRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceCents,
			&i.Currency,
			&i.Organizations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insightsRecentSubscriptions = `-- name: InsightsRecentSubscriptions :many
SELECT s.organization_id, o.name AS organization_name, pl.name AS plan_name, s.status,
       s.cancel_at_period_end, s.updated_at
FROM subscriptions s
JOIN organizations o ON o.id = s.organization_id
JOIN plans pl ON pl.id = s.plan_id
ORDER BY s.updated_at DESC, s.organization_id
LIMIT 10
`

type InsightsRecentSubscriptionsRow struct {
	OrganizationID    string
	OrganizationName  string
	PlanName          string
	Status            string
	CancelAtPeriodEnd bool
	UpdatedAt         time.Time
}

func (q *Queries) InsightsRecentSubscriptions(ctx context.Context) ([]InsightsRecentSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, insightsRecentSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightsRecentSubscriptionsRow{}
	for rows.Next() {
		var i InsightsRecentSubscriptionsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.OrganizationName,
			&i.PlanName,
			&i.Status,
			&i.CancelAtPeriodEnd,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insightsRecentUsers = `-- name: InsightsRecentUsers :many
SELECT u.id, u.email, u.name, u.created_at, u.email_verified_at, u.phone_verified_at,
       (SELECT count(*) FROM organization_members m WHERE m.user_id = u.id)::int AS organizations
FROM users u
ORDER BY u.created_at DESC, u.id DESC
LIMIT 15
`

type InsightsRecentUsersRow struct {
	ID              string
	Email           string
	Name            string
	CreatedAt       time.Time
	EmailVerifiedAt *time.Time
	PhoneVerifiedAt *time.Time
	Organizations   int32
}

func (q *Queries) InsightsRecentUsers(ctx context.Context) ([]InsightsRecentUsersRow, error) {
	rows, err := q.db.Query(ctx, insightsRecentUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightsRecentUsersRow{}
	for rows.Next() {
		var i InsightsRecentUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
			&i.EmailVerifiedAt,
			&i.PhoneVerifiedAt,
			&i.Organizations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insightsSignupsDaily = `-- name: InsightsSignupsDaily :many
WITH days AS (
    SELECT d::date AS day
    FROM generate_series($1::date, $2::date, interval '1 day') AS d
), u AS (
    SELECT (su.created_at AT TIME ZONE 'UTC')::date AS day, count(*) AS n
    FROM users su WHERE su.created_at >= $3 GROUP BY 1
), o AS (
    SELECT (so.created_at AT TIME ZONE 'UTC')::date AS day, count(*) AS n
    FROM organizations so WHERE so.created_at >= $3 GROUP BY 1
)
SELECT to_char(days.day, 'YYYY-MM-DD')::text AS date,
       COALESCE(u.n, 0)::int AS users,
       COALESCE(o.n, 0)::int AS organizations
FROM days
LEFT JOIN u ON u.day = days.day
LEFT JOIN o ON o.day = days.day
ORDER BY days.day
`

type InsightsSignupsDailyParams struct {
	FirstDay pgtype.Date
	LastDay  pgtype.Date
	Since    time.Time
}

type InsightsSignupsDailyRow struct {
	Date          string
	Users         int32
	Organizations int32
}

// One row per day from @first_day to @last_day, including days without sign-ups.
// @since is the start of @first_day in UTC; days are UTC calendar days.
func (q *Queries) InsightsSignupsDaily(ctx context.Context, arg InsightsSignupsDailyParams) ([]InsightsSignupsDailyRow, error) {
	rows, err := q.db.Query(ctx, insightsSignupsDaily, arg.FirstDay, arg.LastDay, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightsSignupsDailyRow{}
	for rows.Next() {
		var i InsightsSignupsDailyRow
		if err := rows.Scan(&i.Date, &i.Users, &i.Organizations); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insightsTopErrors = `-- name: InsightsTopErrors :many
SELECT COALESCE(error_code, 'unknown')::text AS error_code, count(*)::int AS messages
FROM messages
WHERE created_at >= $1 AND environment = 'live' AND direction = 'outbound' AND status = 'failed'
GROUP BY 1
ORDER BY 2 DESC, 1
LIMIT 8
`

type InsightsTopErrorsRow struct {
	ErrorCode string
	Messages  int32
}

func (q *Queries) InsightsTopErrors(ctx context.Context, since time.Time) ([]InsightsTopErrorsRow, error) {
	rows, err := q.db.Query(ctx, insightsTopErrors, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightsTopErrorsRow{}
	for rows.Next() {
		var i InsightsTopErrorsRow
		if err := rows.Scan(&i.ErrorCode, &i.Messages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insightsTopOrganizations = `-- name: InsightsTopOrganizations :many
WITH by_project AS (
    SELECT bm.project_id, count(*) AS n
    FROM messages bm
    WHERE bm.created_at >= $2 AND bm.environment = 'live' AND bm.direction = 'outbound'
    GROUP BY bm.project_id
), top AS (
    SELECT p.organization_id, sum(b.n) AS messages
    FROM by_project b
    JOIN projects p ON p.id = b.project_id
    GROUP BY p.organization_id
    ORDER BY 2 DESC, 1
    LIMIT 10
)
SELECT t.organization_id,
       o.name,
       t.messages::int AS messages,
       (SELECT count(*) FROM devices d JOIN projects dp ON dp.id = d.project_id
         WHERE dp.organization_id = t.organization_id AND d.revoked_at IS NULL)::int AS phones,
       pl.name AS plan_name
FROM top t
JOIN organizations o ON o.id = t.organization_id
LEFT JOIN subscriptions s ON s.organization_id = t.organization_id
JOIN plans pl ON pl.id = CASE WHEN s.status IN ('active', 'past_due') THEN s.plan_id ELSE $1::text END
ORDER BY t.messages DESC, t.organization_id
`

type InsightsTopOrganizationsParams struct {
	FreePlan string
	Since    time.Time
}

type InsightsTopOrganizationsRow struct {
	OrganizationID string
	Name           string
	Messages       int32
	Phones         int32
	PlanName       string
}

// The ten workspaces that sent the most live messages since @since, with their
// paired phones and the plan in effect (@free_plan without an active subscription).
func (q *Queries) InsightsTopOrganizations(ctx context.Context, arg InsightsTopOrganizationsParams) ([]InsightsTopOrganizationsRow, error) {
	rows, err := q.db.Query(ctx, insightsTopOrganizations, arg.FreePlan, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsightsTopOrganizationsRow{}
	for rows.Next() {
		var i InsightsTopOrganizationsRow
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Name,
			&i.Messages,
			&i.Phones,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insightsTotals = `-- name: InsightsTotals :one

SELECT (SELECT count(*) FROM users)::int AS users,
       (SELECT count(*) FROM users WHERE email_verified_at IS NOT NULL)::int AS users_email_verified,
       (SELECT count(*) FROM users WHERE phone_verified_at IS NOT NULL)::int AS users_with_phone,
       (SELECT count(*) FROM users u WHERE u.created_at >= $1)::int AS users_in_range,
       (SELECT count(*) FROM organizations)::int AS organizations,
       (SELECT count(*) FROM organizations o WHERE o.created_at >= $1)::int AS organizations_in_range,
       (SELECT count(*) FROM projects)::int AS projects,
       (SELECT count(*) FROM api_keys
         WHERE revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now()))::int AS api_keys,
       (SELECT count(*) FROM subscriptions WHERE status = 'active')::int AS subscriptions_active,
       (SELECT count(DISTINCT user_id) FROM sessions
         WHERE last_seen_at >= now() - interval '7 days')::int AS active_users_7d
`

type InsightsTotalsRow struct {
	Users                int32
	UsersEmailVerified   int32
	UsersWithPhone       int32
	UsersInRange         int32
	Organizations        int32
	OrganizationsInRange int32
	Projects             int32
	APIKeys              int32
	SubscriptionsActive  int32
	ActiveUsers7d        int32
}

// Operator Insights: instance-wide aggregates for GET /v1/system/insights.
// Every query is bounded by created_at >= @since or by a LIMIT, and none
// returns message bodies or phone numbers.
func (q *Queries) InsightsTotals(ctx context.Context, since time.Time) (InsightsTotalsRow, error) {
	row := q.db.QueryRow(ctx, insightsTotals, since)
	var i InsightsTotalsRow
	err := row.Scan(
		&i.Users,
		&i.UsersEmailVerified,
		&i.UsersWithPhone,
		&i.UsersInRange,
		&i.Organizations,
		&i.OrganizationsInRange,
		&i.Projects,
		&i.APIKeys,
		&i.SubscriptionsActive,
		&i.ActiveUsers7d,
	)
	return i, err
}

const insightsVerify = `-- name: InsightsVerify :one
SELECT count(*)::int AS started,
       (count(*) FILTER (WHERE status = 'verified'))::int AS verified
FROM otp_verifications
WHERE created_at >= $1
`

type InsightsVerifyRow struct {
	Started  int32
	Verified int32
}

func (q *Queries) InsightsVerify(ctx context.Context, since time.Time) (InsightsVerifyRow, error) {
	row := q.db.QueryRow(ctx, insightsVerify, since)
	var i InsightsVerifyRow
	err := row.Scan(&i.Started, &i.Verified)
	return i, err
}
