// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package dbq

import (
	"context"
)

const deleteIntegration = `-- name: DeleteIntegration :execrows
DELETE FROM integrations WHERE id = $1 AND project_id = $2
`

type DeleteIntegrationParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) DeleteIntegration(ctx context.Context, arg DeleteIntegrationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIntegration, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIntegration = `-- name: GetIntegration :one
SELECT id, project_id, kind, environment, secret, last_used_at, last_error, created_at, updated_at FROM integrations WHERE id = $1 AND project_id = $2
`

type GetIntegrationParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetIntegration(ctx context.Context, arg GetIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegration, arg.ID, arg.ProjectID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Environment,
		&i.Secret,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationByID = `-- name: GetIntegrationByID :one
SELECT id, project_id, kind, environment, secret, last_used_at, last_error, created_at, updated_at FROM integrations WHERE id = $1
`

func (q *Queries) GetIntegrationByID(ctx context.Context, id string) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByID, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Environment,
		&i.Secret,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertIntegration = `-- name: InsertIntegration :one
INSERT INTO integrations (id, project_id, kind, environment)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, kind, environment, secret, last_used_at, last_error, created_at, updated_at
`

type InsertIntegrationParams struct {
	ID          string
	ProjectID   string
	Kind        string
	Environment APIEnvironment
}

func (q *Queries) InsertIntegration(ctx context.Context, arg InsertIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, insertIntegration,
		arg.ID,
		arg.ProjectID,
		arg.Kind,
		arg.Environment,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Environment,
		&i.Secret,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrations = `-- name: ListIntegrations :many
SELECT id, project_id, kind, environment, secret, last_used_at, last_error, created_at, updated_at FROM integrations WHERE project_id = $1 ORDER BY created_at
`

func (q *Queries) ListIntegrations(ctx context.Context, projectID string) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrations, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Environment,
			&i.Secret,
			&i.LastUsedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordIntegrationUse = `-- name: RecordIntegrationUse :exec
UPDATE integrations SET
    last_used_at = now(),
    last_error   = $1,
    updated_at   = now()
WHERE id = $2
`

type RecordIntegrationUseParams struct {
	Error *string
	ID    string
}

func (q *Queries) RecordIntegrationUse(ctx context.Context, arg RecordIntegrationUseParams) error {
	_, err := q.db.Exec(ctx, recordIntegrationUse, arg.Error, arg.ID)
	return err
}

const setIntegrationEnvironment = `-- name: SetIntegrationEnvironment :one
UPDATE integrations SET environment = $1, updated_at = now()
WHERE id = $2 AND project_id = $3
RETURNING id, project_id, kind, environment, secret, last_used_at, last_error, created_at, updated_at
`

type SetIntegrationEnvironmentParams struct {
	Environment APIEnvironment
	ID          string
	ProjectID   string
}

func (q *Queries) SetIntegrationEnvironment(ctx context.Context, arg SetIntegrationEnvironmentParams) (Integration, error) {
	row := q.db.QueryRow(ctx, setIntegrationEnvironment, arg.Environment, arg.ID, arg.ProjectID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Environment,
		&i.Secret,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setIntegrationSecret = `-- name: SetIntegrationSecret :one
UPDATE integrations SET secret = $1, updated_at = now()
WHERE id = $2 AND project_id = $3
RETURNING id, project_id, kind, environment, secret, last_used_at, last_error, created_at, updated_at
`

type SetIntegrationSecretParams struct {
	Secret    []byte
	ID        string
	ProjectID string
}

func (q *Queries) SetIntegrationSecret(ctx context.Context, arg SetIntegrationSecretParams) (Integration, error) {
	row := q.db.QueryRow(ctx, setIntegrationSecret, arg.Secret, arg.ID, arg.ProjectID)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Environment,
		&i.Secret,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
