// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package dbq

import (
	"context"
	"time"
)

const deleteExpiredPairingTokens = `-- name: DeleteExpiredPairingTokens :execrows
DELETE FROM device_pairing_tokens WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredPairingTokens(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredPairingTokens, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleRateLimits = `-- name: DeleteStaleRateLimits :execrows
DELETE FROM rate_limit_counters WHERE window_start < $1
`

func (q *Queries) DeleteStaleRateLimits(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleRateLimits, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hitRateLimit = `-- name: HitRateLimit :one
INSERT INTO rate_limit_counters AS c (key, window_start, count)
VALUES ($1, $2, 1)
ON CONFLICT (key) DO UPDATE SET
    count = CASE WHEN c.window_start >= EXCLUDED.window_start THEN c.count + 1 ELSE 1 END,
    window_start = GREATEST(c.window_start, EXCLUDED.window_start)
RETURNING count
`

type HitRateLimitParams struct {
	Key         string
	WindowStart time.Time
}

func (q *Queries) HitRateLimit(ctx context.Context, arg HitRateLimitParams) (int32, error) {
	row := q.db.QueryRow(ctx, hitRateLimit, arg.Key, arg.WindowStart)
	var count int32
	err := row.Scan(&count)
	return count, err
}
