// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const assignMessage = `-- name: AssignMessage :one
UPDATE messages SET device_id = $1, assigned_at = now(), attempts = attempts + 1, updated_at = now()
WHERE id = $2 AND status = 'queued' AND device_id IS NULL
RETURNING id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars
`

type AssignMessageParams struct {
	DeviceID *string
	ID       string
}

func (q *Queries) AssignMessage(ctx context.Context, arg AssignMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, assignMessage, arg.DeviceID, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.DeviceID,
		&i.APIKeyID,
		&i.Recipient,
		&i.Sender,
		&i.Body,
		&i.Segments,
		&i.Attempts,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SendingAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UpdatedAt,
		&i.RequestedDeviceID,
		&i.SimSlot,
		&i.AssignedAt,
		&i.IdempotencyHash,
		&i.BodySha256,
		&i.BodyLength,
		&i.BodyRedactedAt,
		&i.Encoding,
		&i.Purpose,
		&i.DisplayBody,
		&i.ProviderAccountID,
		&i.BodyVars,
	)
	return i, err
}

const dailyMessageUsage = `-- name: DailyMessageUsage :many
SELECT to_char(created_at AT TIME ZONE $1::text, 'YYYY-MM-DD')::text AS day,
       count(*) FILTER (WHERE direction = 'outbound')::int AS outbound,
       count(*) FILTER (WHERE direction = 'outbound' AND status = 'delivered')::int AS delivered,
       count(*) FILTER (WHERE direction = 'outbound' AND status = 'sent')::int AS sent,
       count(*) FILTER (WHERE direction = 'outbound' AND status = 'failed')::int AS failed,
       count(*) FILTER (WHERE direction = 'outbound' AND status IN ('created', 'queued', 'sending'))::int AS pending,
       count(*) FILTER (WHERE direction = 'inbound')::int AS inbound,
       COALESCE(sum(segments) FILTER (WHERE direction = 'outbound'), 0)::int AS segments
FROM messages
WHERE project_id = $2 AND environment = $3 AND created_at >= $4
GROUP BY 1
ORDER BY 1
`

type DailyMessageUsageParams struct {
	Tz          string
	ProjectID   string
	Environment APIEnvironment
	Since       time.Time
}

type DailyMessageUsageRow struct {
	Day       string
	Outbound  int32
	Delivered int32
	Sent      int32
	Failed    int32
	Pending   int32
	Inbound   int32
	Segments  int32
}

func (q *Queries) DailyMessageUsage(ctx context.Context, arg DailyMessageUsageParams) ([]DailyMessageUsageRow, error) {
	rows, err := q.db.Query(ctx, dailyMessageUsage,
		arg.Tz,
		arg.ProjectID,
		arg.Environment,
		arg.Since,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyMessageUsageRow{}
	for rows.Next() {
		var i DailyMessageUsageRow
		if err := rows.Scan(
			&i.Day,
			&i.Outbound,
			&i.Delivered,
			&i.Sent,
			&i.Failed,
			&i.Pending,
			&i.Inbound,
			&i.Segments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deviceMessageUsage = `-- name: DeviceMessageUsage :many
SELECT m.device_id::text AS device_id,
       COALESCE(max(d.name), '')::text AS device_name,
       count(*) FILTER (WHERE m.direction = 'outbound')::int AS outbound,
       count(*) FILTER (WHERE m.direction = 'outbound' AND m.status = 'delivered')::int AS delivered,
       count(*) FILTER (WHERE m.direction = 'outbound' AND m.status = 'failed')::int AS failed,
       count(*) FILTER (WHERE m.direction = 'inbound')::int AS inbound,
       COALESCE(sum(m.segments) FILTER (WHERE m.direction = 'outbound'), 0)::int AS segments
FROM messages m
LEFT JOIN devices d ON d.id = m.device_id
WHERE m.project_id = $1 AND m.environment = $2 AND m.created_at >= $3 AND m.device_id IS NOT NULL
GROUP BY m.device_id
ORDER BY outbound DESC, inbound DESC
`

type DeviceMessageUsageParams struct {
	ProjectID   string
	Environment APIEnvironment
	Since       time.Time
}

type DeviceMessageUsageRow struct {
	DeviceID   string
	DeviceName string
	Outbound   int32
	Delivered  int32
	Failed     int32
	Inbound    int32
	Segments   int32
}

func (q *Queries) DeviceMessageUsage(ctx context.Context, arg DeviceMessageUsageParams) ([]DeviceMessageUsageRow, error) {
	rows, err := q.db.Query(ctx, deviceMessageUsage, arg.ProjectID, arg.Environment, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceMessageUsageRow{}
	for rows.Next() {
		var i DeviceMessageUsageRow
		if err := rows.Scan(
			&i.DeviceID,
			&i.DeviceName,
			&i.Outbound,
			&i.Delivered,
			&i.Failed,
			&i.Inbound,
			&i.Segments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deviceWindowCounts = `-- name: DeviceWindowCounts :many
SELECT d.id,
       (SELECT count(*) FROM messages m
         WHERE m.device_id = d.id
           AND m.assigned_at > now() - make_interval(secs => d.send_limit_window_seconds))::int AS recent_sends,
       (SELECT count(*) FROM messages m WHERE m.device_id = d.id AND m.status IN ('sent', 'delivered'))::int AS total_sent,
       (SELECT count(*) FROM messages m WHERE m.device_id = d.id AND m.status = 'failed')::int AS total_failed
FROM devices d
WHERE d.project_id = $1
`

type DeviceWindowCountsRow struct {
	ID          string
	RecentSends int32
	TotalSent   int32
	TotalFailed int32
}

func (q *Queries) DeviceWindowCounts(ctx context.Context, projectID string) ([]DeviceWindowCountsRow, error) {
	rows, err := q.db.Query(ctx, deviceWindowCounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeviceWindowCountsRow{}
	for rows.Next() {
		var i DeviceWindowCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecentSends,
			&i.TotalSent,
			&i.TotalFailed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dispatchCandidates = `-- name: DispatchCandidates :many
SELECT devices.id, devices.project_id, devices.name, devices.installation_id, devices.credential_hash, devices.status, devices.last_heartbeat_at, devices.last_seen_at, devices.battery_level, devices.is_charging, devices.network_type, devices.carrier_name, devices.sim_count, devices.device_model, devices.android_version, devices.app_version, devices.created_at, devices.updated_at, devices.revoked_at, devices.push_provider, devices.push_endpoint, devices.push_p256dh, devices.push_auth, devices.push_updated_at, devices.connection_id, devices.connected_at, devices.heartbeat_interval, devices.app_flavor, devices.preferred_sim_slot, devices.send_limit_count, devices.send_limit_window_seconds, devices.sims, devices.forward_inbound, devices.notified_presence,
       (SELECT count(*) FROM messages m
         WHERE m.device_id = devices.id
           AND m.assigned_at > now() - make_interval(secs => devices.send_limit_window_seconds))::int AS recent_sends,
       -- Epoch stands for "none" so the columns are never NULL.
       COALESCE((SELECT min(m.assigned_at) FROM messages m
         WHERE m.device_id = devices.id
           AND m.assigned_at > now() - make_interval(secs => devices.send_limit_window_seconds)), to_timestamp(0))::timestamptz AS oldest_in_window,
       COALESCE((SELECT max(m.assigned_at) FROM messages m WHERE m.device_id = devices.id), to_timestamp(0))::timestamptz AS last_assigned
FROM devices
WHERE devices.project_id = $1 AND devices.revoked_at IS NULL
`

type DispatchCandidatesRow struct {
	Device         Device
	RecentSends    int32
	OldestInWindow time.Time
	LastAssigned   time.Time
}

func (q *Queries) DispatchCandidates(ctx context.Context, projectID string) ([]DispatchCandidatesRow, error) {
	rows, err := q.db.Query(ctx, dispatchCandidates, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DispatchCandidatesRow{}
	for rows.Next() {
		var i DispatchCandidatesRow
		if err := rows.Scan(
			&i.Device.ID,
			&i.Device.ProjectID,
			&i.Device.Name,
			&i.Device.InstallationID,
			&i.Device.CredentialHash,
			&i.Device.Status,
			&i.Device.LastHeartbeatAt,
			&i.Device.LastSeenAt,
			&i.Device.BatteryLevel,
			&i.Device.IsCharging,
			&i.Device.NetworkType,
			&i.Device.CarrierName,
			&i.Device.SimCount,
			&i.Device.DeviceModel,
			&i.Device.AndroidVersion,
			&i.Device.AppVersion,
			&i.Device.CreatedAt,
			&i.Device.UpdatedAt,
			&i.Device.RevokedAt,
			&i.Device.PushProvider,
			&i.Device.PushEndpoint,
			&i.Device.PushP256dh,
			&i.Device.PushAuth,
			&i.Device.PushUpdatedAt,
			&i.Device.ConnectionID,
			&i.Device.ConnectedAt,
			&i.Device.HeartbeatInterval,
			&i.Device.AppFlavor,
			&i.Device.PreferredSimSlot,
			&i.Device.SendLimitCount,
			&i.Device.SendLimitWindowSeconds,
			&i.Device.Sims,
			&i.Device.ForwardInbound,
			&i.Device.NotifiedPresence,
			&i.RecentSends,
			&i.OldestInWindow,
			&i.LastAssigned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars FROM messages WHERE id = $1 AND project_id = $2
`

type GetMessageParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessage, arg.ID, arg.ProjectID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.DeviceID,
		&i.APIKeyID,
		&i.Recipient,
		&i.Sender,
		&i.Body,
		&i.Segments,
		&i.Attempts,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SendingAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UpdatedAt,
		&i.RequestedDeviceID,
		&i.SimSlot,
		&i.AssignedAt,
		&i.IdempotencyHash,
		&i.BodySha256,
		&i.BodyLength,
		&i.BodyRedactedAt,
		&i.Encoding,
		&i.Purpose,
		&i.DisplayBody,
		&i.ProviderAccountID,
		&i.BodyVars,
	)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars FROM messages WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.DeviceID,
		&i.APIKeyID,
		&i.Recipient,
		&i.Sender,
		&i.Body,
		&i.Segments,
		&i.Attempts,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SendingAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UpdatedAt,
		&i.RequestedDeviceID,
		&i.SimSlot,
		&i.AssignedAt,
		&i.IdempotencyHash,
		&i.BodySha256,
		&i.BodyLength,
		&i.BodyRedactedAt,
		&i.Encoding,
		&i.Purpose,
		&i.DisplayBody,
		&i.ProviderAccountID,
		&i.BodyVars,
	)
	return i, err
}

const getMessageByIdempotencyKey = `-- name: GetMessageByIdempotencyKey :one
SELECT id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars FROM messages WHERE project_id = $1 AND idempotency_key = $2
`

type GetMessageByIdempotencyKeyParams struct {
	ProjectID      string
	IdempotencyKey *string
}

func (q *Queries) GetMessageByIdempotencyKey(ctx context.Context, arg GetMessageByIdempotencyKeyParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByIdempotencyKey, arg.ProjectID, arg.IdempotencyKey)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.DeviceID,
		&i.APIKeyID,
		&i.Recipient,
		&i.Sender,
		&i.Body,
		&i.Segments,
		&i.Attempts,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SendingAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UpdatedAt,
		&i.RequestedDeviceID,
		&i.SimSlot,
		&i.AssignedAt,
		&i.IdempotencyHash,
		&i.BodySha256,
		&i.BodyLength,
		&i.BodyRedactedAt,
		&i.Encoding,
		&i.Purpose,
		&i.DisplayBody,
		&i.ProviderAccountID,
		&i.BodyVars,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (
    id, project_id, environment, direction, status, provider, api_key_id, requested_device_id,
    recipient, body, segments, encoding, metadata, idempotency_key, idempotency_hash, sim_slot,
    body_sha256, body_length, purpose, display_body, body_vars, queued_at
) VALUES (
    $1, $2, $3, 'outbound', 'queued', $4, $5, $6,
    $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, now()
)
RETURNING id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars
`

type InsertMessageParams struct {
	ID                string
	ProjectID         string
	Environment       APIEnvironment
	Provider          string
	APIKeyID          *string
	RequestedDeviceID *string
	Recipient         string
	Body              string
	Segments          *int16
	Encoding          *string
	Metadata          json.RawMessage
	IdempotencyKey    *string
	IdempotencyHash   []byte
	SimSlot           *int16
	BodySha256        []byte
	BodyLength        *int32
	Purpose           string
	DisplayBody       *string
	BodyVars          []byte
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.ProjectID,
		arg.Environment,
		arg.Provider,
		arg.APIKeyID,
		arg.RequestedDeviceID,
		arg.Recipient,
		arg.Body,
		arg.Segments,
		arg.Encoding,
		arg.Metadata,
		arg.IdempotencyKey,
		arg.IdempotencyHash,
		arg.SimSlot,
		arg.BodySha256,
		arg.BodyLength,
		arg.Purpose,
		arg.DisplayBody,
		arg.BodyVars,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.DeviceID,
		&i.APIKeyID,
		&i.Recipient,
		&i.Sender,
		&i.Body,
		&i.Segments,
		&i.Attempts,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SendingAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UpdatedAt,
		&i.RequestedDeviceID,
		&i.SimSlot,
		&i.AssignedAt,
		&i.IdempotencyHash,
		&i.BodySha256,
		&i.BodyLength,
		&i.BodyRedactedAt,
		&i.Encoding,
		&i.Purpose,
		&i.DisplayBody,
		&i.ProviderAccountID,
		&i.BodyVars,
	)
	return i, err
}

const insertMessageEvent = `-- name: InsertMessageEvent :exec
INSERT INTO message_events (id, message_id, project_id, type, from_status, to_status, detail)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertMessageEventParams struct {
	ID         string
	MessageID  string
	ProjectID  string
	Type       string
	FromStatus *MessageStatus
	ToStatus   *MessageStatus
	Detail     json.RawMessage
}

func (q *Queries) InsertMessageEvent(ctx context.Context, arg InsertMessageEventParams) error {
	_, err := q.db.Exec(ctx, insertMessageEvent,
		arg.ID,
		arg.MessageID,
		arg.ProjectID,
		arg.Type,
		arg.FromStatus,
		arg.ToStatus,
		arg.Detail,
	)
	return err
}

const listMessageEvents = `-- name: ListMessageEvents :many
SELECT id, message_id, project_id, type, from_status, to_status, detail, created_at FROM message_events WHERE message_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListMessageEvents(ctx context.Context, messageID string) ([]MessageEvent, error) {
	rows, err := q.db.Query(ctx, listMessageEvents, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageEvent{}
	for rows.Next() {
		var i MessageEvent
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ProjectID,
			&i.Type,
			&i.FromStatus,
			&i.ToStatus,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars FROM messages
WHERE project_id = $1
  AND ($2::api_environment IS NULL OR environment = $2)
  AND ($3::message_status IS NULL OR status = $3)
  AND ($4::message_direction IS NULL OR direction = $4)
  AND ($5::text IS NULL OR device_id = $5)
  AND ($6::text IS NULL OR recipient = $6)
  AND ($7::text IS NULL OR sender = $7)
  AND ($8::timestamptz IS NULL
       OR (created_at, id) < ($8::timestamptz, $9::text))
ORDER BY created_at DESC, id DESC
LIMIT $10
`

type ListMessagesParams struct {
	ProjectID     string
	Environment   *APIEnvironment
	Status        *MessageStatus
	Direction     *MessageDirection
	DeviceID      *string
	Recipient     *string
	Sender        *string
	BeforeCreated *time.Time
	BeforeID      *string
	RowLimit      int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages,
		arg.ProjectID,
		arg.Environment,
		arg.Status,
		arg.Direction,
		arg.DeviceID,
		arg.Recipient,
		arg.Sender,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Environment,
			&i.Direction,
			&i.Status,
			&i.Provider,
			&i.DeviceID,
			&i.APIKeyID,
			&i.Recipient,
			&i.Sender,
			&i.Body,
			&i.Segments,
			&i.Attempts,
			&i.ProviderMessageID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.QueuedAt,
			&i.SendingAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.UpdatedAt,
			&i.RequestedDeviceID,
			&i.SimSlot,
			&i.AssignedAt,
			&i.IdempotencyHash,
			&i.BodySha256,
			&i.BodyLength,
			&i.BodyRedactedAt,
			&i.Encoding,
			&i.Purpose,
			&i.DisplayBody,
			&i.ProviderAccountID,
			&i.BodyVars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUnassignedMessage = `-- name: LockUnassignedMessage :one
SELECT id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars FROM messages WHERE id = $1 AND status = 'queued' AND device_id IS NULL FOR UPDATE
`

// Locks a queued message no phone has taken, so dispatch waits while it is canceled.
func (q *Queries) LockUnassignedMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRow(ctx, lockUnassignedMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.DeviceID,
		&i.APIKeyID,
		&i.Recipient,
		&i.Sender,
		&i.Body,
		&i.Segments,
		&i.Attempts,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SendingAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UpdatedAt,
		&i.RequestedDeviceID,
		&i.SimSlot,
		&i.AssignedAt,
		&i.IdempotencyHash,
		&i.BodySha256,
		&i.BodyLength,
		&i.BodyRedactedAt,
		&i.Encoding,
		&i.Purpose,
		&i.DisplayBody,
		&i.ProviderAccountID,
		&i.BodyVars,
	)
	return i, err
}

const messageStats = `-- name: MessageStats :one
SELECT
    count(*)::int                                                      AS total,
    count(*) FILTER (WHERE status = 'delivered')::int                  AS delivered,
    count(*) FILTER (WHERE status = 'sent')::int                       AS sent,
    count(*) FILTER (WHERE status = 'failed')::int                     AS failed,
    count(*) FILTER (WHERE status IN ('created', 'queued', 'sending'))::int AS pending,
    COALESCE(avg(EXTRACT(EPOCH FROM (sent_at - created_at))) FILTER (WHERE sent_at IS NOT NULL), 0)::float8 AS avg_send_seconds
FROM messages
WHERE project_id = $1 AND environment = $2 AND direction = 'outbound' AND created_at >= $3
`

type MessageStatsParams struct {
	ProjectID   string
	Environment APIEnvironment
	Since       time.Time
}

type MessageStatsRow struct {
	Total          int32
	Delivered      int32
	Sent           int32
	Failed         int32
	Pending        int32
	AvgSendSeconds float64
}

func (q *Queries) MessageStats(ctx context.Context, arg MessageStatsParams) (MessageStatsRow, error) {
	row := q.db.QueryRow(ctx, messageStats, arg.ProjectID, arg.Environment, arg.Since)
	var i MessageStatsRow
	err := row.Scan(
		&i.Total,
		&i.Delivered,
		&i.Sent,
		&i.Failed,
		&i.Pending,
		&i.AvgSendSeconds,
	)
	return i, err
}

const pendingForDevice = `-- name: PendingForDevice :many
SELECT id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars FROM messages
WHERE device_id = $1 AND status IN ('queued', 'sending')
ORDER BY created_at
LIMIT 100
`

func (q *Queries) PendingForDevice(ctx context.Context, deviceID *string) ([]Message, error) {
	rows, err := q.db.Query(ctx, pendingForDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Environment,
			&i.Direction,
			&i.Status,
			&i.Provider,
			&i.DeviceID,
			&i.APIKeyID,
			&i.Recipient,
			&i.Sender,
			&i.Body,
			&i.Segments,
			&i.Attempts,
			&i.ProviderMessageID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.QueuedAt,
			&i.SendingAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.UpdatedAt,
			&i.RequestedDeviceID,
			&i.SimSlot,
			&i.AssignedAt,
			&i.IdempotencyHash,
			&i.BodySha256,
			&i.BodyLength,
			&i.BodyRedactedAt,
			&i.Encoding,
			&i.Purpose,
			&i.DisplayBody,
			&i.ProviderAccountID,
			&i.BodyVars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redactMessageBodies = `-- name: RedactMessageBodies :execrows
UPDATE messages SET body = '', body_vars = NULL, body_redacted_at = now(), updated_at = now()
WHERE body_redacted_at IS NULL
  AND (created_at < $1
       -- OTP bodies contain the code. A Verify code's message is kept until its
       -- verification finishes (which redacts it) or the longest code lifetime has
       -- passed, so it can be resent through another route; codes delivered for
       -- other systems go as soon as the phone is done with them.
       OR (purpose = 'otp' AND (created_at < $2 OR NOT (metadata ? 'otp_id'))))
  AND status IN ('sent', 'delivered', 'failed', 'received')
`

type RedactMessageBodiesParams struct {
	Before    time.Time
	OtpBefore time.Time
}

func (q *Queries) RedactMessageBodies(ctx context.Context, arg RedactMessageBodiesParams) (int64, error) {
	result, err := q.db.Exec(ctx, redactMessageBodies, arg.Before, arg.OtpBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseMessage = `-- name: ReleaseMessage :one
UPDATE messages SET device_id = NULL, assigned_at = NULL, updated_at = now()
WHERE id = $1 AND status = 'queued' AND device_id = $2
RETURNING id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars
`

type ReleaseMessageParams struct {
	ID       string
	DeviceID *string
}

// Takes a queued message back from a device that did not accept it in time.
func (q *Queries) ReleaseMessage(ctx context.Context, arg ReleaseMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, releaseMessage, arg.ID, arg.DeviceID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.DeviceID,
		&i.APIKeyID,
		&i.Recipient,
		&i.Sender,
		&i.Body,
		&i.Segments,
		&i.Attempts,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SendingAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UpdatedAt,
		&i.RequestedDeviceID,
		&i.SimSlot,
		&i.AssignedAt,
		&i.IdempotencyHash,
		&i.BodySha256,
		&i.BodyLength,
		&i.BodyRedactedAt,
		&i.Encoding,
		&i.Purpose,
		&i.DisplayBody,
		&i.ProviderAccountID,
		&i.BodyVars,
	)
	return i, err
}

const staleAssignments = `-- name: StaleAssignments :many
SELECT id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars FROM messages
WHERE status = 'queued' AND device_id IS NOT NULL AND assigned_at < $1
ORDER BY assigned_at
LIMIT 200
`

func (q *Queries) StaleAssignments(ctx context.Context, before *time.Time) ([]Message, error) {
	rows, err := q.db.Query(ctx, staleAssignments, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Environment,
			&i.Direction,
			&i.Status,
			&i.Provider,
			&i.DeviceID,
			&i.APIKeyID,
			&i.Recipient,
			&i.Sender,
			&i.Body,
			&i.Segments,
			&i.Attempts,
			&i.ProviderMessageID,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.QueuedAt,
			&i.SendingAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.UpdatedAt,
			&i.RequestedDeviceID,
			&i.SimSlot,
			&i.AssignedAt,
			&i.IdempotencyHash,
			&i.BodySha256,
			&i.BodyLength,
			&i.BodyRedactedAt,
			&i.Encoding,
			&i.Purpose,
			&i.DisplayBody,
			&i.ProviderAccountID,
			&i.BodyVars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const transitionMessage = `-- name: TransitionMessage :one
UPDATE messages SET
    status        = $1::message_status,
    sending_at    = CASE WHEN $1::message_status = 'sending'   THEN now() ELSE sending_at END,
    sent_at       = CASE WHEN $1::message_status = 'sent'      THEN now() ELSE sent_at END,
    delivered_at  = CASE WHEN $1::message_status = 'delivered' THEN now() ELSE delivered_at END,
    failed_at     = CASE WHEN $1::message_status = 'failed'    THEN now() ELSE failed_at END,
    queued_at     = CASE WHEN $1::message_status = 'queued'    THEN now() ELSE queued_at END,
    error_code    = CASE WHEN $1::message_status = 'failed'    THEN $2::text ELSE error_code END,
    error_message = CASE WHEN $1::message_status = 'failed'    THEN $3::text ELSE error_message END,
    segments      = COALESCE($4::smallint, segments),
    -- Returning to the queue releases the device assignment.
    device_id     = CASE WHEN $1::message_status = 'queued' THEN NULL ELSE device_id END,
    assigned_at   = CASE WHEN $1::message_status = 'queued' THEN NULL ELSE assigned_at END,
    updated_at    = now()
WHERE id = $5 AND status::text = ANY($6::text[])
RETURNING id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars
`

type TransitionMessageParams struct {
	ToStatus     MessageStatus
	ErrorCode    *string
	ErrorMessage *string
	Segments     *int16
	ID           string
	FromStatuses []string
}

// Moves a message to @to_status only from one of @from_statuses. The single
// place statuses change; callers validate the transition first.
func (q *Queries) TransitionMessage(ctx context.Context, arg TransitionMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, transitionMessage,
		arg.ToStatus,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Segments,
		arg.ID,
		arg.FromStatuses,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.DeviceID,
		&i.APIKeyID,
		&i.Recipient,
		&i.Sender,
		&i.Body,
		&i.Segments,
		&i.Attempts,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SendingAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UpdatedAt,
		&i.RequestedDeviceID,
		&i.SimSlot,
		&i.AssignedAt,
		&i.IdempotencyHash,
		&i.BodySha256,
		&i.BodyLength,
		&i.BodyRedactedAt,
		&i.Encoding,
		&i.Purpose,
		&i.DisplayBody,
		&i.ProviderAccountID,
		&i.BodyVars,
	)
	return i, err
}

const updateDeviceSettings = `-- name: UpdateDeviceSettings :one
UPDATE devices SET
    name = COALESCE($1::text, name),
    preferred_sim_slot = CASE WHEN $2::bool THEN $3::smallint ELSE preferred_sim_slot END,
    send_limit_count = COALESCE($4::int, send_limit_count),
    forward_inbound = COALESCE($5::bool, forward_inbound),
    updated_at = now()
WHERE id = $6 AND project_id = $7
RETURNING id, project_id, name, installation_id, credential_hash, status, last_heartbeat_at, last_seen_at, battery_level, is_charging, network_type, carrier_name, sim_count, device_model, android_version, app_version, created_at, updated_at, revoked_at, push_provider, push_endpoint, push_p256dh, push_auth, push_updated_at, connection_id, connected_at, heartbeat_interval, app_flavor, preferred_sim_slot, send_limit_count, send_limit_window_seconds, sims, forward_inbound, notified_presence
`

type UpdateDeviceSettingsParams struct {
	Name             *string
	SetSim           bool
	PreferredSimSlot *int16
	SendLimitCount   *int32
	ForwardInbound   *bool
	ID               string
	ProjectID        string
}

func (q *Queries) UpdateDeviceSettings(ctx context.Context, arg UpdateDeviceSettingsParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDeviceSettings,
		arg.Name,
		arg.SetSim,
		arg.PreferredSimSlot,
		arg.SendLimitCount,
		arg.ForwardInbound,
		arg.ID,
		arg.ProjectID,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.InstallationID,
		&i.CredentialHash,
		&i.Status,
		&i.LastHeartbeatAt,
		&i.LastSeenAt,
		&i.BatteryLevel,
		&i.IsCharging,
		&i.NetworkType,
		&i.CarrierName,
		&i.SimCount,
		&i.DeviceModel,
		&i.AndroidVersion,
		&i.AppVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
		&i.PushProvider,
		&i.PushEndpoint,
		&i.PushP256dh,
		&i.PushAuth,
		&i.PushUpdatedAt,
		&i.ConnectionID,
		&i.ConnectedAt,
		&i.HeartbeatInterval,
		&i.AppFlavor,
		&i.PreferredSimSlot,
		&i.SendLimitCount,
		&i.SendLimitWindowSeconds,
		&i.Sims,
		&i.ForwardInbound,
		&i.NotifiedPresence,
	)
	return i, err
}

const updateDeviceSims = `-- name: UpdateDeviceSims :exec
UPDATE devices SET sims = $2, updated_at = now() WHERE id = $1
`

type UpdateDeviceSimsParams struct {
	ID   string
	Sims json.RawMessage
}

func (q *Queries) UpdateDeviceSims(ctx context.Context, arg UpdateDeviceSimsParams) error {
	_, err := q.db.Exec(ctx, updateDeviceSims, arg.ID, arg.Sims)
	return err
}

const waitingMessages = `-- name: WaitingMessages :many
SELECT id FROM messages
WHERE project_id = $1 AND status = 'queued' AND device_id IS NULL AND provider = 'android'
ORDER BY created_at
LIMIT 100
`

// Queued messages not yet assigned to a phone.
func (q *Queries) WaitingMessages(ctx context.Context, projectID string) ([]string, error) {
	rows, err := q.db.Query(ctx, waitingMessages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
