// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"
	"time"
)

type APIEnvironment string

const (
	ApiEnvironmentLive APIEnvironment = "live"
	ApiEnvironmentTest APIEnvironment = "test"
)

func (e *APIEnvironment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = APIEnvironment(s)
	case string:
		*e = APIEnvironment(s)
	default:
		return fmt.Errorf("unsupported scan type for APIEnvironment: %T", src)
	}
	return nil
}

type NullAPIEnvironment struct {
	APIEnvironment APIEnvironment
	Valid          bool // Valid is true if APIEnvironment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAPIEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.APIEnvironment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.APIEnvironment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAPIEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.APIEnvironment), nil
}

type DeviceStatus string

const (
	DeviceStatusOnline   DeviceStatus = "online"
	DeviceStatusOffline  DeviceStatus = "offline"
	DeviceStatusDisabled DeviceStatus = "disabled"
)

func (e *DeviceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeviceStatus(s)
	case string:
		*e = DeviceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeviceStatus: %T", src)
	}
	return nil
}

type NullDeviceStatus struct {
	DeviceStatus DeviceStatus
	Valid        bool // Valid is true if DeviceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeviceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeviceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeviceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeviceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeviceStatus), nil
}

type MemberRole string

const (
	MemberRoleOwner  MemberRole = "owner"
	MemberRoleAdmin  MemberRole = "admin"
	MemberRoleMember MemberRole = "member"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole
	Valid      bool // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type MessageDirection string

const (
	MessageDirectionOutbound MessageDirection = "outbound"
	MessageDirectionInbound  MessageDirection = "inbound"
)

func (e *MessageDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageDirection(s)
	case string:
		*e = MessageDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageDirection: %T", src)
	}
	return nil
}

type NullMessageDirection struct {
	MessageDirection MessageDirection
	Valid            bool // Valid is true if MessageDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageDirection) Scan(value interface{}) error {
	if value == nil {
		ns.MessageDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageDirection), nil
}

type MessageStatus string

const (
	MessageStatusCreated   MessageStatus = "created"
	MessageStatusQueued    MessageStatus = "queued"
	MessageStatusSending   MessageStatus = "sending"
	MessageStatusSent      MessageStatus = "sent"
	MessageStatusDelivered MessageStatus = "delivered"
	MessageStatusFailed    MessageStatus = "failed"
	MessageStatusReceived  MessageStatus = "received"
)

func (e *MessageStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageStatus(s)
	case string:
		*e = MessageStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageStatus: %T", src)
	}
	return nil
}

type NullMessageStatus struct {
	MessageStatus MessageStatus
	Valid         bool // Valid is true if MessageStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MessageStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageStatus), nil
}

type APIKey struct {
	ID          string
	ProjectID   string
	Name        string
	Environment APIEnvironment
	KeyPrefix   string
	KeyHash     []byte
	CreatedBy   *string
	LastUsedAt  *time.Time
	ExpiresAt   *time.Time
	RevokedAt   *time.Time
	CreatedAt   time.Time
}

type APIRequestLog struct {
	ID          string
	RequestID   string
	ProjectID   string
	APIKeyID    *string
	Environment string
	Method      string
	Path        string
	Status      int32
	ErrorCode   *string
	DurationMs  int32
	IP          *netip.Addr
	UserAgent   *string
	ResourceID  *string
	CreatedAt   time.Time
}

type AuditLog struct {
	ID             string
	OrganizationID string
	ProjectID      *string
	ActorType      string
	ActorID        *string
	Action         string
	TargetType     *string
	TargetID       *string
	Metadata       json.RawMessage
	IP             *netip.Addr
	CreatedAt      time.Time
}

type Device struct {
	ID                     string
	ProjectID              string
	Name                   string
	InstallationID         string
	CredentialHash         []byte
	Status                 DeviceStatus
	LastHeartbeatAt        *time.Time
	LastSeenAt             *time.Time
	BatteryLevel           *int16
	IsCharging             *bool
	NetworkType            *string
	CarrierName            *string
	SimCount               *int16
	DeviceModel            *string
	AndroidVersion         *string
	AppVersion             *string
	CreatedAt              time.Time
	UpdatedAt              time.Time
	RevokedAt              *time.Time
	PushProvider           *string
	PushEndpoint           *string
	PushP256dh             *string
	PushAuth               *string
	PushUpdatedAt          *time.Time
	ConnectionID           *string
	ConnectedAt            *time.Time
	HeartbeatInterval      int32
	AppFlavor              *string
	PreferredSimSlot       *int16
	SendLimitCount         int32
	SendLimitWindowSeconds int32
	Sims                   json.RawMessage
	ForwardInbound         bool
	NotifiedPresence       *string
}

type DevicePairingToken struct {
	ID        string
	ProjectID string
	TokenHash []byte
	CreatedBy *string
	DeviceID  *string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type InstanceHeartbeat struct {
	InstanceID string
	Kind       string
	Version    string
	Hostname   string
	StartedAt  time.Time
	SeenAt     time.Time
}

type Message struct {
	ID                string
	ProjectID         string
	Environment       APIEnvironment
	Direction         MessageDirection
	Status            MessageStatus
	Provider          string
	DeviceID          *string
	APIKeyID          *string
	Recipient         string
	Sender            *string
	Body              string
	Segments          *int16
	Attempts          int32
	ProviderMessageID *string
	ErrorCode         *string
	ErrorMessage      *string
	Metadata          json.RawMessage
	IdempotencyKey    *string
	CreatedAt         time.Time
	QueuedAt          *time.Time
	SendingAt         *time.Time
	SentAt            *time.Time
	DeliveredAt       *time.Time
	FailedAt          *time.Time
	UpdatedAt         time.Time
	RequestedDeviceID *string
	SimSlot           *int16
	AssignedAt        *time.Time
	IdempotencyHash   []byte
	BodySha256        []byte
	BodyLength        *int32
	BodyRedactedAt    *time.Time
	Encoding          *string
}

type MessageEvent struct {
	ID         string
	MessageID  string
	ProjectID  string
	Type       string
	FromStatus *MessageStatus
	ToStatus   *MessageStatus
	Detail     json.RawMessage
	CreatedAt  time.Time
}

type Organization struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type OrganizationInvite struct {
	ID             string
	OrganizationID string
	TokenHash      []byte
	Role           MemberRole
	Email          string
	InvitedBy      *string
	ExpiresAt      time.Time
	AcceptedAt     *time.Time
	AcceptedBy     *string
	RevokedAt      *time.Time
	CreatedAt      time.Time
}

type OrganizationMember struct {
	ID             string
	OrganizationID string
	UserID         string
	Role           MemberRole
	CreatedAt      time.Time
}

type Project struct {
	ID             string
	OrganizationID string
	Name           string
	Slug           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RateLimitCounter struct {
	Key         string
	WindowStart time.Time
	Count       int32
}

type ServerKey struct {
	Name       string
	PrivateKey []byte
	CreatedAt  time.Time
}

type Session struct {
	ID         string
	UserID     string
	TokenHash  []byte
	IP         *netip.Addr
	UserAgent  string
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

type StatusSample struct {
	Component string
	SampledAt time.Time
	Status    string
	Value     *float64
	Detail    string
}

type User struct {
	ID              string
	Email           string
	Name            string
	PasswordHash    string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type WebhookDelivery struct {
	ID             string
	EndpointID     string
	EventID        string
	Attempt        int32
	Succeeded      bool
	ResponseStatus *int32
	ResponseBody   *string
	Error          *string
	DurationMs     int32
	CreatedAt      time.Time
}

type WebhookEndpoint struct {
	ID             string
	ProjectID      string
	URL            string
	Description    string
	Events         []string
	Secret         string
	Enabled        bool
	DisabledReason *string
	FailingSince   *time.Time
	LastSuccessAt  *time.Time
	LastFailureAt  *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type WebhookEvent struct {
	ID        string
	ProjectID string
	Type      string
	Payload   json.RawMessage
	CreatedAt time.Time
}
