// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package dbq

import (
	"context"
	"time"
)

const addOrganizationMember = `-- name: AddOrganizationMember :one
INSERT INTO organization_members (id, organization_id, user_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, user_id, role, created_at
`

type AddOrganizationMemberParams struct {
	ID             string
	OrganizationID string
	UserID         string
	Role           MemberRole
}

func (q *Queries) AddOrganizationMember(ctx context.Context, arg AddOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, addOrganizationMember,
		arg.ID,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, name, slug)
VALUES ($1, $2, $3)
RETURNING id, name, slug, created_at, updated_at
`

type CreateOrganizationParams struct {
	ID   string
	Name string
	Slug string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationForUser = `-- name: GetOrganizationForUser :one
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at, m.role
FROM organizations o
JOIN organization_members m ON m.organization_id = o.id
WHERE o.id = $1 AND m.user_id = $2
`

type GetOrganizationForUserParams struct {
	OrganizationID string
	UserID         string
}

type GetOrganizationForUserRow struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Role      MemberRole
}

func (q *Queries) GetOrganizationForUser(ctx context.Context, arg GetOrganizationForUserParams) (GetOrganizationForUserRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationForUser, arg.OrganizationID, arg.UserID)
	var i GetOrganizationForUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.name, o.slug, o.created_at, o.updated_at, m.role
FROM organizations o
JOIN organization_members m ON m.organization_id = o.id
WHERE m.user_id = $1
ORDER BY o.created_at, o.id
`

type ListOrganizationsForUserRow struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Role      MemberRole
}

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID string) ([]ListOrganizationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsForUserRow{}
	for rows.Next() {
		var i ListOrganizationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationSlugExists = `-- name: OrganizationSlugExists :one
SELECT EXISTS (SELECT 1 FROM organizations WHERE slug = $1)
`

func (q *Queries) OrganizationSlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, organizationSlugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
