// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const cancelPendingOTPs = `-- name: CancelPendingOTPs :exec
UPDATE otp_verifications SET status = 'canceled', code_hash = NULL, updated_at = now()
WHERE project_id = $1 AND environment = $2 AND recipient = $3 AND status = 'pending'
`

type CancelPendingOTPsParams struct {
	ProjectID   string
	Environment APIEnvironment
	Recipient   string
}

// A new code replaces any code still pending for the same number.
func (q *Queries) CancelPendingOTPs(ctx context.Context, arg CancelPendingOTPsParams) error {
	_, err := q.db.Exec(ctx, cancelPendingOTPs, arg.ProjectID, arg.Environment, arg.Recipient)
	return err
}

const deleteOldOTPs = `-- name: DeleteOldOTPs :execrows
DELETE FROM otp_verifications WHERE created_at < $1
`

func (q *Queries) DeleteOldOTPs(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldOTPs, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireOTP = `-- name: ExpireOTP :one
UPDATE otp_verifications SET status = 'expired', code_hash = NULL, updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, project_id, environment, api_key_id, recipient, status, code_hash, test_code, code_length, attempts, max_attempts, message_id, metadata, expires_at, verified_at, created_at, updated_at
`

func (q *Queries) ExpireOTP(ctx context.Context, id string) (OtpVerification, error) {
	row := q.db.QueryRow(ctx, expireOTP, id)
	var i OtpVerification
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.APIKeyID,
		&i.Recipient,
		&i.Status,
		&i.CodeHash,
		&i.TestCode,
		&i.CodeLength,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MessageID,
		&i.Metadata,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const expireOTPs = `-- name: ExpireOTPs :many
UPDATE otp_verifications SET status = 'expired', code_hash = NULL, updated_at = now()
WHERE status = 'pending' AND expires_at < now()
RETURNING id, project_id, environment, api_key_id, recipient, status, code_hash, test_code, code_length, attempts, max_attempts, message_id, metadata, expires_at, verified_at, created_at, updated_at
`

func (q *Queries) ExpireOTPs(ctx context.Context) ([]OtpVerification, error) {
	rows, err := q.db.Query(ctx, expireOTPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OtpVerification{}
	for rows.Next() {
		var i OtpVerification
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Environment,
			&i.APIKeyID,
			&i.Recipient,
			&i.Status,
			&i.CodeHash,
			&i.TestCode,
			&i.CodeLength,
			&i.Attempts,
			&i.MaxAttempts,
			&i.MessageID,
			&i.Metadata,
			&i.ExpiresAt,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishOTPAttempt = `-- name: FinishOTPAttempt :one
UPDATE otp_verifications SET
    status      = $1,
    attempts    = attempts + 1,
    verified_at = CASE WHEN $1::otp_status = 'verified' THEN now() ELSE verified_at END,
    code_hash   = CASE WHEN $1::otp_status = 'pending' THEN code_hash ELSE NULL END,
    updated_at  = now()
WHERE id = $2
RETURNING id, project_id, environment, api_key_id, recipient, status, code_hash, test_code, code_length, attempts, max_attempts, message_id, metadata, expires_at, verified_at, created_at, updated_at
`

type FinishOTPAttemptParams struct {
	Status OtpStatus
	ID     string
}

// Records one verification attempt. Once the verification leaves 'pending',
// the code hash is erased.
func (q *Queries) FinishOTPAttempt(ctx context.Context, arg FinishOTPAttemptParams) (OtpVerification, error) {
	row := q.db.QueryRow(ctx, finishOTPAttempt, arg.Status, arg.ID)
	var i OtpVerification
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.APIKeyID,
		&i.Recipient,
		&i.Status,
		&i.CodeHash,
		&i.TestCode,
		&i.CodeLength,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MessageID,
		&i.Metadata,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOTPForUpdate = `-- name: GetOTPForUpdate :one
SELECT id, project_id, environment, api_key_id, recipient, status, code_hash, test_code, code_length, attempts, max_attempts, message_id, metadata, expires_at, verified_at, created_at, updated_at FROM otp_verifications
WHERE id = $1 AND project_id = $2 AND environment = $3
FOR UPDATE
`

type GetOTPForUpdateParams struct {
	ID          string
	ProjectID   string
	Environment APIEnvironment
}

func (q *Queries) GetOTPForUpdate(ctx context.Context, arg GetOTPForUpdateParams) (OtpVerification, error) {
	row := q.db.QueryRow(ctx, getOTPForUpdate, arg.ID, arg.ProjectID, arg.Environment)
	var i OtpVerification
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.APIKeyID,
		&i.Recipient,
		&i.Status,
		&i.CodeHash,
		&i.TestCode,
		&i.CodeLength,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MessageID,
		&i.Metadata,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOTPSettings = `-- name: GetOTPSettings :one
SELECT project_id, app_name, template, code_length, ttl_seconds, max_attempts, web_otp_domain, updated_at FROM otp_settings WHERE project_id = $1
`

func (q *Queries) GetOTPSettings(ctx context.Context, projectID string) (OtpSetting, error) {
	row := q.db.QueryRow(ctx, getOTPSettings, projectID)
	var i OtpSetting
	err := row.Scan(
		&i.ProjectID,
		&i.AppName,
		&i.Template,
		&i.CodeLength,
		&i.TtlSeconds,
		&i.MaxAttempts,
		&i.WebOtpDomain,
		&i.UpdatedAt,
	)
	return i, err
}

const getOTPView = `-- name: GetOTPView :one
SELECT o.id, o.project_id, o.environment, o.api_key_id, o.recipient, o.status, o.code_hash, o.test_code, o.code_length, o.attempts, o.max_attempts, o.message_id, o.metadata, o.expires_at, o.verified_at, o.created_at, o.updated_at, m.status AS message_status
FROM otp_verifications o
LEFT JOIN messages m ON m.id = o.message_id
WHERE o.id = $1 AND o.project_id = $2
  AND ($3::api_environment IS NULL OR o.environment = $3)
`

type GetOTPViewParams struct {
	ID          string
	ProjectID   string
	Environment *APIEnvironment
}

type GetOTPViewRow struct {
	ID            string
	ProjectID     string
	Environment   APIEnvironment
	APIKeyID      *string
	Recipient     string
	Status        OtpStatus
	CodeHash      []byte
	TestCode      *string
	CodeLength    int16
	Attempts      int16
	MaxAttempts   int16
	MessageID     *string
	Metadata      json.RawMessage
	ExpiresAt     time.Time
	VerifiedAt    *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	MessageStatus *MessageStatus
}

func (q *Queries) GetOTPView(ctx context.Context, arg GetOTPViewParams) (GetOTPViewRow, error) {
	row := q.db.QueryRow(ctx, getOTPView, arg.ID, arg.ProjectID, arg.Environment)
	var i GetOTPViewRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.APIKeyID,
		&i.Recipient,
		&i.Status,
		&i.CodeHash,
		&i.TestCode,
		&i.CodeLength,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MessageID,
		&i.Metadata,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MessageStatus,
	)
	return i, err
}

const insertOTP = `-- name: InsertOTP :one
INSERT INTO otp_verifications (
    id, project_id, environment, api_key_id, recipient, code_hash, test_code,
    code_length, max_attempts, message_id, metadata, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12
)
RETURNING id, project_id, environment, api_key_id, recipient, status, code_hash, test_code, code_length, attempts, max_attempts, message_id, metadata, expires_at, verified_at, created_at, updated_at
`

type InsertOTPParams struct {
	ID          string
	ProjectID   string
	Environment APIEnvironment
	APIKeyID    *string
	Recipient   string
	CodeHash    []byte
	TestCode    *string
	CodeLength  int16
	MaxAttempts int16
	MessageID   *string
	Metadata    json.RawMessage
	ExpiresAt   time.Time
}

func (q *Queries) InsertOTP(ctx context.Context, arg InsertOTPParams) (OtpVerification, error) {
	row := q.db.QueryRow(ctx, insertOTP,
		arg.ID,
		arg.ProjectID,
		arg.Environment,
		arg.APIKeyID,
		arg.Recipient,
		arg.CodeHash,
		arg.TestCode,
		arg.CodeLength,
		arg.MaxAttempts,
		arg.MessageID,
		arg.Metadata,
		arg.ExpiresAt,
	)
	var i OtpVerification
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.APIKeyID,
		&i.Recipient,
		&i.Status,
		&i.CodeHash,
		&i.TestCode,
		&i.CodeLength,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MessageID,
		&i.Metadata,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestOTPForRecipient = `-- name: LatestOTPForRecipient :one
SELECT id, project_id, environment, api_key_id, recipient, status, code_hash, test_code, code_length, attempts, max_attempts, message_id, metadata, expires_at, verified_at, created_at, updated_at FROM otp_verifications
WHERE project_id = $1 AND environment = $2 AND recipient = $3
ORDER BY created_at DESC, id DESC
LIMIT 1
`

type LatestOTPForRecipientParams struct {
	ProjectID   string
	Environment APIEnvironment
	Recipient   string
}

func (q *Queries) LatestOTPForRecipient(ctx context.Context, arg LatestOTPForRecipientParams) (OtpVerification, error) {
	row := q.db.QueryRow(ctx, latestOTPForRecipient, arg.ProjectID, arg.Environment, arg.Recipient)
	var i OtpVerification
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.APIKeyID,
		&i.Recipient,
		&i.Status,
		&i.CodeHash,
		&i.TestCode,
		&i.CodeLength,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MessageID,
		&i.Metadata,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestPendingOTPForUpdate = `-- name: LatestPendingOTPForUpdate :one
SELECT id, project_id, environment, api_key_id, recipient, status, code_hash, test_code, code_length, attempts, max_attempts, message_id, metadata, expires_at, verified_at, created_at, updated_at FROM otp_verifications
WHERE project_id = $1 AND environment = $2 AND recipient = $3 AND status = 'pending'
ORDER BY created_at DESC, id DESC
LIMIT 1
FOR UPDATE
`

type LatestPendingOTPForUpdateParams struct {
	ProjectID   string
	Environment APIEnvironment
	Recipient   string
}

func (q *Queries) LatestPendingOTPForUpdate(ctx context.Context, arg LatestPendingOTPForUpdateParams) (OtpVerification, error) {
	row := q.db.QueryRow(ctx, latestPendingOTPForUpdate, arg.ProjectID, arg.Environment, arg.Recipient)
	var i OtpVerification
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.APIKeyID,
		&i.Recipient,
		&i.Status,
		&i.CodeHash,
		&i.TestCode,
		&i.CodeLength,
		&i.Attempts,
		&i.MaxAttempts,
		&i.MessageID,
		&i.Metadata,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOTPViews = `-- name: ListOTPViews :many
SELECT o.id, o.project_id, o.environment, o.api_key_id, o.recipient, o.status, o.code_hash, o.test_code, o.code_length, o.attempts, o.max_attempts, o.message_id, o.metadata, o.expires_at, o.verified_at, o.created_at, o.updated_at, m.status AS message_status
FROM otp_verifications o
LEFT JOIN messages m ON m.id = o.message_id
WHERE o.project_id = $1
  AND ($2::api_environment IS NULL OR o.environment = $2)
  AND ($3::otp_status IS NULL OR o.status = $3)
  AND ($4::text IS NULL OR o.recipient = $4)
  AND ($5::timestamptz IS NULL
       OR (o.created_at, o.id) < ($5::timestamptz, $6::text))
ORDER BY o.created_at DESC, o.id DESC
LIMIT $7
`

type ListOTPViewsParams struct {
	ProjectID     string
	Environment   *APIEnvironment
	Status        *OtpStatus
	Recipient     *string
	BeforeCreated *time.Time
	BeforeID      *string
	RowLimit      int32
}

type ListOTPViewsRow struct {
	ID            string
	ProjectID     string
	Environment   APIEnvironment
	APIKeyID      *string
	Recipient     string
	Status        OtpStatus
	CodeHash      []byte
	TestCode      *string
	CodeLength    int16
	Attempts      int16
	MaxAttempts   int16
	MessageID     *string
	Metadata      json.RawMessage
	ExpiresAt     time.Time
	VerifiedAt    *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
	MessageStatus *MessageStatus
}

func (q *Queries) ListOTPViews(ctx context.Context, arg ListOTPViewsParams) ([]ListOTPViewsRow, error) {
	rows, err := q.db.Query(ctx, listOTPViews,
		arg.ProjectID,
		arg.Environment,
		arg.Status,
		arg.Recipient,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOTPViewsRow{}
	for rows.Next() {
		var i ListOTPViewsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Environment,
			&i.APIKeyID,
			&i.Recipient,
			&i.Status,
			&i.CodeHash,
			&i.TestCode,
			&i.CodeLength,
			&i.Attempts,
			&i.MaxAttempts,
			&i.MessageID,
			&i.Metadata,
			&i.ExpiresAt,
			&i.VerifiedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MessageStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oTPStats = `-- name: OTPStats :one
SELECT count(*)::int                                     AS total,
       count(*) FILTER (WHERE status = 'verified')::int AS verified,
       count(*) FILTER (WHERE status = 'pending')::int  AS pending,
       count(*) FILTER (WHERE status = 'expired')::int  AS expired,
       count(*) FILTER (WHERE status = 'failed')::int   AS failed,
       count(*) FILTER (WHERE status = 'canceled')::int AS canceled,
       COALESCE(percentile_cont(0.5) WITHIN GROUP (ORDER BY extract(epoch FROM verified_at - created_at))
                FILTER (WHERE status = 'verified'), 0)::float8 AS median_seconds_to_verify
FROM otp_verifications
WHERE project_id = $1 AND environment = $2 AND created_at >= $3
`

type OTPStatsParams struct {
	ProjectID   string
	Environment APIEnvironment
	Since       time.Time
}

type OTPStatsRow struct {
	Total                 int32
	Verified              int32
	Pending               int32
	Expired               int32
	Failed                int32
	Canceled              int32
	MedianSecondsToVerify float64
}

func (q *Queries) OTPStats(ctx context.Context, arg OTPStatsParams) (OTPStatsRow, error) {
	row := q.db.QueryRow(ctx, oTPStats, arg.ProjectID, arg.Environment, arg.Since)
	var i OTPStatsRow
	err := row.Scan(
		&i.Total,
		&i.Verified,
		&i.Pending,
		&i.Expired,
		&i.Failed,
		&i.Canceled,
		&i.MedianSecondsToVerify,
	)
	return i, err
}

const redactMessage = `-- name: RedactMessage :exec
UPDATE messages SET body = '', body_redacted_at = now(), updated_at = now()
WHERE id = $1 AND body_redacted_at IS NULL AND status IN ('sent', 'delivered', 'failed')
`

// Erases an OTP message's body once it has left the phone.
func (q *Queries) RedactMessage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, redactMessage, id)
	return err
}

const upsertOTPSettings = `-- name: UpsertOTPSettings :one
INSERT INTO otp_settings (project_id, app_name, template, code_length, ttl_seconds, max_attempts, web_otp_domain)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (project_id) DO UPDATE SET
    app_name       = EXCLUDED.app_name,
    template       = EXCLUDED.template,
    code_length    = EXCLUDED.code_length,
    ttl_seconds    = EXCLUDED.ttl_seconds,
    max_attempts   = EXCLUDED.max_attempts,
    web_otp_domain = EXCLUDED.web_otp_domain,
    updated_at     = now()
RETURNING project_id, app_name, template, code_length, ttl_seconds, max_attempts, web_otp_domain, updated_at
`

type UpsertOTPSettingsParams struct {
	ProjectID    string
	AppName      *string
	Template     *string
	CodeLength   int16
	TtlSeconds   int32
	MaxAttempts  int16
	WebOtpDomain *string
}

func (q *Queries) UpsertOTPSettings(ctx context.Context, arg UpsertOTPSettingsParams) (OtpSetting, error) {
	row := q.db.QueryRow(ctx, upsertOTPSettings,
		arg.ProjectID,
		arg.AppName,
		arg.Template,
		arg.CodeLength,
		arg.TtlSeconds,
		arg.MaxAttempts,
		arg.WebOtpDomain,
	)
	var i OtpSetting
	err := row.Scan(
		&i.ProjectID,
		&i.AppName,
		&i.Template,
		&i.CodeLength,
		&i.TtlSeconds,
		&i.MaxAttempts,
		&i.WebOtpDomain,
		&i.UpdatedAt,
	)
	return i, err
}
