// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_resets.sql

package dbq

import (
	"context"
	"time"
)

const claimPasswordReset = `-- name: ClaimPasswordReset :one
UPDATE password_resets SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

// Uses the link once, in the transaction that sets the new password.
func (q *Queries) ClaimPasswordReset(ctx context.Context, tokenHash []byte) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, claimPasswordReset, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetParams struct {
	ID        string
	UserID    string
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const expirePasswordResets = `-- name: ExpirePasswordResets :exec
UPDATE password_resets SET used_at = now() WHERE user_id = $1 AND used_at IS NULL
`

// A new password makes every other open link for the user useless.
func (q *Queries) ExpirePasswordResets(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, expirePasswordResets, userID)
	return err
}
