// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbq

import (
	"context"
	"time"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, organization_id, name, slug)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, name, slug, created_at, updated_at
`

type CreateProjectParams struct {
	ID             string
	OrganizationID string
	Name           string
	Slug           string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ID,
		arg.OrganizationID,
		arg.Name,
		arg.Slug,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, organization_id, name, slug, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectForUser = `-- name: GetProjectForUser :one
SELECT p.id, p.organization_id, p.name, p.slug, p.created_at, p.updated_at, m.role
FROM projects p
JOIN organization_members m ON m.organization_id = p.organization_id
WHERE p.id = $1 AND m.user_id = $2
`

type GetProjectForUserParams struct {
	ProjectID string
	UserID    string
}

type GetProjectForUserRow struct {
	ID             string
	OrganizationID string
	Name           string
	Slug           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Role           MemberRole
}

func (q *Queries) GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (GetProjectForUserRow, error) {
	row := q.db.QueryRow(ctx, getProjectForUser, arg.ProjectID, arg.UserID)
	var i GetProjectForUserRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, organization_id, name, slug, created_at, updated_at FROM projects WHERE organization_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListProjects(ctx context.Context, organizationID string) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectSlugExists = `-- name: ProjectSlugExists :one
SELECT EXISTS (SELECT 1 FROM projects WHERE organization_id = $1 AND slug = $2)
`

type ProjectSlugExistsParams struct {
	OrganizationID string
	Slug           string
}

func (q *Queries) ProjectSlugExists(ctx context.Context, arg ProjectSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, projectSlugExists, arg.OrganizationID, arg.Slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProjectName = `-- name: UpdateProjectName :one
UPDATE projects SET name = $1, updated_at = now()
WHERE id = $2
RETURNING id, organization_id, name, slug, created_at, updated_at
`

type UpdateProjectNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectName, arg.Name, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
