// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package dbq

import (
	"context"
	"encoding/json"
)

const deleteProviderAccount = `-- name: DeleteProviderAccount :execrows
DELETE FROM provider_accounts WHERE id = $1 AND project_id = $2
`

type DeleteProviderAccountParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) DeleteProviderAccount(ctx context.Context, arg DeleteProviderAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderAccount, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enabledProviderAccounts = `-- name: EnabledProviderAccounts :many
SELECT id, project_id, kind, name, enabled, priority, credentials, config, credential_hint, callback_token, last_used_at, last_error, created_at, updated_at FROM provider_accounts WHERE project_id = $1 AND enabled ORDER BY priority, created_at
`

func (q *Queries) EnabledProviderAccounts(ctx context.Context, projectID string) ([]ProviderAccount, error) {
	rows, err := q.db.Query(ctx, enabledProviderAccounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderAccount{}
	for rows.Next() {
		var i ProviderAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.Priority,
			&i.Credentials,
			&i.Config,
			&i.CredentialHint,
			&i.CallbackToken,
			&i.LastUsedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByProviderID = `-- name: GetMessageByProviderID :one
SELECT id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars FROM messages WHERE provider_account_id = $1 AND provider_message_id = $2
`

type GetMessageByProviderIDParams struct {
	ProviderAccountID *string
	ProviderMessageID *string
}

func (q *Queries) GetMessageByProviderID(ctx context.Context, arg GetMessageByProviderIDParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByProviderID, arg.ProviderAccountID, arg.ProviderMessageID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.DeviceID,
		&i.APIKeyID,
		&i.Recipient,
		&i.Sender,
		&i.Body,
		&i.Segments,
		&i.Attempts,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SendingAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UpdatedAt,
		&i.RequestedDeviceID,
		&i.SimSlot,
		&i.AssignedAt,
		&i.IdempotencyHash,
		&i.BodySha256,
		&i.BodyLength,
		&i.BodyRedactedAt,
		&i.Encoding,
		&i.Purpose,
		&i.DisplayBody,
		&i.ProviderAccountID,
		&i.BodyVars,
	)
	return i, err
}

const getProviderAccount = `-- name: GetProviderAccount :one
SELECT id, project_id, kind, name, enabled, priority, credentials, config, credential_hint, callback_token, last_used_at, last_error, created_at, updated_at FROM provider_accounts WHERE id = $1 AND project_id = $2
`

type GetProviderAccountParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetProviderAccount(ctx context.Context, arg GetProviderAccountParams) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, getProviderAccount, arg.ID, arg.ProjectID)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.Credentials,
		&i.Config,
		&i.CredentialHint,
		&i.CallbackToken,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderAccountByID = `-- name: GetProviderAccountByID :one
SELECT id, project_id, kind, name, enabled, priority, credentials, config, credential_hint, callback_token, last_used_at, last_error, created_at, updated_at FROM provider_accounts WHERE id = $1
`

func (q *Queries) GetProviderAccountByID(ctx context.Context, id string) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, getProviderAccountByID, id)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.Credentials,
		&i.Config,
		&i.CredentialHint,
		&i.CallbackToken,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRouting = `-- name: GetRouting :one
SELECT project_id, mode, fallback_after_seconds, updated_at FROM project_routing WHERE project_id = $1
`

func (q *Queries) GetRouting(ctx context.Context, projectID string) (ProjectRouting, error) {
	row := q.db.QueryRow(ctx, getRouting, projectID)
	var i ProjectRouting
	err := row.Scan(
		&i.ProjectID,
		&i.Mode,
		&i.FallbackAfterSeconds,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProviderAccount = `-- name: InsertProviderAccount :one
INSERT INTO provider_accounts (id, project_id, kind, name, priority, credentials, config, credential_hint, callback_token)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, kind, name, enabled, priority, credentials, config, credential_hint, callback_token, last_used_at, last_error, created_at, updated_at
`

type InsertProviderAccountParams struct {
	ID             string
	ProjectID      string
	Kind           string
	Name           string
	Priority       int32
	Credentials    []byte
	Config         json.RawMessage
	CredentialHint string
	CallbackToken  string
}

func (q *Queries) InsertProviderAccount(ctx context.Context, arg InsertProviderAccountParams) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, insertProviderAccount,
		arg.ID,
		arg.ProjectID,
		arg.Kind,
		arg.Name,
		arg.Priority,
		arg.Credentials,
		arg.Config,
		arg.CredentialHint,
		arg.CallbackToken,
	)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.Credentials,
		&i.Config,
		&i.CredentialHint,
		&i.CallbackToken,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderAccounts = `-- name: ListProviderAccounts :many
SELECT id, project_id, kind, name, enabled, priority, credentials, config, credential_hint, callback_token, last_used_at, last_error, created_at, updated_at FROM provider_accounts WHERE project_id = $1 ORDER BY priority, created_at
`

func (q *Queries) ListProviderAccounts(ctx context.Context, projectID string) ([]ProviderAccount, error) {
	rows, err := q.db.Query(ctx, listProviderAccounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderAccount{}
	for rows.Next() {
		var i ProviderAccount
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Name,
			&i.Enabled,
			&i.Priority,
			&i.Credentials,
			&i.Config,
			&i.CredentialHint,
			&i.CallbackToken,
			&i.LastUsedAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordProviderResult = `-- name: RecordProviderResult :exec
UPDATE provider_accounts SET
    last_used_at = CASE WHEN $1::text IS NULL THEN now() ELSE last_used_at END,
    last_error   = $1,
    updated_at   = now()
WHERE id = $2
`

type RecordProviderResultParams struct {
	Error *string
	ID    string
}

func (q *Queries) RecordProviderResult(ctx context.Context, arg RecordProviderResultParams) error {
	_, err := q.db.Exec(ctx, recordProviderResult, arg.Error, arg.ID)
	return err
}

const setMessageProvider = `-- name: SetMessageProvider :one
UPDATE messages SET
    provider            = $1,
    provider_account_id = $2,
    provider_message_id = $3,
    device_id           = NULL,
    updated_at          = now()
WHERE id = $4
RETURNING id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars
`

type SetMessageProviderParams struct {
	Provider          string
	ProviderAccountID *string
	ProviderMessageID *string
	ID                string
}

// Records which provider took a message, and its ID there.
func (q *Queries) SetMessageProvider(ctx context.Context, arg SetMessageProviderParams) (Message, error) {
	row := q.db.QueryRow(ctx, setMessageProvider,
		arg.Provider,
		arg.ProviderAccountID,
		arg.ProviderMessageID,
		arg.ID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.DeviceID,
		&i.APIKeyID,
		&i.Recipient,
		&i.Sender,
		&i.Body,
		&i.Segments,
		&i.Attempts,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SendingAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UpdatedAt,
		&i.RequestedDeviceID,
		&i.SimSlot,
		&i.AssignedAt,
		&i.IdempotencyHash,
		&i.BodySha256,
		&i.BodyLength,
		&i.BodyRedactedAt,
		&i.Encoding,
		&i.Purpose,
		&i.DisplayBody,
		&i.ProviderAccountID,
		&i.BodyVars,
	)
	return i, err
}

const updateProviderAccount = `-- name: UpdateProviderAccount :one
UPDATE provider_accounts SET
    name            = COALESCE($1, name),
    enabled         = COALESCE($2, enabled),
    priority        = COALESCE($3, priority),
    credentials     = COALESCE($4, credentials),
    credential_hint = COALESCE($5, credential_hint),
    config          = COALESCE($6, config),
    updated_at      = now()
WHERE id = $7 AND project_id = $8
RETURNING id, project_id, kind, name, enabled, priority, credentials, config, credential_hint, callback_token, last_used_at, last_error, created_at, updated_at
`

type UpdateProviderAccountParams struct {
	Name           *string
	Enabled        *bool
	Priority       *int32
	Credentials    []byte
	CredentialHint *string
	Config         []byte
	ID             string
	ProjectID      string
}

func (q *Queries) UpdateProviderAccount(ctx context.Context, arg UpdateProviderAccountParams) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, updateProviderAccount,
		arg.Name,
		arg.Enabled,
		arg.Priority,
		arg.Credentials,
		arg.CredentialHint,
		arg.Config,
		arg.ID,
		arg.ProjectID,
	)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.Credentials,
		&i.Config,
		&i.CredentialHint,
		&i.CallbackToken,
		&i.LastUsedAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRouting = `-- name: UpsertRouting :one
INSERT INTO project_routing (project_id, mode, fallback_after_seconds)
VALUES ($1, $2, $3)
ON CONFLICT (project_id) DO UPDATE SET
    mode = EXCLUDED.mode, fallback_after_seconds = EXCLUDED.fallback_after_seconds, updated_at = now()
RETURNING project_id, mode, fallback_after_seconds, updated_at
`

type UpsertRoutingParams struct {
	ProjectID            string
	Mode                 string
	FallbackAfterSeconds int32
}

func (q *Queries) UpsertRouting(ctx context.Context, arg UpsertRoutingParams) (ProjectRouting, error) {
	row := q.db.QueryRow(ctx, upsertRouting, arg.ProjectID, arg.Mode, arg.FallbackAfterSeconds)
	var i ProjectRouting
	err := row.Scan(
		&i.ProjectID,
		&i.Mode,
		&i.FallbackAfterSeconds,
		&i.UpdatedAt,
	)
	return i, err
}
