// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_logs.sql

package dbq

import (
	"context"
	"time"
)

const dailyRequestUsage = `-- name: DailyRequestUsage :many
SELECT to_char(created_at AT TIME ZONE $1::text, 'YYYY-MM-DD')::text AS day,
       count(*)::int AS requests,
       count(*) FILTER (WHERE status >= 400 AND status < 500)::int AS client_errors,
       count(*) FILTER (WHERE status >= 500)::int AS server_errors,
       COALESCE(percentile_cont(0.95) WITHIN GROUP (ORDER BY duration_ms), 0)::float8 AS p95_ms
FROM api_request_logs
WHERE project_id = $2 AND environment = $3 AND created_at >= $4
GROUP BY 1
ORDER BY 1
`

type DailyRequestUsageParams struct {
	Tz          string
	ProjectID   string
	Environment string
	Since       time.Time
}

type DailyRequestUsageRow struct {
	Day          string
	Requests     int32
	ClientErrors int32
	ServerErrors int32
	P95Ms        float64
}

func (q *Queries) DailyRequestUsage(ctx context.Context, arg DailyRequestUsageParams) ([]DailyRequestUsageRow, error) {
	rows, err := q.db.Query(ctx, dailyRequestUsage,
		arg.Tz,
		arg.ProjectID,
		arg.Environment,
		arg.Since,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyRequestUsageRow{}
	for rows.Next() {
		var i DailyRequestUsageRow
		if err := rows.Scan(
			&i.Day,
			&i.Requests,
			&i.ClientErrors,
			&i.ServerErrors,
			&i.P95Ms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteOldRequestLogs = `-- name: DeleteOldRequestLogs :execrows
DELETE FROM api_request_logs WHERE created_at < $1
`

func (q *Queries) DeleteOldRequestLogs(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldRequestLogs, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRequestLog = `-- name: GetRequestLog :one
SELECT id, request_id, project_id, api_key_id, environment, method, path, status, error_code, duration_ms, ip, user_agent, resource_id, created_at FROM api_request_logs WHERE id = $1 AND project_id = $2
`

type GetRequestLogParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetRequestLog(ctx context.Context, arg GetRequestLogParams) (APIRequestLog, error) {
	row := q.db.QueryRow(ctx, getRequestLog, arg.ID, arg.ProjectID)
	var i APIRequestLog
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.ProjectID,
		&i.APIKeyID,
		&i.Environment,
		&i.Method,
		&i.Path,
		&i.Status,
		&i.ErrorCode,
		&i.DurationMs,
		&i.IP,
		&i.UserAgent,
		&i.ResourceID,
		&i.CreatedAt,
	)
	return i, err
}

const listRequestLogs = `-- name: ListRequestLogs :many
SELECT id, request_id, project_id, api_key_id, environment, method, path, status, error_code, duration_ms, ip, user_agent, resource_id, created_at FROM api_request_logs
WHERE project_id = $1
  AND environment = $2
  AND ($3::text IS NULL OR method = $3)
  AND ($4::int IS NULL OR status >= $4)
  AND ($5::int IS NULL OR status <= $5)
  AND ($6::text IS NULL OR api_key_id = $6)
  AND ($7::text IS NULL OR starts_with(path, $7))
  AND ($8::timestamptz IS NULL
       OR (created_at, id) < ($8::timestamptz, $9::text))
ORDER BY created_at DESC, id DESC
LIMIT $10
`

type ListRequestLogsParams struct {
	ProjectID     string
	Environment   string
	Method        *string
	StatusMin     *int32
	StatusMax     *int32
	APIKeyID      *string
	PathPrefix    *string
	BeforeCreated *time.Time
	BeforeID      *string
	RowLimit      int32
}

func (q *Queries) ListRequestLogs(ctx context.Context, arg ListRequestLogsParams) ([]APIRequestLog, error) {
	rows, err := q.db.Query(ctx, listRequestLogs,
		arg.ProjectID,
		arg.Environment,
		arg.Method,
		arg.StatusMin,
		arg.StatusMax,
		arg.APIKeyID,
		arg.PathPrefix,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []APIRequestLog{}
	for rows.Next() {
		var i APIRequestLog
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.ProjectID,
			&i.APIKeyID,
			&i.Environment,
			&i.Method,
			&i.Path,
			&i.Status,
			&i.ErrorCode,
			&i.DurationMs,
			&i.IP,
			&i.UserAgent,
			&i.ResourceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
