// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package dbq

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSchedule = `-- name: AdvanceSchedule :exec
UPDATE scheduled_messages SET
    next_run_at = $1, last_run_at = $2::timestamptz, run_count = run_count + 1, updated_at = now()
WHERE id = $3
`

type AdvanceScheduleParams struct {
	NextRunAt *time.Time
	RanAt     time.Time
	ID        string
}

func (q *Queries) AdvanceSchedule(ctx context.Context, arg AdvanceScheduleParams) error {
	_, err := q.db.Exec(ctx, advanceSchedule, arg.NextRunAt, arg.RanAt, arg.ID)
	return err
}

const claimDueSchedules = `-- name: ClaimDueSchedules :many
SELECT id, project_id, environment, name, recipient, body, device_id, kind, at_time, days, day_of_month, run_date, time_zone, ends_at, paused, next_run_at, last_run_at, last_message_id, last_error, run_count, api_key_id, created_by, created_at, updated_at FROM scheduled_messages
WHERE NOT paused AND next_run_at IS NOT NULL AND next_run_at <= $1::timestamptz
ORDER BY next_run_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimDueSchedulesParams struct {
	Now      time.Time
	RowLimit int32
}

// Locks due schedules; concurrent workers skip each other's rows.
func (q *Queries) ClaimDueSchedules(ctx context.Context, arg ClaimDueSchedulesParams) ([]ScheduledMessage, error) {
	rows, err := q.db.Query(ctx, claimDueSchedules, arg.Now, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledMessage{}
	for rows.Next() {
		var i ScheduledMessage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Environment,
			&i.Name,
			&i.Recipient,
			&i.Body,
			&i.DeviceID,
			&i.Kind,
			&i.AtTime,
			&i.Days,
			&i.DayOfMonth,
			&i.RunDate,
			&i.TimeZone,
			&i.EndsAt,
			&i.Paused,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastMessageID,
			&i.LastError,
			&i.RunCount,
			&i.APIKeyID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM scheduled_messages WHERE id = $1 AND project_id = $2
`

type DeleteScheduleParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchedule, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, project_id, environment, name, recipient, body, device_id, kind, at_time, days, day_of_month, run_date, time_zone, ends_at, paused, next_run_at, last_run_at, last_message_id, last_error, run_count, api_key_id, created_by, created_at, updated_at FROM scheduled_messages WHERE id = $1 AND project_id = $2
`

type GetScheduleParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetSchedule(ctx context.Context, arg GetScheduleParams) (ScheduledMessage, error) {
	row := q.db.QueryRow(ctx, getSchedule, arg.ID, arg.ProjectID)
	var i ScheduledMessage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Name,
		&i.Recipient,
		&i.Body,
		&i.DeviceID,
		&i.Kind,
		&i.AtTime,
		&i.Days,
		&i.DayOfMonth,
		&i.RunDate,
		&i.TimeZone,
		&i.EndsAt,
		&i.Paused,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastMessageID,
		&i.LastError,
		&i.RunCount,
		&i.APIKeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getScheduleByID = `-- name: GetScheduleByID :one
SELECT id, project_id, environment, name, recipient, body, device_id, kind, at_time, days, day_of_month, run_date, time_zone, ends_at, paused, next_run_at, last_run_at, last_message_id, last_error, run_count, api_key_id, created_by, created_at, updated_at FROM scheduled_messages WHERE id = $1
`

func (q *Queries) GetScheduleByID(ctx context.Context, id string) (ScheduledMessage, error) {
	row := q.db.QueryRow(ctx, getScheduleByID, id)
	var i ScheduledMessage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Name,
		&i.Recipient,
		&i.Body,
		&i.DeviceID,
		&i.Kind,
		&i.AtTime,
		&i.Days,
		&i.DayOfMonth,
		&i.RunDate,
		&i.TimeZone,
		&i.EndsAt,
		&i.Paused,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastMessageID,
		&i.LastError,
		&i.RunCount,
		&i.APIKeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSchedule = `-- name: InsertSchedule :one
INSERT INTO scheduled_messages (
    id, project_id, environment, name, recipient, body, device_id, kind, at_time, days, day_of_month,
    run_date, time_zone, ends_at, paused, next_run_at, api_key_id, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17, $18
)
RETURNING id, project_id, environment, name, recipient, body, device_id, kind, at_time, days, day_of_month, run_date, time_zone, ends_at, paused, next_run_at, last_run_at, last_message_id, last_error, run_count, api_key_id, created_by, created_at, updated_at
`

type InsertScheduleParams struct {
	ID          string
	ProjectID   string
	Environment APIEnvironment
	Name        string
	Recipient   string
	Body        string
	DeviceID    *string
	Kind        string
	AtTime      string
	Days        []string
	DayOfMonth  *int16
	RunDate     pgtype.Date
	TimeZone    string
	EndsAt      *time.Time
	Paused      bool
	NextRunAt   *time.Time
	APIKeyID    *string
	CreatedBy   *string
}

func (q *Queries) InsertSchedule(ctx context.Context, arg InsertScheduleParams) (ScheduledMessage, error) {
	row := q.db.QueryRow(ctx, insertSchedule,
		arg.ID,
		arg.ProjectID,
		arg.Environment,
		arg.Name,
		arg.Recipient,
		arg.Body,
		arg.DeviceID,
		arg.Kind,
		arg.AtTime,
		arg.Days,
		arg.DayOfMonth,
		arg.RunDate,
		arg.TimeZone,
		arg.EndsAt,
		arg.Paused,
		arg.NextRunAt,
		arg.APIKeyID,
		arg.CreatedBy,
	)
	var i ScheduledMessage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Name,
		&i.Recipient,
		&i.Body,
		&i.DeviceID,
		&i.Kind,
		&i.AtTime,
		&i.Days,
		&i.DayOfMonth,
		&i.RunDate,
		&i.TimeZone,
		&i.EndsAt,
		&i.Paused,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastMessageID,
		&i.LastError,
		&i.RunCount,
		&i.APIKeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, project_id, environment, name, recipient, body, device_id, kind, at_time, days, day_of_month, run_date, time_zone, ends_at, paused, next_run_at, last_run_at, last_message_id, last_error, run_count, api_key_id, created_by, created_at, updated_at FROM scheduled_messages
WHERE project_id = $1 AND environment = $2
  AND ($3::timestamptz IS NULL
       OR (created_at, id) < ($3::timestamptz, $4::text))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListSchedulesParams struct {
	ProjectID     string
	Environment   APIEnvironment
	BeforeCreated *time.Time
	BeforeID      *string
	RowLimit      int32
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]ScheduledMessage, error) {
	rows, err := q.db.Query(ctx, listSchedules,
		arg.ProjectID,
		arg.Environment,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduledMessage{}
	for rows.Next() {
		var i ScheduledMessage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Environment,
			&i.Name,
			&i.Recipient,
			&i.Body,
			&i.DeviceID,
			&i.Kind,
			&i.AtTime,
			&i.Days,
			&i.DayOfMonth,
			&i.RunDate,
			&i.TimeZone,
			&i.EndsAt,
			&i.Paused,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastMessageID,
			&i.LastError,
			&i.RunCount,
			&i.APIKeyID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordScheduleResult = `-- name: RecordScheduleResult :exec
UPDATE scheduled_messages SET
    last_message_id = COALESCE($1::text, last_message_id),
    last_error = $2, updated_at = now()
WHERE id = $3
`

type RecordScheduleResultParams struct {
	LastMessageID *string
	LastError     *string
	ID            string
}

func (q *Queries) RecordScheduleResult(ctx context.Context, arg RecordScheduleResultParams) error {
	_, err := q.db.Exec(ctx, recordScheduleResult, arg.LastMessageID, arg.LastError, arg.ID)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE scheduled_messages SET
    name = $1, recipient = $2, body = $3, device_id = $4,
    kind = $5, at_time = $6, days = $7, day_of_month = $8,
    run_date = $9, time_zone = $10, ends_at = $11,
    paused = $12, next_run_at = $13, updated_at = now()
WHERE id = $14 AND project_id = $15
RETURNING id, project_id, environment, name, recipient, body, device_id, kind, at_time, days, day_of_month, run_date, time_zone, ends_at, paused, next_run_at, last_run_at, last_message_id, last_error, run_count, api_key_id, created_by, created_at, updated_at
`

type UpdateScheduleParams struct {
	Name       string
	Recipient  string
	Body       string
	DeviceID   *string
	Kind       string
	AtTime     string
	Days       []string
	DayOfMonth *int16
	RunDate    pgtype.Date
	TimeZone   string
	EndsAt     *time.Time
	Paused     bool
	NextRunAt  *time.Time
	ID         string
	ProjectID  string
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (ScheduledMessage, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.Name,
		arg.Recipient,
		arg.Body,
		arg.DeviceID,
		arg.Kind,
		arg.AtTime,
		arg.Days,
		arg.DayOfMonth,
		arg.RunDate,
		arg.TimeZone,
		arg.EndsAt,
		arg.Paused,
		arg.NextRunAt,
		arg.ID,
		arg.ProjectID,
	)
	var i ScheduledMessage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Name,
		&i.Recipient,
		&i.Body,
		&i.DeviceID,
		&i.Kind,
		&i.AtTime,
		&i.Days,
		&i.DayOfMonth,
		&i.RunDate,
		&i.TimeZone,
		&i.EndsAt,
		&i.Paused,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastMessageID,
		&i.LastError,
		&i.RunCount,
		&i.APIKeyID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
