// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status.sql

package dbq

import (
	"context"
	"time"
)

const dailyStatus = `-- name: DailyStatus :many
SELECT component,
       to_char(sampled_at AT TIME ZONE 'UTC', 'YYYY-MM-DD')::text AS day,
       count(*)::int AS samples,
       count(*) FILTER (WHERE status <> 'outage')::int AS up,
       count(*) FILTER (WHERE status = 'operational')::int AS operational
FROM status_samples
WHERE sampled_at >= $1
GROUP BY 1, 2
ORDER BY 1, 2
`

type DailyStatusRow struct {
	Component   string
	Day         string
	Samples     int32
	Up          int32
	Operational int32
}

// Per component and UTC day: samples taken and how many were not an outage
// or not degraded. Days without samples are missing (no data, not downtime).
func (q *Queries) DailyStatus(ctx context.Context, since time.Time) ([]DailyStatusRow, error) {
	rows, err := q.db.Query(ctx, dailyStatus, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyStatusRow{}
	for rows.Next() {
		var i DailyStatusRow
		if err := rows.Scan(
			&i.Component,
			&i.Day,
			&i.Samples,
			&i.Up,
			&i.Operational,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteHeartbeat = `-- name: DeleteHeartbeat :exec
DELETE FROM instance_heartbeats WHERE instance_id = $1
`

func (q *Queries) DeleteHeartbeat(ctx context.Context, instanceID string) error {
	_, err := q.db.Exec(ctx, deleteHeartbeat, instanceID)
	return err
}

const deleteOldStatusSamples = `-- name: DeleteOldStatusSamples :execrows
DELETE FROM status_samples WHERE sampled_at < $1
`

func (q *Queries) DeleteOldStatusSamples(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldStatusSamples, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const firstUserEmail = `-- name: FirstUserEmail :one
SELECT email FROM users ORDER BY created_at, id LIMIT 1
`

func (q *Queries) FirstUserEmail(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, firstUserEmail)
	var email string
	err := row.Scan(&email)
	return email, err
}

const fleetStats = `-- name: FleetStats :one
SELECT count(*) FILTER (WHERE revoked_at IS NULL)::int AS total,
       count(*) FILTER (WHERE revoked_at IS NULL AND status = 'online')::int AS online
FROM devices
`

type FleetStatsRow struct {
	Total  int32
	Online int32
}

func (q *Queries) FleetStats(ctx context.Context) (FleetStatsRow, error) {
	row := q.db.QueryRow(ctx, fleetStats)
	var i FleetStatsRow
	err := row.Scan(&i.Total, &i.Online)
	return i, err
}

const insertStatusSample = `-- name: InsertStatusSample :exec
INSERT INTO status_samples (component, sampled_at, status, value, detail)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (component, sampled_at) DO UPDATE SET status = EXCLUDED.status, value = EXCLUDED.value, detail = EXCLUDED.detail
`

type InsertStatusSampleParams struct {
	Component string
	SampledAt time.Time
	Status    string
	Value     *float64
	Detail    string
}

func (q *Queries) InsertStatusSample(ctx context.Context, arg InsertStatusSampleParams) error {
	_, err := q.db.Exec(ctx, insertStatusSample,
		arg.Component,
		arg.SampledAt,
		arg.Status,
		arg.Value,
		arg.Detail,
	)
	return err
}

const latestStatusSamples = `-- name: LatestStatusSamples :many
SELECT DISTINCT ON (component) component, sampled_at, status, value, detail FROM status_samples
WHERE sampled_at > now() - interval '10 minutes'
ORDER BY component, sampled_at DESC
`

func (q *Queries) LatestStatusSamples(ctx context.Context) ([]StatusSample, error) {
	rows, err := q.db.Query(ctx, latestStatusSamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusSample{}
	for rows.Next() {
		var i StatusSample
		if err := rows.Scan(
			&i.Component,
			&i.SampledAt,
			&i.Status,
			&i.Value,
			&i.Detail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeats = `-- name: ListHeartbeats :many
SELECT instance_id, kind, version, hostname, started_at, seen_at FROM instance_heartbeats WHERE seen_at > now() - interval '1 hour' ORDER BY kind, started_at
`

func (q *Queries) ListHeartbeats(ctx context.Context) ([]InstanceHeartbeat, error) {
	rows, err := q.db.Query(ctx, listHeartbeats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstanceHeartbeat{}
	for rows.Next() {
		var i InstanceHeartbeat
		if err := rows.Scan(
			&i.InstanceID,
			&i.Kind,
			&i.Version,
			&i.Hostname,
			&i.StartedAt,
			&i.SeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageBacklog = `-- name: MessageBacklog :one
SELECT count(*)::int AS waiting,
       COALESCE(EXTRACT(EPOCH FROM now() - min(created_at)), 0)::float8 AS oldest_seconds
FROM messages WHERE status = 'queued' AND device_id IS NULL AND provider = 'android'
`

type MessageBacklogRow struct {
	Waiting       int32
	OldestSeconds float64
}

func (q *Queries) MessageBacklog(ctx context.Context) (MessageBacklogRow, error) {
	row := q.db.QueryRow(ctx, messageBacklog)
	var i MessageBacklogRow
	err := row.Scan(&i.Waiting, &i.OldestSeconds)
	return i, err
}

const upsertHeartbeat = `-- name: UpsertHeartbeat :exec
INSERT INTO instance_heartbeats (instance_id, kind, version, hostname, started_at, seen_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (instance_id) DO UPDATE SET seen_at = now(), version = EXCLUDED.version
`

type UpsertHeartbeatParams struct {
	InstanceID string
	Kind       string
	Version    string
	Hostname   string
	StartedAt  time.Time
}

func (q *Queries) UpsertHeartbeat(ctx context.Context, arg UpsertHeartbeatParams) error {
	_, err := q.db.Exec(ctx, upsertHeartbeat,
		arg.InstanceID,
		arg.Kind,
		arg.Version,
		arg.Hostname,
		arg.StartedAt,
	)
	return err
}
