// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package dbq

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"
)

const claimInvite = `-- name: ClaimInvite :one
UPDATE organization_invites SET accepted_at = now(), accepted_by = $1
WHERE token_hash = $2 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > now()
RETURNING id, organization_id, token_hash, role, email, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at
`

type ClaimInviteParams struct {
	UserID    *string
	TokenHash []byte
}

// Marks the invite used, once, in the accepting transaction.
func (q *Queries) ClaimInvite(ctx context.Context, arg ClaimInviteParams) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, claimInvite, arg.UserID, arg.TokenHash)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TokenHash,
		&i.Role,
		&i.Email,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*)::int FROM organization_members WHERE organization_id = $1 AND role = 'owner'
`

func (q *Queries) CountOwners(ctx context.Context, organizationID string) (int32, error) {
	row := q.db.QueryRow(ctx, countOwners, organizationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countProjects = `-- name: CountProjects :one
SELECT count(*)::int FROM projects WHERE organization_id = $1
`

func (q *Queries) CountProjects(ctx context.Context, organizationID string) (int32, error) {
	row := q.db.QueryRow(ctx, countProjects, organizationID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO organization_invites (id, organization_id, token_hash, role, email, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, token_hash, role, email, invited_by, expires_at, accepted_at, accepted_by, revoked_at, created_at
`

type CreateInviteParams struct {
	ID             string
	OrganizationID string
	TokenHash      []byte
	Role           MemberRole
	Email          string
	InvitedBy      *string
	ExpiresAt      time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (OrganizationInvite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ID,
		arg.OrganizationID,
		arg.TokenHash,
		arg.Role,
		arg.Email,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i OrganizationInvite
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TokenHash,
		&i.Role,
		&i.Email,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :execrows
DELETE FROM organization_members WHERE id = $1 AND organization_id = $2
`

type DeleteMemberParams struct {
	ID             string
	OrganizationID string
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMember, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :execrows
DELETE FROM sessions WHERE user_id = $1 AND id <> $2
`

type DeleteOtherSessionsParams struct {
	UserID string
	KeepID string
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherSessions, arg.UserID, arg.KeepID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

type DeleteSessionParams struct {
	ID     string
	UserID string
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSoleMemberOrganizations = `-- name: DeleteSoleMemberOrganizations :execrows
DELETE FROM organizations o
WHERE EXISTS (SELECT 1 FROM organization_members m WHERE m.organization_id = o.id AND m.user_id = $1)
  AND (SELECT count(*) FROM organization_members m WHERE m.organization_id = o.id) = 1
`

func (q *Queries) DeleteSoleMemberOrganizations(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSoleMemberOrganizations, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAuditLog = `-- name: GetAuditLog :one
SELECT id, organization_id, project_id, actor_type, actor_id, action, target_type, target_id, metadata, ip, created_at FROM audit_logs WHERE id = $1 AND organization_id = $2
`

type GetAuditLogParams struct {
	ID             string
	OrganizationID string
}

func (q *Queries) GetAuditLog(ctx context.Context, arg GetAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLog, arg.ID, arg.OrganizationID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ProjectID,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Metadata,
		&i.IP,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT i.id, i.organization_id, i.token_hash, i.role, i.email, i.invited_by, i.expires_at, i.accepted_at, i.accepted_by, i.revoked_at, i.created_at, o.name AS organization_name, COALESCE(u.name, '')::text AS inviter_name
FROM organization_invites i
JOIN organizations o ON o.id = i.organization_id
LEFT JOIN users u ON u.id = i.invited_by
WHERE i.token_hash = $1
`

type GetInviteByTokenRow struct {
	ID               string
	OrganizationID   string
	TokenHash        []byte
	Role             MemberRole
	Email            string
	InvitedBy        *string
	ExpiresAt        time.Time
	AcceptedAt       *time.Time
	AcceptedBy       *string
	RevokedAt        *time.Time
	CreatedAt        time.Time
	OrganizationName string
	InviterName      string
}

func (q *Queries) GetInviteByToken(ctx context.Context, tokenHash []byte) (GetInviteByTokenRow, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, tokenHash)
	var i GetInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TokenHash,
		&i.Role,
		&i.Email,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedBy,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.OrganizationName,
		&i.InviterName,
	)
	return i, err
}

const getMember = `-- name: GetMember :one
SELECT id, organization_id, user_id, role, created_at FROM organization_members WHERE id = $1 AND organization_id = $2
`

type GetMemberParams struct {
	ID             string
	OrganizationID string
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.ID, arg.OrganizationID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.organization_id, a.project_id, a.actor_type, a.actor_id, a.action, a.target_type, a.target_id, a.metadata, a.ip, a.created_at,
       COALESCE(u.name, k.name, d.name, '')::text AS actor_name,
       COALESCE(u.email, '')::text AS actor_email,
       COALESCE(p.name, '')::text AS project_name
FROM audit_logs a
LEFT JOIN users u ON a.actor_type = 'user' AND u.id = a.actor_id
LEFT JOIN api_keys k ON a.actor_type = 'api_key' AND k.id = a.actor_id
LEFT JOIN devices d ON a.actor_type = 'device' AND d.id = a.actor_id
LEFT JOIN projects p ON p.id = a.project_id
WHERE a.organization_id = $1
  AND ($2::text IS NULL OR a.project_id = $2)
  AND ($3::text IS NULL OR starts_with(a.action, $3))
  AND ($4::text IS NULL OR a.actor_id = $4)
  AND ($5::timestamptz IS NULL
       OR (a.created_at, a.id) < ($5::timestamptz, $6::text))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $7
`

type ListAuditLogsParams struct {
	OrganizationID string
	ProjectID      *string
	ActionPrefix   *string
	ActorID        *string
	BeforeCreated  *time.Time
	BeforeID       *string
	RowLimit       int32
}

type ListAuditLogsRow struct {
	ID             string
	OrganizationID string
	ProjectID      *string
	ActorType      string
	ActorID        *string
	Action         string
	TargetType     *string
	TargetID       *string
	Metadata       json.RawMessage
	IP             *netip.Addr
	CreatedAt      time.Time
	ActorName      string
	ActorEmail     string
	ProjectName    string
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.OrganizationID,
		arg.ProjectID,
		arg.ActionPrefix,
		arg.ActorID,
		arg.BeforeCreated,
		arg.BeforeID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ProjectID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Metadata,
			&i.IP,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorEmail,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.id, m.organization_id, m.user_id, m.role, m.created_at, u.email, u.name,
       COALESCE((SELECT max(s.last_seen_at) FROM sessions s WHERE s.user_id = u.id), m.created_at)::timestamptz AS last_active_at
FROM organization_members m
JOIN users u ON u.id = m.user_id
WHERE m.organization_id = $1
ORDER BY CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END, m.created_at, m.id
`

type ListMembersRow struct {
	ID             string
	OrganizationID string
	UserID         string
	Role           MemberRole
	CreatedAt      time.Time
	Email          string
	Name           string
	LastActiveAt   time.Time
}

func (q *Queries) ListMembers(ctx context.Context, organizationID string) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.Name,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvites = `-- name: ListPendingInvites :many
SELECT i.id, i.organization_id, i.token_hash, i.role, i.email, i.invited_by, i.expires_at, i.accepted_at, i.accepted_by, i.revoked_at, i.created_at, COALESCE(u.name, '')::text AS inviter_name, COALESCE(u.email, '')::text AS inviter_email
FROM organization_invites i
LEFT JOIN users u ON u.id = i.invited_by
WHERE i.organization_id = $1 AND i.accepted_at IS NULL AND i.revoked_at IS NULL AND i.expires_at > now()
ORDER BY i.created_at DESC
`

type ListPendingInvitesRow struct {
	ID             string
	OrganizationID string
	TokenHash      []byte
	Role           MemberRole
	Email          string
	InvitedBy      *string
	ExpiresAt      time.Time
	AcceptedAt     *time.Time
	AcceptedBy     *string
	RevokedAt      *time.Time
	CreatedAt      time.Time
	InviterName    string
	InviterEmail   string
}

func (q *Queries) ListPendingInvites(ctx context.Context, organizationID string) ([]ListPendingInvitesRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvites, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitesRow{}
	for rows.Next() {
		var i ListPendingInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TokenHash,
			&i.Role,
			&i.Email,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedBy,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.InviterName,
			&i.InviterEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT id, user_id, token_hash, ip, user_agent, created_at, last_seen_at, expires_at FROM sessions WHERE user_id = $1 AND expires_at > now() ORDER BY last_seen_at DESC
`

func (q *Queries) ListSessionsForUser(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.IP,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const organizationsBlockingDeletion = `-- name: OrganizationsBlockingDeletion :many
SELECT o.id, o.name FROM organizations o
JOIN organization_members m ON m.organization_id = o.id AND m.user_id = $1 AND m.role = 'owner'
WHERE (SELECT count(*) FROM organization_members x WHERE x.organization_id = o.id AND x.role = 'owner') = 1
  AND (SELECT count(*) FROM organization_members x WHERE x.organization_id = o.id) > 1
`

type OrganizationsBlockingDeletionRow struct {
	ID   string
	Name string
}

// Organizations the user owns alone while others are members: ownership must move first.
func (q *Queries) OrganizationsBlockingDeletion(ctx context.Context, userID string) ([]OrganizationsBlockingDeletionRow, error) {
	rows, err := q.db.Query(ctx, organizationsBlockingDeletion, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationsBlockingDeletionRow{}
	for rows.Next() {
		var i OrganizationsBlockingDeletionRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectDevices = `-- name: ProjectDevices :many
SELECT id FROM devices WHERE project_id = $1 AND revoked_at IS NULL
`

func (q *Queries) ProjectDevices(ctx context.Context, projectID string) ([]string, error) {
	rows, err := q.db.Query(ctx, projectDevices, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE organization_invites SET revoked_at = now()
WHERE id = $1 AND organization_id = $2 AND accepted_at IS NULL AND revoked_at IS NULL
`

type RevokeInviteParams struct {
	ID             string
	OrganizationID string
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const roleForOrganization = `-- name: RoleForOrganization :one
SELECT role FROM organization_members WHERE organization_id = $1 AND user_id = $2
`

type RoleForOrganizationParams struct {
	OrganizationID string
	UserID         string
}

func (q *Queries) RoleForOrganization(ctx context.Context, arg RoleForOrganizationParams) (MemberRole, error) {
	row := q.db.QueryRow(ctx, roleForOrganization, arg.OrganizationID, arg.UserID)
	var role MemberRole
	err := row.Scan(&role)
	return role, err
}

const roleForProject = `-- name: RoleForProject :one
SELECT m.role FROM projects p
JOIN organization_members m ON m.organization_id = p.organization_id
WHERE p.id = $1 AND m.user_id = $2
`

type RoleForProjectParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) RoleForProject(ctx context.Context, arg RoleForProjectParams) (MemberRole, error) {
	row := q.db.QueryRow(ctx, roleForProject, arg.ProjectID, arg.UserID)
	var role MemberRole
	err := row.Scan(&role)
	return role, err
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE organization_members SET role = $1 WHERE id = $2 AND organization_id = $3 RETURNING id, organization_id, user_id, role, created_at
`

type UpdateMemberRoleParams struct {
	Role           MemberRole
	ID             string
	OrganizationID string
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.Role, arg.ID, arg.OrganizationID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const updateOrganizationName = `-- name: UpdateOrganizationName :one
UPDATE organizations SET name = $1, updated_at = now() WHERE id = $2 RETURNING id, name, slug, created_at, updated_at
`

type UpdateOrganizationNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateOrganizationName(ctx context.Context, arg UpdateOrganizationNameParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganizationName, arg.Name, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users SET name = $1, updated_at = now() WHERE id = $2 RETURNING id, email, name, password_hash, email_verified_at, created_at, updated_at, phone, phone_verified_at
`

type UpdateUserNameParams struct {
	Name string
	ID   string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.Name, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Phone,
		&i.PhoneVerifiedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1, updated_at = now() WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
