// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package dbq

import (
	"context"
	"encoding/json"
	"time"
)

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (id, project_id, url, description, events, secret)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, url, description, events, secret, enabled, disabled_reason, failing_since, last_success_at, last_failure_at, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	ID          string
	ProjectID   string
	URL         string
	Description string
	Events      []string
	Secret      string
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.ID,
		arg.ProjectID,
		arg.URL,
		arg.Description,
		arg.Events,
		arg.Secret,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.URL,
		&i.Description,
		&i.Events,
		&i.Secret,
		&i.Enabled,
		&i.DisabledReason,
		&i.FailingSince,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldWebhookEvents = `-- name: DeleteOldWebhookEvents :execrows
DELETE FROM webhook_events WHERE created_at < $1
`

func (q *Queries) DeleteOldWebhookEvents(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldWebhookEvents, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :execrows
DELETE FROM webhook_endpoints WHERE id = $1 AND project_id = $2
`

type DeleteWebhookEndpointParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookEndpoint, arg.ID, arg.ProjectID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const disableWebhookEndpoint = `-- name: DisableWebhookEndpoint :exec
UPDATE webhook_endpoints SET enabled = false, disabled_reason = $2, updated_at = now() WHERE id = $1
`

type DisableWebhookEndpointParams struct {
	ID             string
	DisabledReason *string
}

func (q *Queries) DisableWebhookEndpoint(ctx context.Context, arg DisableWebhookEndpointParams) error {
	_, err := q.db.Exec(ctx, disableWebhookEndpoint, arg.ID, arg.DisabledReason)
	return err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, project_id, url, description, events, secret, enabled, disabled_reason, failing_since, last_success_at, last_failure_at, created_at, updated_at FROM webhook_endpoints WHERE id = $1 AND project_id = $2
`

type GetWebhookEndpointParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) GetWebhookEndpoint(ctx context.Context, arg GetWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpoint, arg.ID, arg.ProjectID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.URL,
		&i.Description,
		&i.Events,
		&i.Secret,
		&i.Enabled,
		&i.DisabledReason,
		&i.FailingSince,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEndpointByID = `-- name: GetWebhookEndpointByID :one
SELECT id, project_id, url, description, events, secret, enabled, disabled_reason, failing_since, last_success_at, last_failure_at, created_at, updated_at FROM webhook_endpoints WHERE id = $1
`

func (q *Queries) GetWebhookEndpointByID(ctx context.Context, id string) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByID, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.URL,
		&i.Description,
		&i.Events,
		&i.Secret,
		&i.Enabled,
		&i.DisabledReason,
		&i.FailingSince,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEvent = `-- name: GetWebhookEvent :one
SELECT id, project_id, type, payload, created_at FROM webhook_events WHERE id = $1
`

func (q *Queries) GetWebhookEvent(ctx context.Context, id string) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEvent, id)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const insertInboundMessage = `-- name: InsertInboundMessage :one
INSERT INTO messages (
    id, project_id, environment, direction, status, provider, device_id, recipient, sender, body,
    segments, encoding, idempotency_key, sim_slot, body_sha256, body_length, metadata
) VALUES (
    $1, $2, 'live', 'inbound', 'received', 'android', $3, '', $4, $5,
    $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (project_id, idempotency_key) DO NOTHING
RETURNING id, project_id, environment, direction, status, provider, device_id, api_key_id, recipient, sender, body, segments, attempts, provider_message_id, error_code, error_message, metadata, idempotency_key, created_at, queued_at, sending_at, sent_at, delivered_at, failed_at, updated_at, requested_device_id, sim_slot, assigned_at, idempotency_hash, body_sha256, body_length, body_redacted_at, encoding, purpose, display_body, provider_account_id, body_vars
`

type InsertInboundMessageParams struct {
	ID             string
	ProjectID      string
	DeviceID       *string
	Sender         *string
	Body           string
	Segments       *int16
	Encoding       *string
	IdempotencyKey *string
	SimSlot        *int16
	BodySha256     []byte
	BodyLength     *int32
	Metadata       json.RawMessage
}

func (q *Queries) InsertInboundMessage(ctx context.Context, arg InsertInboundMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertInboundMessage,
		arg.ID,
		arg.ProjectID,
		arg.DeviceID,
		arg.Sender,
		arg.Body,
		arg.Segments,
		arg.Encoding,
		arg.IdempotencyKey,
		arg.SimSlot,
		arg.BodySha256,
		arg.BodyLength,
		arg.Metadata,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Environment,
		&i.Direction,
		&i.Status,
		&i.Provider,
		&i.DeviceID,
		&i.APIKeyID,
		&i.Recipient,
		&i.Sender,
		&i.Body,
		&i.Segments,
		&i.Attempts,
		&i.ProviderMessageID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.SendingAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.UpdatedAt,
		&i.RequestedDeviceID,
		&i.SimSlot,
		&i.AssignedAt,
		&i.IdempotencyHash,
		&i.BodySha256,
		&i.BodyLength,
		&i.BodyRedactedAt,
		&i.Encoding,
		&i.Purpose,
		&i.DisplayBody,
		&i.ProviderAccountID,
		&i.BodyVars,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :exec
INSERT INTO webhook_deliveries (id, endpoint_id, event_id, attempt, succeeded, response_status, response_body, error, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertWebhookDeliveryParams struct {
	ID             string
	EndpointID     string
	EventID        string
	Attempt        int32
	Succeeded      bool
	ResponseStatus *int32
	ResponseBody   *string
	Error          *string
	DurationMs     int32
}

func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, insertWebhookDelivery,
		arg.ID,
		arg.EndpointID,
		arg.EventID,
		arg.Attempt,
		arg.Succeeded,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.Error,
		arg.DurationMs,
	)
	return err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one
INSERT INTO webhook_events (id, project_id, type, payload) VALUES ($1, $2, $3, $4) RETURNING id, project_id, type, payload, created_at
`

type InsertWebhookEventParams struct {
	ID        string
	ProjectID string
	Type      string
	Payload   json.RawMessage
}

func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent,
		arg.ID,
		arg.ProjectID,
		arg.Type,
		arg.Payload,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT d.id, d.endpoint_id, d.event_id, d.attempt, d.succeeded, d.response_status, d.response_body, d.error, d.duration_ms, d.created_at, e.type AS event_type
FROM webhook_deliveries d
JOIN webhook_events e ON e.id = d.event_id
WHERE d.endpoint_id = $1
ORDER BY d.created_at DESC, d.id DESC
LIMIT $2
`

type ListWebhookDeliveriesParams struct {
	EndpointID string
	Limit      int32
}

type ListWebhookDeliveriesRow struct {
	ID             string
	EndpointID     string
	EventID        string
	Attempt        int32
	Succeeded      bool
	ResponseStatus *int32
	ResponseBody   *string
	Error          *string
	DurationMs     int32
	CreatedAt      time.Time
	EventType      string
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.EndpointID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWebhookDeliveriesRow{}
	for rows.Next() {
		var i ListWebhookDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.EndpointID,
			&i.EventID,
			&i.Attempt,
			&i.Succeeded,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.Error,
			&i.DurationMs,
			&i.CreatedAt,
			&i.EventType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, project_id, url, description, events, secret, enabled, disabled_reason, failing_since, last_success_at, last_failure_at, created_at, updated_at FROM webhook_endpoints WHERE project_id = $1 ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListWebhookEndpoints(ctx context.Context, projectID string) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.URL,
			&i.Description,
			&i.Events,
			&i.Secret,
			&i.Enabled,
			&i.DisabledReason,
			&i.FailingSince,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookFailure = `-- name: MarkWebhookFailure :one
UPDATE webhook_endpoints SET
    last_failure_at = now(),
    failing_since = COALESCE(failing_since, now()),
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, url, description, events, secret, enabled, disabled_reason, failing_since, last_success_at, last_failure_at, created_at, updated_at
`

func (q *Queries) MarkWebhookFailure(ctx context.Context, id string) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, markWebhookFailure, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.URL,
		&i.Description,
		&i.Events,
		&i.Secret,
		&i.Enabled,
		&i.DisabledReason,
		&i.FailingSince,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWebhookSuccess = `-- name: MarkWebhookSuccess :exec
UPDATE webhook_endpoints SET last_success_at = now(), failing_since = NULL, updated_at = now() WHERE id = $1
`

func (q *Queries) MarkWebhookSuccess(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markWebhookSuccess, id)
	return err
}

const presenceChanges = `-- name: PresenceChanges :many
SELECT id, project_id, name, installation_id, credential_hash, status, last_heartbeat_at, last_seen_at, battery_level, is_charging, network_type, carrier_name, sim_count, device_model, android_version, app_version, created_at, updated_at, revoked_at, push_provider, push_endpoint, push_p256dh, push_auth, push_updated_at, connection_id, connected_at, heartbeat_interval, app_flavor, preferred_sim_slot, send_limit_count, send_limit_window_seconds, sims, forward_inbound, notified_presence, daily_send_limit FROM devices
WHERE revoked_at IS NULL
  AND ((status = 'online' AND notified_presence IS DISTINCT FROM 'online')
    OR (status <> 'online' AND notified_presence = 'online' AND last_seen_at < $1))
LIMIT 500
`

// Devices whose presence differs from the last device.* webhook. Offline is
// reported only after a grace period so a quick reconnect is not an event.
func (q *Queries) PresenceChanges(ctx context.Context, offlineBefore *time.Time) ([]Device, error) {
	rows, err := q.db.Query(ctx, presenceChanges, offlineBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.InstallationID,
			&i.CredentialHash,
			&i.Status,
			&i.LastHeartbeatAt,
			&i.LastSeenAt,
			&i.BatteryLevel,
			&i.IsCharging,
			&i.NetworkType,
			&i.CarrierName,
			&i.SimCount,
			&i.DeviceModel,
			&i.AndroidVersion,
			&i.AppVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
			&i.PushProvider,
			&i.PushEndpoint,
			&i.PushP256dh,
			&i.PushAuth,
			&i.PushUpdatedAt,
			&i.ConnectionID,
			&i.ConnectedAt,
			&i.HeartbeatInterval,
			&i.AppFlavor,
			&i.PreferredSimSlot,
			&i.SendLimitCount,
			&i.SendLimitWindowSeconds,
			&i.Sims,
			&i.ForwardInbound,
			&i.NotifiedPresence,
			&i.DailySendLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateWebhookSecret = `-- name: RotateWebhookSecret :one
UPDATE webhook_endpoints SET secret = $1, updated_at = now()
WHERE id = $2 AND project_id = $3
RETURNING id, project_id, url, description, events, secret, enabled, disabled_reason, failing_since, last_success_at, last_failure_at, created_at, updated_at
`

type RotateWebhookSecretParams struct {
	Secret    string
	ID        string
	ProjectID string
}

func (q *Queries) RotateWebhookSecret(ctx context.Context, arg RotateWebhookSecretParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, rotateWebhookSecret, arg.Secret, arg.ID, arg.ProjectID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.URL,
		&i.Description,
		&i.Events,
		&i.Secret,
		&i.Enabled,
		&i.DisabledReason,
		&i.FailingSince,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setNotifiedPresence = `-- name: SetNotifiedPresence :execrows
UPDATE devices SET notified_presence = $1
WHERE id = $2 AND notified_presence IS DISTINCT FROM $1
`

type SetNotifiedPresenceParams struct {
	Presence *string
	ID       string
}

func (q *Queries) SetNotifiedPresence(ctx context.Context, arg SetNotifiedPresenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNotifiedPresence, arg.Presence, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const subscribedEndpoints = `-- name: SubscribedEndpoints :many
SELECT id FROM webhook_endpoints
WHERE project_id = $1 AND enabled
  AND (cardinality(events) = 0 OR $2::text = ANY(events))
`

type SubscribedEndpointsParams struct {
	ProjectID string
	EventType string
}

func (q *Queries) SubscribedEndpoints(ctx context.Context, arg SubscribedEndpointsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, subscribedEndpoints, arg.ProjectID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :one
UPDATE webhook_endpoints SET
    url = COALESCE($1::text, url),
    description = COALESCE($2::text, description),
    events = COALESCE($3::text[], events),
    enabled = COALESCE($4::bool, enabled),
    disabled_reason = CASE WHEN $4::bool THEN NULL ELSE disabled_reason END,
    failing_since = CASE WHEN $4::bool THEN NULL ELSE failing_since END,
    updated_at = now()
WHERE id = $5 AND project_id = $6
RETURNING id, project_id, url, description, events, secret, enabled, disabled_reason, failing_since, last_success_at, last_failure_at, created_at, updated_at
`

type UpdateWebhookEndpointParams struct {
	URL         *string
	Description *string
	Events      []string
	Enabled     *bool
	ID          string
	ProjectID   string
}

func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, updateWebhookEndpoint,
		arg.URL,
		arg.Description,
		arg.Events,
		arg.Enabled,
		arg.ID,
		arg.ProjectID,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.URL,
		&i.Description,
		&i.Events,
		&i.Secret,
		&i.Enabled,
		&i.DisabledReason,
		&i.FailingSince,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
